### ISSUE TITLE
Why mdk-sdk is no longer available?

### ISSUE THREAD

**Issue by oomek** [wang-bin/mdk-sdk#1]
The repo is empty. Would you please explain why?

**Comment by oomek** [comment]
I've seen the sourceforge link, but the include directory is empty.

**Comment by wang-bin** [comment]
I will upload new packages and push headers tomorrow

**Comment by wang-bin** [comment]
1 day later.

**Comment by oomek** [comment]
Out of curiosity. Does your player also use OMX_UseEGLImage() or just renders natively on RPI?

**Comment by wang-bin** [comment]
I use mmal and eglimage. I have studied omx and how to get max rendering performance. A generic solution is providing custom buffer header. But not sure what is it on rpi, maybe vcsm. Another is eglimage.

**Comment by oomek** [comment]
I was experimenting with openmax api on the Raspberry Pi for the last month, but I'm still struggling with achieving satisfying results. The goal is to draw the video on the sfml texture that would allow me to make transforms like rotate/pinch/skew. For now I just have it drawing on the opengl texture, but I get tearing. When I added double buffering I get uneven framerates. Would you share a little insight on this matter?

**Comment by oomek** [comment]
This is supposed to be replacement for the current implementation that uses mmal decoder and sws_scale, and then updating sfml image with a pixel buffer which has terrible performance caused by copying the frames 3 times between CPU-GPU memory.

**Comment by wang-bin** [comment]
> For now I just have it drawing on the opengl texture, but I get tearing. 
How do you draw the frames?

I use an egl extension to convert decoded frame to eglimage(you can find it in official examples), then use eglimage as a texture. cpu load < 15% for 1080p videos, a litter higher than omxplayer, but better than others.

btw, how do you create an eglimage for omx?

**Comment by oomek** [comment]
This is a fork of another media player I'm trying to adapt to work with Attract Mode on the Raspberry Pi
https://github.com/oomek/rpi-mediaplayer

I use OMX_UseEGLImage on a set of gl textures and alternate between them. Then I draw using opengl. Later I'm planning to integrate it with sfml so I take texture.getNativeHandle() and decode with OMX.

Unfortunately there is tearing when I draw directly with single buffer on the texture and double/triple buffering would be an overkill for the RPI. Attract Mode is a frontend that can play multiple videos at the same time, so memory management is crucial.

Thi is the reason I'm looking for alternatives. Attract Mode uses mmal currently, but I haven't found any way to bind the mmal output to sfml texture with zero copy.

**Comment by wang-bin** [comment]
When writing mmal decoder, I find playback is not smooth if input/output port buffer number and size is not good. Maybe omx is the same.

**Comment by oomek** [comment]
You mean the i/o buffer of the video_decode or egl_render module?

**Comment by wang-bin** [comment]
yes

Radek Dutkiewicz <notifications@github.com> 于2019年4月1日周一 下午6:07写道：

**Comment by oomek** [comment]
I've tried querrying this:
```
OMX_PARAM_BRCMDISABLEPROPRIETARYTUNNELSTYPE extraBuffers;
OMX_INIT_STRUCTURE(extraBuffers);
extraBuffers.nPortIndex = 130;
OMX_GetParameter(ILC_GET_HANDLE(video_decode), OMX_IndexParamBrcmExtraBuffers, &extraBuffers);
printf("OMX_IndexParamBrcmExtraBuffers: %u\n", extraBuffers.nSize);
```
But it's already 16. Even if I set this to 256 it has no effect on stuttering. I'm out of ideas.

**Comment by wang-bin** [comment]
what about  port buffers? not extra buffers.

new sdk is uploaded.

**Comment by oomek** [comment]
nBufferCountActual on the port 131 ( video_decoder output ) is 0
nBufferCountActual on the port 130 ( video_decoder input ) is 20

What value would you advise to set it to?

I've checked the new sdk for the Raspberry Pi , but the headers are still missing.

**Comment by wang-bin** [comment]
Default values may not work well without special code path.
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp#L519

headers are in include dir. which one did you download? latest is https://sourceforge.net/projects/mdk-sdk/files/mdk-sdk-rpi.tar.xz/download

**Comment by oomek** [comment]
I must have downloaded the wrong file. The headers are there, thanks.
I've tried the mdkplay with my test videos, and I observe severe stuttering with 30fps files. Strangely 60fps files up to 720p play smoothly

**Comment by wang-bin** [comment]
export MDK_LOG=1
    ./mdkplay -c:v MMAL videofile

then you will see log, can you paste the log here?

**Comment by oomek** [comment]
https://pastebin.com/6HwuwM2M

**Comment by oomek** [comment]
https://pastebin.com/GmkVmDw3

**Comment by oomek** [comment]
Btw, The log is showing regardless of the MDK_LOG value

**Comment by wang-bin** [comment]
Can you upload your video clip?

**Comment by oomek** [comment]
[test480p30.zip](https://github.com/wang-bin/mdk-sdk/files/3034281/test480p30.zip)
Play the first few seconds repeatedly as the stuttering is most visible in the beginning.

**Comment by oomek** [comment]
[squares.zip](https://github.com/wang-bin/mdk-sdk/files/3034351/squares.zip)
Here are some better examples.

**Comment by wang-bin** [comment]
Too slow to download from github. You can upload to https://0x0.st

**Comment by oomek** [comment]
https://0x0.st/zPxs.zip

**Comment by wang-bin** [comment]
Because the frame rate is to small. You can try other players on desktop, the same result.

**Comment by oomek** [comment]
Other players work fine, omxplayer also have no issues playing it without stuttering.

**Comment by wang-bin** [comment]
Works fine on my pi 3b+. What's your device?

**Comment by oomek** [comment]
Hold on, I might have sent you a corrupted file.
https://0x0.st/zPxB.zip
Those I've tested in mpc-hc, vlc and omxplayer and the playback of 480p30 is smooth

**Comment by oomek** [comment]
3b+

**Comment by oomek** [comment]
What is your firmware version ? `uname -a`

Linux retropie 4.19.30-v7+ #1209 SMP Tue Mar 26 13:14:20 GMT 2019 armv7l GNU/Linux

**Comment by wang-bin** [comment]
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by oomek** [comment]
Are you certain that the video with 30fps I sent you do not stutter? This is weird. Are the ffmpeg libs in your player statically linked or shared?

**Comment by wang-bin** [comment]
Stutters like omxplayer. The same result on my mac using mpv or ffplay.
FFmpeg is statically linked. I plan to add an option to choose ffmpeg shared libs at runtime.

**Comment by oomek** [comment]
Just to make sure, you have tested the second link i posted https://0x0.st/zPxB.zip ? The 30fps inside do not stutter for me on any player, except mdk.

**Comment by wang-bin** [comment]
I downloaded wrong file. I see the stutter
