### ISSUE TITLE
请问，如果要播放来自网络的媒体流数据，该使用哪步骤核心代码？ 大概流程是怎样？  看初始化都是使用本地的媒体文件。

### ISSUE THREAD

**Issue by jingyinglee** [wang-bin/mdk-sdk#100]

**Comment by wang-bin** [comment]
github action artifacts 有个mdk-abi-sdk的包解压到mdk-sdk目录，另外写个工程实现MediaIO，要注意的是一个工程里abi的头文件和公开头文件不能同时使用。最终还是通过定义一个url去读数据
