### ISSUE TITLE
demo中部分视频无法播放

### ISSUE THREAD

**Issue by FeJQ** [wang-bin/mdk-sdk#103]
使用的命令为mdkplay.exe D:\test.mp4
以下视频播放后有声音，但没画面

ffmpeg -i D:\test.mp4

ffmpeg version N-106379-g902ee9cafc-20220322 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220322
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 29.100 /  8. 29.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[libdav1d @ 000001e635fd46c0] libdav1d 887fa1d
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomav01iso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:27.04, start: 0.000000, bitrate: 1859 kb/s
  Stream #0:0[0x1](und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv), 852x480, 1725 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
At least one output file must be specified

**Comment by FeJQ** [comment]
glfwplay第一次播放正常，再次播放就没有画面了。没有看到有日志生成，不知在哪里看？ 这是该视频的下载地址https://wwsb.lanzoul.com/iFC7R14wipcd

**Comment by wang-bin** [comment]
glfwplay -logfile test.log

**Comment by wang-bin** [comment]
如果系统不支持av1硬解的话放个 libdav1d.dll 进去可以软解，或者商店上装个av1插件用MFT解码

**Comment by FeJQ** [comment]
截取了部分日志：
D 2023-08-12 16:38:40.429@23832: after avformat_open_input. pb: 000001E07CAF4940, iformat: 00007FFC74884520 context flags: 2097280, input format flags: 67141640
D 2023-08-12 16:38:40.430@23832: [FFmpeg:av1] Your platform doesn't support hardware accelerated AV1 decoding.
D 2023-08-12 16:38:40.430@23832: [FFmpeg:av1] Failed to get pixel format.
D 2023-08-12 16:38:40.430@23832: [FFmpeg:av1] Missing Sequence Header.

弄了一个libdav1d.dll进去就可以正常播放了
