### ISSUE TITLE
rk板卡得android 切换播放器一瞬间，会出现花屏

### ISSUE THREAD

**Issue by ken626014896** [wang-bin/mdk-sdk#105]
第一次打开软件，然后播放是不会出现的，只有在删除播放器，然后再新建播放器时大概率会出现，然后重复这个动作就会出现
感觉是缓存问题，上个视频最后一帧数据，出现在了新的播放器第一帧
解码设置  image设为0或1  surface设为0或1 都一样会出现花屏
下面是log
[log.txt](https://github.com/wang-bin/mdk-sdk/files/12318125/log.txt)
使用的是最新的sdk，其实以前的sdk一直都有，只是不影响正常使用就一直没管
https://github.com/wang-bin/mdk-sdk/assets/38373469/f2d9862c-0dd5-46f3-9706-065878c46203

**Comment by wang-bin** [comment]
不像上一个视频的数据，随机的。pc端有这种现象吗

**Comment by ken626014896** [comment]
pc端暂时没发现这个现象

**Comment by wang-bin** [comment]
试下最新包，修了一个framebuffer双缓冲未清理干净的问题
