### ISSUE TITLE
在使用自带的 mdk-examples-master\Qt\qtmultiwidgets例子时，设置了硬解码后无法正常播放？

### ISSUE THREAD

**Issue by liquanguo** [wang-bin/mdk-sdk#107]
在使用自带的 mdk-examples-master\Qt\qtmultiwidgets例子时，设置了硬解码后无法正常播放？
在qtmultiwidgets中，修改videogroup.cpp文件的构造函数代码后，九宫格播放只有一个窗口能正常播放，其他都显示第一帧。

使用的环境：
win10，SDK为最新的mdk-sdk

修改前：
    int i = qApp->arguments().indexOf("-c:v");
    if (i > 0)
        mpPlayer->setDecoders(qApp->arguments().at(i+1).split(","));
修改后：
mpPlayer->setDecoders({
                          #if (__APPLE__+0)
                                  "VT",
                          #elif (__ANDROID__+0)
                                  "AMediaCodec:java=0:copy=0:surface=1:async=0",
                          #elif (_WIN32+0)
                                  "MFT:d3d=11",
                                  "CUDA",
                                  "D3D11",
                                  "DXVA",
                          #elif (__linux__+0)
                                  "VAAPI",
                                  "VDPAU",
                                  "CUDA",
                          #endif
                                  "FFmpeg"});

请问：这是因为只能使用FFmpeg软解码才能播放九宫格吗，开启硬解后不支持吗？

**Comment by wang-bin** [comment]
原因还不清楚。同这个问题 https://github.com/wang-bin/mdk-sdk/issues/52

可行的方法是离屏渲染到一个纹理，再把纹理贴到多个widget。flutter这边我写了个例子结果是正确的 https://github.com/wang-bin/mdk-examples/blob/master/flutter/simple/lib/multi_textures.dart

**Comment by liquanguo** [comment]
> 原因还不清楚。同这个问题 #52
> 
> 可行的方法是离屏渲染到一个纹理，再把纹理贴到多个widget。flutter这边我写了个例子结果是正确的 https://github.com/wang-bin/mdk-examples/blob/master/flutter/simple/lib/multi_textures.dart

好的
