### ISSUE TITLE
请问，可以开发基于QOPenGL纹理多开的例子吗？

### ISSUE THREAD

**Issue by liquanguo** [wang-bin/mdk-sdk#109]
请问，可以开发基于QOPenGL纹理多开的例子吗？
九宫格开九个4K视频很吃力，如何可以开一个4K，其他用纹理贴就很完美了。

在QMultiWidget例子里面，无法使用硬解多开的，如果作者能搞个纹理多开的话，就不用同时多开九个4K了，而且还不同步。
谢谢。

**Comment by wang-bin** [comment]
我这周写一个

**Comment by liquanguo** [comment]
> 我这周写一个

好的，谢谢
