### ISSUE TITLE
MDK 0.22

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#110]
I have a problem on Linux, very often when clicking on a video file, it strip some seconds, or do not start playing with latest version of MDK.

Here is the logs with 0.21 and 0.22 
[mdk021.txt](https://github.com/wang-bin/mdk-sdk/files/12536865/mdk021.txt)
[mdk022.txt](https://github.com/wang-bin/mdk-sdk/files/12536866/mdk022.txt)

**Comment by wang-bin** [comment]
There is a change in decoder selection. Can you share your video so i can test?

**Comment by wang-bin** [comment]
this video works fine. the codec is h263 in your log, but this video is h264

**Comment by wang-bin** [comment]
i tried, can't reproduce the issuse with this video. i need a h263, then hw decoders will fail and switch to ffmpeg

**Comment by wang-bin** [comment]
or you can show me the log for this video

**Comment by pierrexn** [comment]
i have the problem with other video format like quicktime. 

Here is logs with another mp4, video doesn't play with 0.22
[mdk022.txt](https://github.com/wang-bin/mdk-sdk/files/12538737/mdk022.txt)
[mdk021.txt](https://github.com/wang-bin/mdk-sdk/files/12538738/mdk021.txt)

**Comment by pierrexn** [comment]
Thanks it works now
