### ISSUE TITLE
MDK 0.22 Windows

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#111]
I have an issue on Windows with 0.22 and not 0.21. 
When i stop playing of audio file and play another one,  i have a dead lock...

```
  player_->setMedia("2.mp3"); 

  player_->setActiveTracks(MediaType::Subtitle, {});
  player_->setProperty("continue_at_end", "1");
  player_->setBufferRange(0);
  player_->prepare();
  player_->seek(0, SeekFlag::FromStart);
  ...
  player_->set(State::Playing);
  ...
  player_->set(State::Paused);
  ...
  player_->set(State::Stopped);
  player_->waitFor(State::Stopped); // dead lock here
  
  player_->setMedia("3.mp3"); 
  player_->setActiveTracks(MediaType::Subtitle, {});
  player_->setProperty("continue_at_end", "1");
  player_->setBufferRange(0);
  player_->prepare(); // dead lock here
```

I use QMDKWidget

**Comment by pierrexn** [comment]
Are you able to reproduce?

**Comment by wang-bin** [comment]
I haven't tried QMDKWidget. I modified glfwplay, can't reproduce

**Comment by wang-bin** [comment]
```
player_->waitFor(State::Stopped); // dead lock here
  
  player_->setMedia("3.mp3"); 
```

How can you setMedia if there is a dead lock before this line?

**Comment by pierrexn** [comment]
Sorry if i remove `player_->waitFor(State::Stopped);` the dea lock occurs in `player_->prepare();`

**Comment by pierrexn** [comment]
Today, im not able to reproduce this issue in the same way. 

Here is the log when i open 2.mp3, play it, open 3.mp3, play it, open 2.mp3
[log.txt](https://github.com/wang-bin/mdk-sdk/files/12560084/log.txt)

**Comment by wang-bin** [comment]
try this https://github.com/wang-bin/mdk-sdk/actions/runs/6122469809

**Comment by pierrexn** [comment]
It seems that this bug is fixed
