### ISSUE TITLE
播放rtsp视频时，如果视频只有视频流没有音频流，视频无法播放

### ISSUE THREAD

**Issue by NO1-Affectionate** [wang-bin/mdk-sdk#115]
我的测试平台是x86架构下的麒麟系统，一个国产Linux系统，类似Ubuntu，IDE为Qt Creator 4.11.2。
我用EasyDarwin搭了一个本地的rtsp服务端，本地通过ffmpeg推流，最后用mdk拉流。经过测试，如果视频有视频流和音频流，mdk能够正常播放，但是如果去掉音频流只留下视频流，播放界面会黑屏，解析不出任何图像。由于我不清楚日志生成在哪里，所以没有贴上日志，不好意思

**Comment by NO1-Affectionate** [comment]
使用的mdk版本为最新的0.22.0

**Comment by wang-bin** [comment]
setLogHandler()把log输出。或者运行自带的`glfwplay -logfile test.log url`

**Comment by NO1-Affectionate** [comment]
不好意思没想到会这么快回复，这是两次的日志，1日志里的流数据只有视频流没有音频流，视频无法播放，2日志里我换了一个视频进行推流，视频也播放出来了。我所用的代码是你所给出的示例mdk-examples/Qt
/graphicsview，我只是将setMedia的url改成了rtsp流地址
[log-1.txt](https://github.com/wang-bin/mdk-sdk/files/12593956/log-1.txt)
[log-2.txt](https://github.com/wang-bin/mdk-sdk/files/12593958/log-2.txt)

**Comment by NO1-Affectionate** [comment]
> setLogHandler()把log输出。或者运行自带的`glfwplay -logfile test.log url`。降低rtsp延迟：https://github.com/wang-bin/mdk-sdk/wiki/Troubleshooting#mosaic-and-high-latency-in-rtsp

**Comment by wang-bin** [comment]
第一个流没打开进程挂了，你gdb调试下挂在哪一行

**Comment by NO1-Affectionate** [comment]
> 第一个流没打开进程挂了，你gdb调试下挂在哪一行

不好意思，怪我强行中止了调试，程序是不会挂的，只是不显示视频，我又重新截了一下无法播放的日志，它打印出了rtsp的流信息，我在日志126行的时候关闭了程序窗口。
[log-3.txt](https://github.com/wang-bin/mdk-sdk/files/12594259/log-3.txt)

**Comment by NO1-Affectionate** [comment]
> 视频参数没识别出来，你用ffplay, vlc试试看，ffplay应该也播不了

ffplay还真播不出来，但是vlc和mpv都能播，mpv可以秒开，vlc等4-5秒才能载入视频
[terminal-1.txt](https://github.com/wang-bin/mdk-sdk/files/12594603/terminal-1.txt)

**Comment by NO1-Affectionate** [comment]
> 视频参数没识别出来，你用ffplay, vlc试试看，ffplay应该也播不了

我刚刚多试了一下，如果对ffplay使用-rtsp_transport tcp参数，让它强制使用tcp连接，视频是可以播放出来的，请问在mdk里有办法强制使用tcp连接吗？

**Comment by wang-bin** [comment]
```player.setProperty("avformat.rtsp_transport", "tcp"); ```

**Comment by NO1-Affectionate** [comment]
> `player.setProperty("avformat.rtsp_transport", "tcp"); `

好像不行哦，这个语句必须要写在特定位置吗？我在创建对象，setMedia前后，play的前后都试过了，这个方法给的返回值都是false，视频也确实没能播放，在easyDarwin的服务端检测到的拉流类型还是udp

**Comment by wang-bin** [comment]
`SetGlobalOption("ffmpeg.log", "trace");`再贴下日志

**Comment by NO1-Affectionate** [comment]
> `SetGlobalOption("ffmpeg.log", "trace");`再贴下日志

[log-4.txt](https://github.com/wang-bin/mdk-sdk/files/12595033/log-4.txt)

**Comment by wang-bin** [comment]
好像代码有点bug，晚上再改

**Comment by wang-bin** [comment]
去掉SetGlobalOption("ffmpeg.log", "trace");，设个错误的值比如`player.setProperty("avformat.rtsp_transport", "xxx"); ` 然后log发我看下

**Comment by wang-bin** [comment]
你的log看上去没设置上去，所以要你设个错误的参数`player.setProperty("avformat.rtsp_transport", "xxx");`看看日志会没有报错。

我这边用测试没问题
```
./glfwplay  -avformat.rtsp_transport tcp -avformat.probesize 1000 -avformat.fpsprobesize 0 -ffmpeg.log trace=rtsp -logfile test.log rtsp://192.168.3.134:8080/h264_ulaw.sdp
```

另外你把sdk更新到最新版本，你用的版本有几个bug

**Comment by NO1-Affectionate** [comment]
我这里已经将参数由tcp改为了xxx，日志如下
[log-5.txt](https://github.com/wang-bin/mdk-sdk/files/12602824/log-5.txt)
我这里使用的sdk版本是release的0.22.0，还有更新的版本吗？我这里的./glfwplay无法执行，显示无法找到libglfw.so.3动态库文件，我搜索之后也确实找不到这个文件

**Comment by wang-bin** [comment]
安装libglfw3

**Comment by NO1-Affectionate** [comment]
你的demo程序是可以正常运行的，能够解析出视频，那这个setProperty失败可能是什么原因呢？有没有什么办法排查一下？

**Comment by wang-bin** [comment]
从日志看你美舍上去，你把代码贴下

**Comment by NO1-Affectionate** [comment]
好的，代码在这里，这是你mdk-examples/Qt/graphicsview工程的代码中的一部分，别的文件我未作修改
[main.cpp.txt](https://github.com/wang-bin/mdk-sdk/files/12602990/main.cpp.txt)

**Comment by NO1-Affectionate** [comment]
哦哦，确实可以了，不好意思。感谢大佬及时帮助
