### ISSUE TITLE
snapshot截图似乎无法进入回调

### ISSUE THREAD

**Issue by NO1-Affectionate** [wang-bin/mdk-sdk#116]
不好意思又打扰了，我在使用的时候给graphicsVideoItem.cpp添加了一个方法，调用了snapshot功能，代码如下
void GraphicsVideoItem::snapshot(const std::string filePath)
{
    Player::SnapshotRequest request{};
//    request.width = 1200;
//    request.height = 900;
    qDebug() << "Take a snapshot";
    player_->snapshot(&request, [](Player::SnapshotRequest *req, double frameTime) -> std::string{
        std::string filePath = "/home/kylin/Workspace/DetectionSoftware/pic/1122.jpg";
        qDebug() << "Get into SnapshotCallback";
        if(req){
            const QImage img = QImage(req->data, req->width, req->height,
                                      QImage::Format_RGBA8888);
            if(img.save(QString().fromStdString(filePath))){
                qDebug() << "Snapshot saved : " << QString().fromStdString(filePath);
            }
            else{
                qDebug() << "Fail to save : " << QString().fromStdString(filePath);
            }
        }
        return  filePath;
    });
}
奇怪的是我在调试的时候发现无法进入lambda函数的内部，qDebug() << "Get into SnapshotCallback";从未被执行过，如果大佬有空，希望能帮忙看一眼，万分感谢

**Comment by wang-bin** [comment]
snapshot最后还有个参数要和渲染相关的最后一个参数相同，这里是this
```
player_->snapshot(&request, ...., this);
```

**Comment by NO1-Affectionate** [comment]
好的，确实是这样，问题解决了，谢谢
