### ISSUE TITLE
Dead lock when creating thumbnail

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#121]
There is a dead lock when extracting frame for this file at 50%

https://github.com/wang-bin/mdk-sdk/assets/1200371/258aba94-4432-424d-be95-f2232c3fd3c5

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-examples/blob/master/Native/Thumbnail.cpp#L81

It's a seek error. Same error in other players if using the same seek flag. You can add a seek flag can fix the issue `p.seek(p.mediaInfo().duration * from_percent, SeekFlag::FromStart);`, but this results in accurate seek, which is not fast, i will add another flag later in api.

**Comment by wang-bin** [comment]
With the latest sdk, you can use `p.seek(p.mediaInfo().duration * from_percent, SeekFlag::FromStart|SeekFlag::KeyFrame|SeekFlag::Backward);`

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-examples/commit/b8d1317a3497ec1032280df5ca46bbe7972d1765

**Comment by pierrexn** [comment]
Thanks it works...
