### ISSUE TITLE
如何在QMDKWidget上绘制文字和检测框？

### ISSUE THREAD

**Issue by oscar1780** [wang-bin/mdk-sdk#123]
![Uploading 20231105204207.png…]()
  作者，您好，我使用QMDKWidget成功绘制了多个播放器窗口，并成功获取到了多个rtsp数据流。下一步，我想在QMDKWidget上绘制出一些文字和识别框，请问是否有相关的示例和教程?

**Comment by wang-bin** [comment]
用qpainter画文字和框框参考这个例子 https://github.com/wang-bin/mdk-examples/blob/master/Qt/qtpaintonvideo.cpp

如果要在视频帧的特定位置画，需要把相对于帧的坐标转换成widget的坐标，用这个借口 https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#void-mappointmapdirection-dir-float-x-float-y-float-z--nullptr-void-vo_opaque--nullptr

**Comment by oscar1780** [comment]
好的，感谢。
