### ISSUE TITLE
如何设置 rtsp_transport/buffer_size/stimeout/max_delay 等参数？有没有关键字key对照表

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#124]
如何设置 rtsp_transport/buffer_size/stimeout/max_delay 等参数？有没有关键字key对照表?方便查找，谢谢

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#void-setpropertyconst-stdstring-key-const-stdstring-value

format 相关: player.setProperty("avformat.key", "value")

protocol, io相关：player.setProperty("avio.key", "value")

**Comment by feiyangqingyun** [comment]
感谢，player->setProperty("avformat.rtsp_transport", "tcp");  确实可以。
