### ISSUE TITLE
什么时候引入avfilter滤镜模块，使得可以像qtav一样支持ffmpeg中的各种滤镜内容？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#125]
什么时候引入avfilter滤镜模块，使得可以像qtav一样支持ffmpeg中的各种滤镜内容？

**Comment by feiyangqingyun** [comment]
谢谢，试了下，player->setProperty("video.avfilter", "boxblur=2:2");  好像没效果。

**Comment by wang-bin** [comment]
你可以贴下日志。sdk里自带的ffmpeg裁剪过了，很多滤镜没有，你可以换个全一点的，比如https://sourceforge.net/projects/avbuild/files/windows-desktop/ 里 default结尾的包是默认的lgpl配置。另外，硬件解码（默认copy=0）的时候avfilter目前用不了

**Comment by feiyangqingyun** [comment]
非常感谢，我把ffmpeg-6.dll注释了，然后用ffmpeg原版的库文件，滤镜都可以用了。顺便提个小建议，可以在gitee开个镜像方便国人使用，github墙的不是一般的厉害。

**Comment by wang-bin** [comment]
github上编译好后自动上传到sourceforge，有固定的下载链接，没找到更合适的平台支持这么操作。gitee用来跟踪issue？

**Comment by feiyangqingyun** [comment]
我得意思是在gitee也同步下mdk-sdk这个项目，方便国内用户。我都是在阿里云服务器上安装的浏览器来访问github
