### ISSUE TITLE
setActiveTracks(MediaType::Audio) 函数失败，设置无效果，视频轨道有效果。

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#126]
setActiveTracks(MediaType::Audio) 函数失败，设置无效果，视频轨道有效果。

**Comment by feiyangqingyun** [comment]
测试文件在qtav中设置成功，说明文件没有问题

**Comment by wang-bin** [comment]
日志

**Comment by feiyangqingyun** [comment]
找到原因了，设置音频轨道的索引不能以AudioStreamInfo中的index为准，而必须和视频的index完全一样才行，比如获取到的ts文件有3个节目流，AudioStreamInfo中的index对应3/4/5，VideoStreamInfo中的index对应0/1/2，如果需要切换轨道，则必须音视频轨道一致，比如setActiveTracks(MediaType::Audio, 1);setActiveTracks(MediaType::Video, 1);，如果是setActiveTracks(MediaType::Audio, 4);setActiveTracks(MediaType::Video, 1);则失败。

**Comment by feiyangqingyun** [comment]
找到原因了，设置音频轨道的索引不能以AudioStreamInfo中的index为准，而必须和视频的index完全一样才行，比如获取到的ts文件有3个节目流，AudioStreamInfo中的index对应3/4/5，VideoStreamInfo中的index对应0/1/2，如果需要切换轨道，则必须音视频轨道一致，比如setActiveTracks(MediaType::Audio, 1);setActiveTracks(MediaType::Video, 1);，如果是setActiveTracks(MediaType::Audio, 4);setActiveTracks(MediaType::Video, 1);则失败。

**Comment by feiyangqingyun** [comment]
找到原因了，设置音频轨道的索引不能以AudioStreamInfo中的index为准，而必须和视频的index完全一样才行，比如获取到的ts文件有3个节目流，AudioStreamInfo中的index对应3/4/5，VideoStreamInfo中的index对应0/1/2，如果需要切换轨道，则必须音视频轨道一致，比如setActiveTracks(MediaType::Audio, 1);setActiveTracks(MediaType::Video, 1);，如果是setActiveTracks(MediaType::Audio, 4);setActiveTracks(MediaType::Video, 1);则失败。

**Comment by wang-bin** [comment]
是用MediaInfo.audio数组里的索引。你是音频视频轨道同时切换吗？如果是mpegts码流切节目，可以用`setActiveTracks(MediaType::Unknown, n)`，会选中第n个节目的音频视频，文档里忘记写了，changelog里有，不过目前可能有点音画同步问题
