### ISSUE TITLE
在onFrame回调中VideoFrame如何转换成QImage对应的格式保存图片？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#128]
player->onFrame<VideoFrame>([&](VideoFrame & frame, int t) {
        static int count = 0;
        count++;
        if (count % 25 == 0) {
            VideoFrame v = frame.to(PixelFormat::BGRX);
            qDebug() << TIMEMS << frame.width() << t << (int)frame.format() << (int)v.format();
            QImage image(v.bufferData(), v.width(), v.height(), QImage::Format_BGR888);
            image.save("f:/1.jpg");
        }
        return 0;
    });

保存的图片内容不对。

**Comment by wang-bin** [comment]
试试 PixelFormat::RGBA => QImage::Format_RGBA888

**Comment by feiyangqingyun** [comment]
试过了，颜色发蓝。整体对的上，就是颜色发蓝了

**Comment by wang-bin** [comment]
用 PixelFormat::BGRX 呢

**Comment by feiyangqingyun** [comment]
各种组合都试过了，BGRA和BGRX对应Format_RGBA888都是发蓝，其他组合保存下来都是图片都是没有，条纹状

**Comment by wang-bin** [comment]
看qt文档应该是 PixelFormat::RGBA => QImage::Format_RGBA888, PixelFormat::BGRA => QImage:: Format_ARGB32。你有没有测试代码让我跑跑看

**Comment by feiyangqingyun** [comment]
试了下PixelFormat::BGRA => QImage:: Format_ARGB32，绝大部分视频文件对了，但是部分视频文件比如分辨率464x264这种，保存的图片是斜纹状，好像要字节对齐啥的？

**Comment by wang-bin** [comment]
> 试了下PixelFormat::BGRA => QImage:: Format_ARGB32，绝大部分视频文件对了，但是部分视频文件比如分辨率464x264这种，保存的图片是斜纹状，好像要字节对齐啥的？

你方便的话视频发一下，或者切几秒钟

**Comment by feiyangqingyun** [comment]
Uploading 2023-11-17-17-34-33-728.mp4…

**Comment by feiyangqingyun** [comment]
[2023-11-17-17-34-33-728.zip](https://github.com/wang-bin/mdk-sdk/files/13390194/2023-11-17-17-34-33-728.zip)

**Comment by wang-bin** [comment]
下载不了

**Comment by feiyangqingyun** [comment]
[2023-11-17-17-34-33-728.zip](https://github.com/wang-bin/mdk-sdk/files/13398846/2023-11-17-17-34-33-728.zip)

**Comment by wang-bin** [comment]
用你的视频测了下RGBA=>Format_RGBA8888, BGRA=>Format_ARGB32都没问题。我是在[这个例子](https://github.com/wang-bin/mdk-examples/blob/e2e2cd8ea6930f9990c529a89b497ec5a928f1aa/Native/Thumbnail.cpp#L78)加了一行
```cpp
QImage(rgb.bufferData(), rgb.width(), rgb.height(), rgb.bytesPerLine(), QImage::Format_RGBA8888).save("/tmp/q.jpg");
```
测的，不知道你是不是哪里写的不对

**Comment by feiyangqingyun** [comment]
感谢巨佬，加上bytesPerLine参数传入进去确实完全正常了，原来是这个参数引起的，谢谢。
