### ISSUE TITLE
如何实现逐帧播放stepBackward/stepForward？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#130]
目前没有看到对应的接口，是否后续会提供此类接口？

**Comment by wang-bin** [comment]
`seek(SeekFlag::FromNow|SeekFlag::Frame, n);` n是帧数，正数相当于step forward，负数backward

**Comment by feiyangqingyun** [comment]
好的谢谢，那这个N如何获取？播放到中途暂停需要逐帧播放。再次感谢大佬

**Comment by wang-bin** [comment]
n你自己设，比如n=1每调一次就是单帧逐帧前进，n=2每次前进两帧。n太大可能会有问题

**Comment by feiyangqingyun** [comment]
可以了，谢谢巨佬
