### ISSUE TITLE
是否支持video=USB Video Device这种地址？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#131]
是否支持video=USB Video Device这种地址？库已经换成ffmpeg自带的库，试了下好像行不通。

**Comment by wang-bin** [comment]
`setMedia("avdevice://format:filename")`, 参考这个 https://github.com/wang-bin/mdk-sdk/issues/40#issuecomment-940985902

**Comment by feiyangqingyun** [comment]
确实可以，非常感谢，同理用 avdevice://gdigrab:desktop  可以采集桌面。

**Comment by wang-bin** [comment]
ffmpeg采集其实性能很差，我自己写过一些不过接口还没想好

**Comment by feiyangqingyun** [comment]
是的，桌面采集好像就是抓图成bmp再转换的。
