### ISSUE TITLE
库文件中的.dsym文件干嘛用的？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#133]
在linux和安卓库文件中的.dsym文件干嘛用的？发现删除了也能正常运行，没发现有何依赖。然道我用错了？

**Comment by wang-bin** [comment]
调试符号文件，类似于windows的pdb，我编译后弄成独立文件，发布应用不需要这些，查崩溃了用

**Comment by wang-bin** [comment]
调用 [mkdsym](https://github.com/wang-bin/cmake-tools/blob/0967e8a89d6650f5f5dce59b1ac372f2c85c2006/tools.cmake#L650)

**Comment by feiyangqingyun** [comment]
再次感谢巨佬
