### ISSUE TITLE
cant setProperty of avcodec

### ISSUE THREAD

**Issue by stingdau1206** [wang-bin/mdk-sdk#134]
Hi wang-bin, your mdk-sdk is wonderful,

but i have some problem. normally i use cmd to view rtsp by: "ffplay <rtsp_link> -**fflags** +nobuffer -**flags** low_delay -**analyzeduration** 0 -**max_delay** 0"

at this cmd, we have 4 options (properties): **fflags, flags, analyzeduration, max_delay**
so i only see 3 option in option_table of avformat **fflags, analyzeduration, max_delay** : https://github.com/wang-bin/FFmpeg/blob/wang/libavformat/options_table.h
`player.setProperty("avformat.fflags", "+nobuffer");
player.setProperty("avformat.analyzeduration", "0");
player.setProperty("avformat.max_delay", "0");`

and the remain option **flags**, i see it in option_table of avcodec: https://github.com/wang-bin/FFmpeg/blob/wang/libavcodec/options_table.h
but it seems can not setProperty of avcodec.

So now how can i should do ?

**Comment by wang-bin** [comment]
should be fixed in the latest build. these properties will be applied to all ffmpeg based audio/video/subtitle decoders, [setDecoders()](https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#void-setdecodersmediatype-type-const-stdvectorstdstring-names) can set properties on a single decoder

**Comment by wang-bin** [comment]
`setProperty("avcodec.flags", ...)`

**Comment by stingdau1206** [comment]
thanks for your reply. so now, i cant set **flags** property to low_delay right ?

**Comment by wang-bin** [comment]
you can, `setProperty("avcodec.flags", "low_delay")` or `setProperty("video.decoder", "flags=low_delay")`

**Comment by stingdau1206** [comment]
thks a lot, u are my hero
i want note: `setProperty("video.decoder", "flags=low_delay")` is working but `setProperty("avcodec.flags", "low_delay") ` not work

**Comment by wang-bin** [comment]
can you show me your log if call `setProperty("avcodec.flags", "low_delay")`? I tested other avcodec options and it works

**Comment by stingdau1206** [comment]
it dont show warning or error log when call `setProperty("avcodec.flags", "low_delay")`
just i compare with above cmd 
when use `setProperty("video.decoder", "flags=low_delay")` it working same as call by cmd
but about avcodec not same

**Comment by wang-bin** [comment]
if no error, the flag is applied. I tested libdav1d decoder in FFmpeg, which also supports low_delay option, "avcodec.flags" works for me.

**Comment by wang-bin** [comment]
I need your log to know what codec is used
