### ISSUE TITLE
record("rtmp://xxxxx")并没有推流

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#135]
record("rtmp://xxxxx")只能保存文件，如果是rtmp/rtsp地址并没有推流，是内部暂时没有实现吗？或者后续有这个计划吗？谢谢

**Comment by wang-bin** [comment]
可以考虑下

**Comment by wang-bin** [comment]
我测试了下rtmp、rtsp都能正常推流啊，只不过可能要指明格式（跟ffmpeg配置有关）
```cpp
    player.record("rtmp://127.0.0.1/live/0", "flv");
    player.record("rtsp://127.0.0.1/live/0", "rtsp");
```

**Comment by feiyangqingyun** [comment]
嗯，确实可以，还有个小缺憾就是，如果音频流不是aac，则rtmp推流失败，建议非aac就推视频流就好，毕竟视频流是264，是符合要求的。当然这只是一个人性化的策略，并不是bug。

**Comment by wang-bin** [comment]
rtmp 音频支持 aac adpcm_swf mp3 nellymoser pcm_alaw pcm_mulaw pcm_s16be pcm_s16le pcm_u8 speex，视频支持av1 flashsv flashsv2 flv1 h264 hevc vp6 vp6a vp6f vp9

**Comment by wang-bin** [comment]
我这边测试h264+mp3推rtmp没问题。你提供下日志我看看什么问题

**Comment by feiyangqingyun** [comment]
h264+pcm_mulaw推rtmp会失败。

**Comment by feiyangqingyun** [comment]
现象是推流成功，拉流失败。可能这受限于流媒体服务程序的支持程度？

**Comment by feiyangqingyun** [comment]
确实，换了流媒体服务程序及可以了，是我错怪了大佬，抱歉！

**Comment by wang-bin** [comment]
我用zlmediakit测的，mulaw没试过，不过这些标准的格式肯定支持
