### ISSUE TITLE
msvc2013/2015 error C2057 应输入常量表达式 qmetatype.h报错

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#138]
使用qt+msvc2013/2015 报错，error C2057 应输入常量表达式 qmetatype.h报错，有最低编译器要求？对应qt+mingw都正常。

**Comment by feiyangqingyun** [comment]
用的测试示例是qmdkplay.pro，用msvc2017/2019/2022完全正常，莫非最低要求msvc2017？

**Comment by wang-bin** [comment]
错误信息贴一下，至少要知道哪个文件哪一行。我怀疑是constexpr float 那几行，改成static inline就行

**Comment by feiyangqingyun** [comment]
将constexpr改成static inline 编译报错，改成const/static/static const 三种方式，global.h编译不报错，但是依然最终无法通过编译，还是提示C2057:应输入常量表达式

**Comment by feiyangqingyun** [comment]
![1](https://github.com/wang-bin/mdk-sdk/assets/3894710/1cd55d5b-53a5-4325-9d46-2bb47ba424fd)

**Comment by feiyangqingyun** [comment]
无论是qtcreator还是vs，只要是msvc2013/2015都是这个现象。

**Comment by feiyangqingyun** [comment]
王总，你这sdk做的蛮好，尤其是接口设计非常棒非常强大万能。我打算在我的开源主页给你引流，国内站点：https://gitee.com/feiyangqingyun  国际站点：https://github.com/feiyangqingyun

**Comment by wang-bin** [comment]
怎么看上去是qt里的报错啊。其他qt程序没这个报错？

**Comment by wang-bin** [comment]
> 王总，你这sdk做的蛮好，尤其是接口设计非常棒非常强大万能。我打算在我的开源主页给你引流，国内站点：https://gitee.com/feiyangqingyun 国际站点：https://github.com/feiyangqingyun

谢谢

**Comment by feiyangqingyun** [comment]
是的，其他的无论什么qt版本什么组合都是正常的，会不会是mdk的头文件有定义冲突？但是msvc2017及也是正常

**Comment by wang-bin** [comment]
如果冲突的话include mdk的头文件放最后试试

**Comment by feiyangqingyun** [comment]
试过了也不行

**Comment by wang-bin** [comment]
我这边也没编译器测试。要么你只include 头文件不写mdk代码，然后头文件里#if 0 #endif进行二分法注释查找哪行影响的

**Comment by wang-bin** [comment]
constexpr float那几行要改吗？要改的话我这边也改下

**Comment by feiyangqingyun** [comment]
也要的，constexpr改成const，不然无法编译。
