### ISSUE TITLE
mdk支持linux系统采集本地设备吗？比如本地摄像头或者桌面

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#139]
在win正常，都能正常采集本地摄像头和桌面，但是到了linux，同样的环境用ffplay可以正常采集，用mdk  setMedia("avdevice://v4l2:/dev/video0")  setMedia("avdevice://x11grab::0.0+0,0")  都不行，不知道是不是暂时没有实现。

**Comment by wang-bin** [comment]
没试过，有没有日志

**Comment by feiyangqingyun** [comment]
试过了可以，要用ffmpeg的库，不能用自带的libffmpeg.so.6，但是在win上不用ffmpeg的库也是有的，估计提供的win的ffmpeg-6.dll是已经内置了avdevice库

**Comment by wang-bin** [comment]
估计是我编译环境相关的头文件没装

**Comment by wang-bin** [comment]
看qt文档，mkspecs目录，qmake源码，https://wiki.qt.io/Undocumented_QMake

**Comment by feiyangqingyun** [comment]
跪谢大佬。祝大佬头发浓密，财务自由。
