### ISSUE TITLE
can't catch any event when target device drop network connection ?

### ISSUE THREAD

**Issue by stingdau1206** [wang-bin/mdk-sdk#140]
I run this example [](https://github.com/wang-bin/mdk-examples/tree/master/Qt/qml)
i have added 3 callback

```
    internal_player->onStateChanged([=](State newState) {
        qDebug() << "newState";
        qDebug() << int8_t(newState);
    });

    internal_player->onMediaStatusChanged([=](MediaStatus newMediaState){
        qDebug() << "newMediaState";
        qDebug() << newMediaState;
        return true;
    });

    internal_player->onEvent([=](MediaEvent newEvent){
        qDebug() << "newMediaEvent";
        qDebug() << newEvent.error;
        return true;
    });
```
**and stream target device over its rtsp link** 

case 1: begin with target device has network
after run application, it run normally
when i call `play()`, 3 callback is called with each its change
next, i unplug the ethernet cable from target device (now it not has network)
the stream on app's window is stop, but nothing happen (no callback is called)

case 2: begin with target device has not network
after run application, it run normally
when i call `play()`, 3 callback is called each its change
next, i plug the ethernet cable to target device (now it has network)
but after that, nothing happen, no callback is called and the stream not run

**Comment by wang-bin** [comment]
I need your log

**Comment by stingdau1206** [comment]
Hi @wang-bin , this is log in each case
Case1: Log when all is good, stream ok
```
newMediaState
2
newMediaState
4
newMediaState
20
newMediaEvent
0
newState
1
newMediaEvent
1
newMediaEvent
0
newMediaState
292
newMediaEvent
100
newMediaEvent
1200
```
after that, i unplug ethernet cable from target device-> stream display is pause, but nothing more log, the log still same above. so i cant catch event when target device drop network ?

case 2: begin with target device not has network
```
newMediaState
2
newMediaState
-2147483648
```
after that, i plug ethernet cable to target device -> target device has network but notthing happen, stream not play and nothing more log, log still same above
```
newMediaState
2
newMediaState
-2147483648
```
so i cant catch event when target device is reconnected network

**Comment by wang-bin** [comment]
i need the full log using log handler

**Comment by stingdau1206** [comment]
@wang-bin  Sorry
i just run this example [](https://github.com/wang-bin/mdk-examples/blob/master/Qt/qmdkqmlplay.pro)
then i only add some code i tell above.
so that log is every thing i have, so if u need anything, u can tell me how to set up it

i only have log when run by cmd ffplay
![image](https://github.com/wang-bin/mdk-sdk/assets/67157339/f09c04c3-66a9-441d-9089-041bcd4a401c)

**Comment by wang-bin** [comment]
```cpp
setLogHandler([&log_file](LogLevel level, const char* msg){
        // write msg to a file. print system time will be better
    });
```

from ffplay log I see the stream is still connected when you disable network, application can not detect the network changes. There is no api from ffmpeg can detect such changes, in mdk MediaStatus should become Buffering, and if state will be Stopped if timeout.
