### ISSUE TITLE
如何识别视频流分辨率发生变化？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#142]
如何识别视频流分辨率发生变化？onStateChanged/onMediaStatus/onEvent均没有任何触发。

**Comment by wang-bin** [comment]
目前没有，只能通过onFrame对比之前的大小。你是什么视频流？

**Comment by feiyangqingyun** [comment]
就是普通的摄像头rtsp视频流，场景就是用户在运行过程中在后台修改了摄像头的分辨率，可以动态调整的。之前qtav有个videoFrameSizeChanged信号可以正常用。

**Comment by feiyangqingyun** [comment]
mdk的底层代码肯定能过识别到分辨率变化了，建议能过提供一个event信号，放在onEvent中。

**Comment by wang-bin** [comment]
可以

**Comment by wang-bin** [comment]
category: "decoder.video", detail: "size", video.{width, height}

**Comment by feiyangqingyun** [comment]
![2D01DF84D2571DFD931C67883F3400BE](https://github.com/wang-bin/mdk-sdk/assets/3894710/a4b56688-5762-4c40-9a0c-299b42a4bd33)
非常完美，给王总加鸡腿。

**Comment by feiyangqingyun** [comment]
好像还差一点，这个变化后的尺寸等信息，没有更新到 VideoCodecParameters 中，导致读取到的还是旧的。不知道是不是我哪里还用的不对。

**Comment by wang-bin** [comment]
这个没改

**Comment by wang-bin** [comment]
试下最新的包

**Comment by feiyangqingyun** [comment]
ok，马上安排。谢谢

**Comment by feiyangqingyun** [comment]
可以，完美
![QQ截图20231125202910](https://github.com/wang-bin/mdk-sdk/assets/3894710/c40f63b3-54fb-4398-b583-b670bbfa37e1)
