### ISSUE TITLE
有没有清空缓存数据的接口？setBufferRange？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#144]
有没有清空缓存数据的接口？比如采集视频流过程中触发了暂停，过了30s又继续播放，希望继续播放的是最新的实时的，而不是缓存中的，如果有清空缓存接口则交给用户主动清空缓存再继续播放 set(mdk::State::Playing)。

**Comment by wang-bin** [comment]
setBufferRange最后一个参数可以保证始终播放最新的数据丢弃老数据

**Comment by feiyangqingyun** [comment]
player->setBufferRange(0, 10)  各种参数试了下，没有效果，还是有缓存，或者怪怪的问题。

**Comment by wang-bin** [comment]
maxMs=10ms太小了，比一帧的时长还短，相当于不缓存了。maxMs对延迟没影响，设大点比较好。缓存里有至少有两个关键帧才会把老的丢弃，不然随意丢会解码出错。如果关键帧间隔很大然后maxMs设的很小就会没效果。

**Comment by wang-bin** [comment]
你直接 `setBufferRange(0, INT64_MAX, true)`就行，缓冲区始终只有最新的一个关键帧间隔内的数据

**Comment by feiyangqingyun** [comment]
那如果想要暂停后继续播放，立马清空缓存，应该怎么处理？调用哪个函数？

**Comment by wang-bin** [comment]
试下最新包，`setBufferRange(0, INT64_MAX, true)`始终只保留一个关键帧间隔的数据

**Comment by feiyangqingyun** [comment]
不行，继续播放后画面变得一卡卡。

**Comment by wang-bin** [comment]
maxMs = INT64_MAX 是会有问题，要改满多地方，后面再修。最新的包maxMs设成其他值应该没问题了，之前音频丢的不对
