### ISSUE TITLE
硬解码不支持渲染到多个窗体？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#145]
qtmultiwidgets.pro项目，默认ffmpeg软解码可以一个解码渲染到多个窗体，如果是硬解码，只有最后一个窗体有动态的画面，其他窗口都是只显示第一帧。

**Comment by wang-bin** [comment]
这原因还不清楚。一个方法是先渲染到一个纹理再把纹理显示到多个widget

**Comment by feiyangqingyun** [comment]
试了下qtav，addVideoRenderer到多个VideoOutput，支持硬解码同时渲染多个的。

**Comment by wang-bin** [comment]
qtav的日志贴出来看看

**Comment by feiyangqingyun** [comment]
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    QMDKWidgetRenderer w1;
    QMDKWidgetRenderer w2;
    w1.show();
    w2.show();

    QMDKPlayer p;
    //软解模式下两个画面都正常绘制
    p.setDecoders(QStringList() << "FFmpeg");
    //硬解模式下无论渲染到多少个画面/只会有一个画面在绘制/无论何种硬解比如DXVA或者D3D11等
    p.setDecoders(QStringList() << "DXVA");
    p.setMedia("http://vfx.mtime.cn/Video/2021/11/16/mp4/211116131456748178.mp4");
    p.addRenderer(&w1);
    p.addRenderer(&w2);
    p.play();

    return a.exec();
}

**Comment by wang-bin** [comment]
windows上可以复现，mac上正常，很奇怪

**Comment by feiyangqingyun** [comment]
是挺奇怪的，大佬加油，又是元气满满的一天

**Comment by feiyangqingyun** [comment]
![QQ截图20231205113918](https://github.com/wang-bin/mdk-sdk/assets/3894710/c6a56ff4-61a1-49b5-b02c-2bb8aafa4d7c)
各种硬解都测试了，非常完美，谢谢

**Comment by wang-bin** [comment]
顺便做了一点性能优化。用非opengl的rhi、qt6quick多线程渲染估计还有问题，后面会优化

**Comment by feiyangqingyun** [comment]
目前发现安卓上硬解多屏渲染也是和之前win上一样的现象。用的就是最新的mdk

**Comment by wang-bin** [comment]
最新包修复了android硬解多窗口渲染部分问题，解码器要用AMediaCodec

**Comment by feiyangqingyun** [comment]
好的，谢谢，马上安排

**Comment by feiyangqingyun** [comment]
试过了，在荣耀手机鸿蒙系统，还是硬解不行，卡顿以及失灵，而且多屏渲染闪烁几下，也没了。

**Comment by wang-bin** [comment]
我这边有时候也会卡，今天的包又调整了下卡顿减少了，但是偶尔也会发生，原因没想明白。你试下这个apk，同时渲染surfaceview+glsurfaceview，我手机上正常的。qt的任何程序我电脑上会报一堆gradle错误没法测
[app-debug.apk.zip](https://github.com/wang-bin/mdk-sdk/files/13695407/app-debug.apk.zip)

**Comment by feiyangqingyun** [comment]
嗯，你这个可以，在鸿蒙也是正常，看来是和qt安卓的qopenglwidget的兼容性哪里有问题，不知道是否哪里设置下？QApplication::setAttribute(Qt::AA_UseOpenGLES);？
[video_demo.zip](https://github.com/wang-bin/mdk-sdk/files/13695606/video_demo.zip)
你试试我的这个

**Comment by wang-bin** [comment]
我渲染器多缓存了一帧。你再试试最新包。

**Comment by feiyangqingyun** [comment]
我加了QApplication::setAttribute(Qt::AA_UseOpenGLES);效果又要好一些，起码多屏硬解渲染有时候正常了

**Comment by wang-bin** [comment]
> 我加了QApplication::setAttribute(Qt::AA_UseOpenGLES);效果又要好一些，起码多屏硬解渲染有时候正常了

不用加，本来就是opengles

**Comment by wang-bin** [comment]
我用最新的libmdk.so替换你apk里的重新打包apk，硬解渲染很正常

**Comment by feiyangqingyun** [comment]
可能真的和硬件有关。我是荣耀9x，麒麟芯片，可能有点区别。刚试了你的最新的，现在硬解下，一张画面都没了

**Comment by wang-bin** [comment]
试下最新包，android的几个参数我感觉没理解透，又调了下，测了几个手机还有开发板基本正常了

**Comment by feiyangqingyun** [comment]
好的，谢谢大佬，2号来，祝大佬元旦快乐

**Comment by feiyangqingyun** [comment]
彻底重新编译过，在鸿蒙手机不行，硬解码没画面，以前的版本还能出来几秒钟画面

**Comment by wang-bin** [comment]
需要日志
