### ISSUE TITLE
player->onFrame如果里面啥也不干，会增加CPU负担吗？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#147]
player->onFrame<mdk::VideoFrame>([&](mdk::VideoFrame & frame, int t) {return 0;});  会不会影响性能？不用的时候能不能关闭这个？

**Comment by wang-bin** [comment]
不会，就多个调虚函数的成本，忽略不计

**Comment by feiyangqingyun** [comment]
ok
