### ISSUE TITLE
对有旋转角度的视频文件存储后的录像文件没有带对应的旋转角度

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#150]
对有旋转角度的视频文件存储后的录像文件没有带对应的旋转角度。建议考虑加上这个处理。
void FFmpegHelper::setRotate(AVStream *stream, int rotate)
{
#if (FFMPEG_VERSION_MAJOR < 5)
    av_dict_set(&stream->metadata, "rotate", QString::number(rotate).toUtf8().constData(), 0);
#else
    quint8 *sidedata = av_stream_new_side_data(stream, AV_PKT_DATA_DISPLAYMATRIX, sizeof(qint32) * 9);
    if (sidedata) {
        av_display_rotation_set((qint32 *)sidedata, rotate);
    }
#endif
}

**Comment by wang-bin** [comment]
试下最新包

**Comment by feiyangqingyun** [comment]
试过了，完美。感谢
