### ISSUE TITLE
mdk是否提供按照渲染画布等比例绘制？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#152]
在qtav中提供了RendererAspectRatio/VideoAspectRatio两种方式，非常好用，但是在mdk中只提供了KeepAspectRatio，永远都是VideoAspectRatio效果。

**Comment by wang-bin** [comment]
https://github.com/wang-bin/libmdk-capi/blob/main/include/mdk/cpp/global.h#L33-L37 预定义的有这几种，IgnoreAspectRatio是你要的，其他的float值就是用你给的的比例

**Comment by feiyangqingyun** [comment]
IgnoreAspectRatio是拉伸铺满，希望是按照画布等比例，RendererAspectRatio

**Comment by feiyangqingyun** [comment]
RendererAspectRatio对应应该填值多少？或者有没有换算机制公式之类的

**Comment by wang-bin** [comment]
> RendererAspectRatio对应应该填值多少？或者有没有换算机制公式之类的

IgnoreAspectRatio

**Comment by wang-bin** [comment]
按照画布等比例不就是拉伸到画布大小吗？你是要什么效果

**Comment by feiyangqingyun** [comment]
下面是正常画面
![正常画面](https://github.com/wang-bin/mdk-sdk/assets/3894710/d77f4f37-339f-455c-a383-d30827a996c9)
下面是mdk用crop滤镜后的画面
![正常画面](https://github.com/wang-bin/mdk-sdk/assets/3894710/02342426-2d08-44c0-b8eb-14494d237b3d)
下面是qtav用crop滤镜后的画面，可以看到自己按照画面等比例缩放了。非常完美，就是要这种效果。
![裁切画面2](https://github.com/wang-bin/mdk-sdk/assets/3894710/0a2a9032-1b31-4e91-a54e-a64906f7a3e2)

**Comment by feiyangqingyun** [comment]
下面是正常画面
![正常画面](https://github.com/wang-bin/mdk-sdk/assets/3894710/d77f4f37-339f-455c-a383-d30827a996c9)
下面是mdk用crop滤镜后的画面
![裁切画面1](https://github.com/wang-bin/mdk-sdk/assets/3894710/dcce87ff-2984-43f7-8674-79a57d32b80b)
下面是qtav用crop滤镜后的画面，可以看到自己按照画面等比例缩放了。非常完美，就是要这种效果。
![裁切画面2](https://github.com/wang-bin/mdk-sdk/assets/3894710/0a2a9032-1b31-4e91-a54e-a64906f7a3e2)

**Comment by wang-bin** [comment]
widget边框是哪部分能否标一下？qtav用的什么参数？我没看到这种效果的参数

**Comment by feiyangqingyun** [comment]
你可以试试裁切滤镜 crop=100:100:50:60  ，对比下qtav，就会看到效果

**Comment by feiyangqingyun** [comment]
crop=100\:100:50:60   对应w:h:x:y

**Comment by feiyangqingyun** [comment]
crop=100\:\10050:60 对应w:h❌y

**Comment by wang-bin** [comment]
是只有用crop之后才会有问题？那你得改下问题描述

**Comment by feiyangqingyun** [comment]
找到原因了，qtav在执行 crop=100:100:50:60  滤镜后会发送 videoFrameSizeChanged 信号，而mdk没有，就像之前的，运行过程中分辨率变化了，要触发一个event。其实执行裁剪crop滤镜也会触发分辨率变化，而event那边暂时没有反应。可以考虑加进去。

**Comment by feiyangqingyun** [comment]
忽略标题，是我搞错了现象，核心就是触发裁剪滤镜crop后，画布尺寸变化了，mdk没有提供videoFrameSizeChanged 信号，建议考虑加进去。

**Comment by feiyangqingyun** [comment]
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    QMDKWidget w;
    w.resize(400, 300);
    w.show();
    w.setMedia("http://vfx.mtime.cn/Video/2021/11/16/mp4/211116131456748178.mp4");
    w.play();

    //1s后会执行一次crop裁剪滤镜/会触发分辨率变化
    QTimer t;
    t.setInterval(1000);
    t.setSingleShot(true);
    t.callOnTimeout([&] {
        w.setProperty("video.avfilter", "crop=100:100:150:160");
    });
    t.start();

    return a.exec();
}

**Comment by wang-bin** [comment]
试下最新的包，加了个新的事件，MediaInfo不会变
```cpp
    MediaEvent e{
        .error = track,
        .category = "video", .detail = "size",
        .video = {.width = width, .height = height}
    }
```

**Comment by feiyangqingyun** [comment]
测试过了，可以了，感谢大佬。
