### ISSUE TITLE
record录像期间如果暂停后一段时间再继续播放，录像文件不正常。

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#153]
record录制中，如果暂停播放，过段时间再继续播放，录制的文件播放有问题，暂停期间那一段画面一直不动，但是进度条在走，应该是要连贯的才对。会不会是需要重新计算时间基准？

**Comment by feiyangqingyun** [comment]
录像期间，切换播放进度，也会导致存储的文件不对，播放录像的文件，中间跳过的播放一直卡住不动。录像文件应该是这段直接跳过去就好。

**Comment by wang-bin** [comment]
暂停不会受影响，我用glfwplay测了也无法复现，你可以提供一个glfwplay的复现方法，或提供你的测试代码。始终向前切换播放位置也不会有问题，会有时间戳和进度条跳变，但是播放应该都流畅的，否则就是播放器问题，试了mpv和mdk都正常播放，vlc会卡。位置来回切换会有问题，不过这个也没必要支持吧，我这个录制最初是用于录制直播流用的

**Comment by feiyangqingyun** [comment]
试过了，用mdk/ffplay/potplayer播放正常，用vlc/mpc-hc/qtav/其他mp4播放器播放，都不正常。说明里面打包的时间戳可能不对。而按照ffplay的解码播放可能专门做了这种容错。

**Comment by feiyangqingyun** [comment]
按照帧数量将pts/dts重新计算不知道会不会好一点。比如切换过几次进度，总共播放了10s，保存时长也是10s。而不是现在按照最后录像结束的时长作为时长。比如文件总共时长60s，播放到第10s，切换进度到30s（相当于跳过了20s），再播放10s，录像结束。用mdk保存的文件时长是40s，而实际时长应该是20s。
void FFmpegHelper::rescalePacket(AVPacket *packet, AVRational timeBaseIn, qint64 &count, qreal fps)
{
    count++;
    qreal duration = AV_TIME_BASE / fps;
    packet->pts = (count * duration) / (av_q2d(timeBaseIn) * AV_TIME_BASE);
    packet->dts = packet->pts;
    packet->duration = duration / (av_q2d(timeBaseIn) * AV_TIME_BASE);
}

void FFmpegHelper::rescalePacket(AVPacket *packet, AVRational timeBaseIn, AVRational timeBaseOut)
{
    //1. av_rescale_q里面调用的av_rescale_q_rnd
    //2. av_rescale_q_rnd里面调用的av_rescale_rnd
    //3. av_packet_rescale_ts对pts/dts/duration三者调用av_rescale_q
#if 1
    packet->pts = av_rescale_q_rnd(packet->pts, timeBaseIn, timeBaseOut, AVRounding(AV_ROUND_NEAR_INF | AV_ROUND_PASS_MINMAX));
    packet->dts = av_rescale_q_rnd(packet->dts, timeBaseIn, timeBaseOut, AVRounding(AV_ROUND_NEAR_INF | AV_ROUND_PASS_MINMAX));
    packet->duration = av_rescale_q(packet->duration, timeBaseIn, timeBaseOut);
#else
    av_packet_rescale_ts(packet, timeBaseIn, timeBaseOut);
#endif
    packet->pos = -1;
}

**Comment by wang-bin** [comment]
这跟ffmpeg没关系，是播放器的问题，mdk mpv 都不是基于ffplay的。直播流也会有时间戳跳变的情况而且无法避免，这种情况vlc这些播放器都完蛋。时间戳要连续的话ffmpeg命令行应该有什么参数可以转一些。当然我这边也可以考了加个参数出力下

**Comment by wang-bin** [comment]
暂停的问题你能不能给个复现的方法？不然得改下issue标题

**Comment by wang-bin** [comment]
推流测试发现时间必须递增的，最新包默认改成连续时间戳了，时长不会偏大，进度条来回切换也没问题
