### ISSUE TITLE
后期有计划加入去掉音视频同步的机制吗？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#157]
比如视频监控行业的摄像头，对实时性要求极高，现象手晃动，这边画面也希望对应动作的延迟控制在0.3s内，这就要求用ffmpeg采集后直接立马解码并显示，不需要去做音视频同步，速度是最快的。一般rtsp都是25-30帧每秒，都是连贯的，不需要同步，对应的音视频也是连续的。

**Comment by feiyangqingyun** [comment]
谢谢大佬，试过了，效果不大，不知道是不是我哪里用的不对，之前大概是延迟2s，加了这个以后延迟1s，实际上可以做到0.2s。就是收到以后就直接解码并绘制。

**Comment by feiyangqingyun** [comment]
可否直接做成设置属性的方式，比如setProperty("sync", "false");

**Comment by wang-bin** [comment]
收帧是会尽快显示的，不管有没有设onsync，你看下要多久？还有ffmpeg的几个降低延迟的参赛设了没？

**Comment by feiyangqingyun** [comment]
player->setProperty("avformat.fflags", "+nobuffer");
player->setProperty("avformat.analyzeduration", "5000000");
player->setProperty("avformat.probesize", "50000");
player->setProperty("avformat.fpsprobesize", "0");
都设置了
