### ISSUE TITLE
由于找不到mdk.dll，无法继续执行代码

### ISSUE THREAD

**Issue by LiWatermelon** [wang-bin/mdk-sdk#158]
mdk文件：mdk-sdk-windows-desktop-vs2019.7z
基础环境：msvc2019 QT6.5.0
![image](https://github.com/wang-bin/mdk-sdk/assets/133831635/955241c9-01ec-477e-ac39-8712d48607b0)
![image](https://github.com/wang-bin/mdk-sdk/assets/133831635/ee724020-9c4a-4d57-9067-f3689d33e699)
![image](https://github.com/wang-bin/mdk-sdk/assets/133831635/4bf30823-47d6-4d22-99c3-b6dc7bfcc3bc)
![image](https://github.com/wang-bin/mdk-sdk/assets/133831635/54188d71-6b0d-4197-b38f-64b5339432f6)
![image](https://github.com/wang-bin/mdk-sdk/assets/133831635/9e17e9ee-5374-466e-bc82-996ba94492d7)

**Comment by wang-bin** [comment]
请使用最新的用vs2022编译的sdk https://sourceforge.net/projects/mdk-sdk/files/nightly/mdk-sdk-windows-desktop-vs2022.7z/download


sdk是支持多种编译器的，从vs2013到最新，还包括mingw gcc。你用的版本很老了。

缺少mdk.dll需要在qtcreator里手动把`mdk-sdk/bin/x64`目录添加到PATH环境变量里

<img width="1434" alt="image" src="https://github.com/wang-bin/mdk-sdk/assets/785206/11c68f53-aa46-4ad2-aa84-6dfb8c9d9aef">

**Comment by feiyangqingyun** [comment]
建议先试试播放个本地文件，一步步来。mdk.dll  mdk-braw.dll  mdk-r3d.dll  libass.dll    ffmpeg-6.dll  这几个文件都要的

**Comment by wang-bin** [comment]
> 建议先试试播放个本地文件，一步步来。mdk.dll mdk-braw.dll mdk-r3d.dll libass.dll ffmpeg-6.dll 这几个文件都要的

[mdk-braw.dll](https://github.com/wang-bin/mdk-braw) [mdk-r3d.dll](https://github.com/wang-bin/mdk-r3d) 通常不需要，这是用于解码blackmagic、red这类专业相机的raw视频的，还要配合他们提供的dll使用 , 这两个目前主要是一些国外用户在用。这个我到时候readme里备注下

ffmpeg-6.dll或者一组ffmpeg的标准dll(avcodec-60.dll, avutil-58.dll等)目前是必须的，ffmpeg版本可以是4到最新。 libass.dll是字幕用的，不需要字幕功能的话可以不带

**Comment by feiyangqingyun** [comment]
是吧，歇息答疑，弱弱的咨询大佬一个技术问题，就是硬解后的数据你是支持绘制显卡的方式去绘制的吗？有没有用到 av_hwframe_transfer_data或者av_hwframe_map？谢谢。

**Comment by wang-bin** [comment]
> 是吧，歇息答疑，弱弱的咨询大佬一个技术问题，就是硬解后的数据你是支持绘制显卡的方式去绘制的吗？有没有用到 av_hwframe_transfer_data或者av_hwframe_map？谢谢。

尽量用最优的方式绘制，这个比较复杂。没用ffmpeg的方法，ffmpeg不提供相关功能
