### ISSUE TITLE
在安卓上mdk::SetGlobalOption("JavaVM", QJniEnvironment::javaVM())是否是必须的？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#160]
用的qt安卓，试过了，有没有这句都没有任何影响。目前为止是没有发现。

**Comment by wang-bin** [comment]
api level 26或更新的可以不加，硬件解码和渲染部分默认完全用ndk实现

**Comment by feiyangqingyun** [comment]
有个现象不知道是不是我步骤不对，关于安卓上mdk的现象，之前大概是11月份的版本的安卓库，硬解正常，现在用12月份的，硬解不正常，大概前面几秒钟正常，后面就停了，不知道什么原因，各种彻底重新编译，环境彻底清空再编译等，现象还是一样。
用软解码都正常。不知道近期你是不是改了哪里？或者是我眼花了之前看错了？

**Comment by wang-bin** [comment]
日志

**Comment by feiyangqingyun** [comment]
你可以用你编译的apk试试硬解如何，感觉就是近期更改代码后导致的。11月初的是可以的。

**Comment by wang-bin** [comment]
我最近测过正常，而且没改android相关代码

**Comment by feiyangqingyun** [comment]
也有可能是我环境的问题，我之前用的qt6.5 现在换的6.6，我在换回去试试。

**Comment by feiyangqingyun** [comment]
顺便问下大佬，安卓上硬解，你推荐用哪个参数？AMediaCodec  、AMediaCodec:java=0:async=1     AMediaCodec:java=0:copy=0:surface=1:async=0:image=0   后面这些具体啥含义？有没有文档说明，谢谢

**Comment by feiyangqingyun** [comment]
找到了硬解为何不行的原因了，手机的问题，换了红米的小米的就可以，荣耀的鸿蒙就只能软解。硬解经常失效。原因未知。

**Comment by wang-bin** [comment]
你可以贴下日志我来分析下。对比下vlc、mpv-android、系统播放器看看

**Comment by wang-bin** [comment]
鸿蒙的日志咋样的？让我涨涨见识

**Comment by feiyangqingyun** [comment]
心好累，我先忙点其他的
