### ISSUE TITLE
linux arm64 执行./aplay 报错提示找不到 libpulse.so

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#161]
在arm64位的嵌入式板子上运行提供的可执行文件，报错提示缺少libpulse.so、libglfw.so等文件。
![微信图片_20231212185213](https://github.com/wang-bin/mdk-sdk/assets/3894710/b93230a9-3d7d-4d8d-94b8-2c2f8c3930c6)

**Comment by wang-bin** [comment]
什么系统？debian系的话用apt安装下，linux下装这些应该不是问题，依赖参考 https://github.com/wang-bin/mdk-sdk/wiki/System-Requirements#linux-desktop-raspberry-pi-os

glfw是部分测试程序的依赖，debian上glfw 有两个包，如果x11环境装libglfw3, wayland环境装libglfw3-wayland

**Comment by wang-bin** [comment]
你的硬件应该可以用rkmpp解码器，渲染的话用egl + opengles性能最好 `./glfwplay -c:v rkmpp,V4L2M2M,FFmpeg -es test.mp4`。不过我没在这板子上试过，只测过树莓派，有点类似。有问题的话可以贴下日志

**Comment by feiyangqingyun** [comment]
好的，谢谢回复
