### ISSUE TITLE
Thumbnail generation

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#164]
since 0.23.0.1166, i use new code from Thumbnail example. Now i can't anymore extract a frame at a position. 25%, 50% and 75% give the same image. It happens on any video file (Windows).

**Comment by feiyangqingyun** [comment]
try the latest build

**Comment by wang-bin** [comment]
can't reproduce with `Thumbnail.exe -from 0.5 test.mp4`. You can show me your log, or send me a video
