### ISSUE TITLE
开启最快速度解码后音频严重滞后

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#165]
int main(int argc, char *argv[])
{
QApplication a(argc, argv);

QMDKWidgetRenderer w;
w.show();

QMDKPlayer p;
p.setMedia("rtsp://xxxx");
//开启最快速度解析后视频速度是快了，但是音频严重滞后好几秒，感觉好像是还在做同步，音频应该也要最快速度才行
player->onSync([] { return DBL_MAX; });
p.addRenderer(&w);
p.play();

return a.exec();
}

**Comment by wang-bin** [comment]
音频比较麻烦，得实时估计播放速度再对音频数据转换

**Comment by feiyangqingyun** [comment]
大佬加油，相信你能搞定的。

**Comment by feiyangqingyun** [comment]
> 音频比较麻烦，得实时估计播放速度再对音频数据转换

大佬再麻烦问下，你单独编译的那些ffmpeg库。有没有把freetype编译进去？谢谢

**Comment by wang-bin** [comment]
没有，用不到，只编译最基本的供暖

**Comment by feiyangqingyun** [comment]
> 没有，用不到，只编译最基本的功能

实际应用中，文字水印很常用的

**Comment by wang-bin** [comment]
> > 没有，用不到，只编译最基本的功能
> 
> 实际应用中，文字水印很常用的

不要在一个issue下讨论无关的话题
