### ISSUE TITLE
android使用sync控制视频进度的时候，会不断间隔黑屏

### ISSUE THREAD

**Issue by ken626014896** [wang-bin/mdk-sdk#167]
最新的安卓sdk，会黑一下然后好一下，之前旧sdk的没发现这个问题 
旧的版本好像是MDK-JNI 0.22.1 (git 4a0d0d6) - Multimedia Development Kit. Copyright (c) 2016-2023 WangBin(QtAV author) <wbsecg1 at gmail.com>
开发板是rk3568 android11
[log.txt](https://github.com/wang-bin/mdk-sdk/files/13792424/log.txt)

**Comment by ken626014896** [comment]
internal_player->setDecoders(MediaType::Video,{"AMediaCodec", "FFmpeg", "dav1d"});这个是解码设置

**Comment by wang-bin** [comment]
刚播放的时候黑一下？我的android例子呢？

**Comment by wang-bin** [comment]
AMediaCodec:acquire=latest 试下

**Comment by ken626014896** [comment]
用的是qml的例子，使用sync控制视频进度，设置了确实不闪黑屏了

**Comment by wang-bin** [comment]
好，最近在做多屏显示改过一些参数，我后面把这个不黑的改成默认的

**Comment by wang-bin** [comment]
最新包把这个参数设成默认的了

**Comment by ken626014896** [comment]
测试了，不加参数也正常了，感谢作者大大
