### ISSUE TITLE
国产aarch64架构的cpu和国产系统的， 怎么使用mdk-sdk？

### ISSUE THREAD

**Issue by liquanguo** [wang-bin/mdk-sdk#168]
如题：国产aarch64架构的cpu和国产系统的，例如飞腾2000cpu的麒麟系统， 怎么使用mdk-sdk？
最近在国产系统上做了个播放器，之前一直在Windows上使用，直接下载release版本调用库就可以了。
现在在国产aarch64架构下，是使用哪一个release版本，还是需要交叉编译的。
谢谢。

**Comment by wang-bin** [comment]
mdk-sdk-linux.tar.xz这个包，lib/arm64下面的就是aarch64的库，ffmpeg可以使用包里的，如果系统里有特殊优化过的也可以用系统的。ldd看下缺什么库安装下，如果依赖解决不了可以提出来我减少依赖

**Comment by liquanguo** [comment]
> mdk-sdk-linux.tar.xz这个包，lib/arm64下面的就是aarch64的库，ffmpeg可以使用包里的，如果系统里有特殊优化过的也可以用系统的。ldd看下缺什么库安装下，如果依赖解决不了可以提出来我减少依赖

好的，第一次弄交叉编译，非常感谢！

**Comment by wang-bin** [comment]
可以交叉编译也可以直接目标机器上编译

**Comment by liquanguo** [comment]
好的
