### ISSUE TITLE
Dead lock on mp4 playing

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#177]
On Windows, we have a dead lock after playing 2/3s

https://github.com/wang-bin/mdk-sdk/assets/1200371/642aa328-06e8-4d2a-a2e8-d098b47fced8

**Comment by wang-bin** [comment]
log

**Comment by pierrexn** [comment]
sorry here is
[logs.txt](https://github.com/wang-bin/mdk-sdk/files/13917654/logs.txt)

**Comment by wang-bin** [comment]
fixed in the latest build
