### ISSUE TITLE
Question. I have a device that receives an rtsp stream and plays it through your library. Is it possible to stream this video to another device

### ISSUE THREAD

**Issue by He11c0der** [wang-bin/mdk-sdk#178]
Hi. Question. I have a device that receives an rtsp stream and plays it through your library. Is it possible to stream this video to another device and play it through your library

**Comment by wang-bin** [comment]
you need a stream server, then `Player.record("rtmp://.... or rtsp://... etc.)` can stream current video to the server, and other devices receive streams from the server.

**Comment by wang-bin** [comment]
yes
