### ISSUE TITLE
MDK Console output 

### ISSUE THREAD

**Issue by oomek** [wang-bin/mdk-sdk#18]
Hi, I see that your lib is throwing a little bit of text to the console on start:
```
MDK 0.10.0 (git 7a075dab) - Multimedia Development Kit. Copyright (c) 2016-2020 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Raspberry Pi ARMv6; Clang8.0.1 (branches/release_80)GCC4.2.1; libc++9000; 02:01:20 Sep 29 2020
```
I understand that it's a way of advertising yourself, so you would not be keen on adding an option to remove it, but how about making it a little less obtrusive, getting rid of compiler specific info ( set with env var maybe ) and keeping the limit of 80 chars? Would you agree to do it by any chance?

**Comment by wang-bin** [comment]
env var is acceptable.

**Comment by oomek** [comment]
Awesome, thanks.

**Comment by wang-bin** [comment]
use the latest binary and export MDK_BUILD_INFO=0

**Comment by oomek** [comment]
Thank you very much

**Comment by oomek** [comment]
Tried to set this variable in the code but it seems it's added to late as the info still shows up.
```
char env[] = "MDK_BUILD_INFO=0";
putenv(env);
```
