### ISSUE TITLE
mdk-sdk crash on custom Url or protocol

### ISSUE THREAD

**Issue by ChrisThis** [wang-bin/mdk-sdk#181]
I have registered my custom protocol with the name "qio":

`mdk::abi::MediaIO::registerOnce("qio", []{ return new MyMdkSdk::MyIODevice();});
qInfo() << "MyMdkSdk::MyIODevice register QIODevice";
qInfo() << "MyMdkSdk::MyIODevice registered" << mdk::abi::MediaIO::registered();`

mdk-sdk log output:

> register uri MyOSQML
MyMdkSdk::MyIODevice register QIODevice
MyMdkSdk::MyIODevice registered std::vector("FFmpeg", "Mem", "qio", "QIODevice")
MDK 0.25.0 (git 2200147) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux x86_64; Clang18.1.0 (++20240131123237+400a02bb281b-1~exp1~20240131003348.16)GCC4.2.1; libc++180100; 13:34:50 Jan 31 2024
MDK video decoders: "VAAPI", "VDPAU", "hap", "dav1d", "CUDA", "FFmpeg"

to implement my own protocol i user your example form QtMultimediaPlugin.
This works perfect for my last version of mdk-sdk 0.18.x (Clang compiler for my own qio protocol)

Now it crash when i call 'Prepare'
here some log output:

> MDK setNext from -1 url:
MDK default FrameReader0x204aea0 state: 0=>0=>0, 0
MDK default0x204aea0 virtual void mdk::FrameReader::stop(), current state: 0
MDK clear on stop
MDK clear on stop
MDK default FrameReader0x204aea0 state: 0=>0=>0, 0
MDK default0x204aea0 virtual void mdk::FrameReader::stop(), current state: 0
MDK AudioBackendALSA ERROR@285>>> snd_pcm_pause(pcm_, value) (fffffffb): Input/output error
MDK 
MDK 0x2282ef0 MediaControl.prepare(0, ...) qio:92883856
MDK default 0x204aea0 FrameReader.start(0, ...)
MDK default 0x204aea0 FrameReader::update MediaStatus 0=>0X2
Intern media status changed LoadedMedia
MyMultimedia::MediaPlayer MDK media status changed 2
MDK default FrameReader0x204aea0 state: 0=>0=>1, 0
MDK default FrameReader0x204aea0 state: 0=>1=>1, 0
MDK start frame reader thread: 140057766840000
MDK Selected avformat runtime version: 60.20.100 (build: 60.20.100), license: LGPL version 2.1 or later
MDK avformat_version0x7f620caf6961
MDK qio: Url or protocol is not supported by MediaIO FFmpeg
MDK qio: Url or protocol is not supported by MediaIO Mem

I tested it on linux and ios.

Thanks

**Comment by wang-bin** [comment]
are you using the latest abi sdk headers? they are not compatible with old versions. if correct headers are used but your app still crashs, then i need the backtrace, keep libmdk.so*.dsym in the same dir of libmdk so.0 and run gdb

**Comment by ChrisThis** [comment]
where can i find the current abi sdk headers?

**Comment by wang-bin** [comment]
github action artifacts, download mdk-abi-sdk

**Comment by ChrisThis** [comment]
Perfect, thanks
not it works :)
