### ISSUE TITLE
Dead lock

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#185]
I have a dead lock when trying to play this file on windows (mdk 0.24)

https://github.com/wang-bin/mdk-sdk/assets/1200371/5a8a7505-71d6-40ae-9935-731c4cab5822

[logs.txt](https://github.com/wang-bin/mdk-sdk/files/14478299/logs.txt)

**Comment by wang-bin** [comment]
the latest build works fine
