### ISSUE TITLE
请教一个问题，onFrame 在窗口最小化时就没有回调了，导致窗口最小化时视频相当于就被暂停了，有什么好的解决方法吗

### ISSUE THREAD

**Issue by RAVER0306** [wang-bin/mdk-sdk#187]

**Comment by wang-bin** [comment]
onFrame不需要窗口也有回调，你代码里暂停的，你可以给个最简单的例子

**Comment by RAVER0306** [comment]
> onFrame不需要窗口也有回调，你代码里暂停的，你可以举个最简单的例子

不好意思，是我在updatePaintNode中阻塞了  onFrame，似乎最小话QQuickItem就不触发updatePaintNode了，我能在onFrame里面将QSGNode转成纹理提供给 QQuickItem 去绘制吗，因为我需要在onFrame解码的帧之上绘制一些内容

**Comment by wang-bin** [comment]
qsgnode(qsgsimpletexturenode)本来就可以提供纹理给item显示的，和onFrame没关系，onFrame不在渲染线程没法直接操作qsgnode。如果只是绘制简单的内容不需要知道帧内容，renderVideo()之后就可以加你想绘制的代码。如果要对渲染后帧的内容进行处理，可以参考 [gyroflow 里用的代码](https://github.com/AdrianEddy/qml-video-rs/blob/master/src/cpp/MDKPlayer.cpp#L321)，可能需要注意[同步问题](https://github.com/AdrianEddy/qml-video-rs/blob/master/src/cpp/MDKPlayer.cpp#L360)

**Comment by RAVER0306** [comment]
> renderVideo()

我刚刚试了一下，在窗口最小化的时候，QQuickWindow::beforeRendering 信号似乎也没有发出，听您说的方法，我是需要在onFrame里面使用QRhi的接口将纹理提供给QRhi，然后再onFrame的最后调用一次renderVideo()吗

**Comment by wang-bin** [comment]
onframe不能用，线程不对，你要确保在qsg的渲染线程里渲染。最小化了为啥还要渲染？不清楚你要做什么

**Comment by RAVER0306** [comment]
我目前的做法是在updatePaintNode中通过grabToImage获取quickitem的绘制内容，最小化之后收不到这些信号，这条路就走不通了

**Comment by RAVER0306** [comment]
我在onframe之后需要保存帧图片，然后再到updatePaintNode绘制AI识别帧的方框，最后对比原图和在VideoTextureNode基础上绘制一些方框的图片

**Comment by wang-bin** [comment]
最小化了为什么还要处理？没最小化你是怎么做的？

**Comment by RAVER0306** [comment]
没最小化是在updatePaintNode里面使用 grabToImage 和 QSGGeometry 做的

**Comment by RAVER0306** [comment]
现在我应该是要在onframe里面通过OpenCV或者qt相关的工具类画好转成纹理提供给item绘制了，这样Qt不绘制也能正常保存原图和AI识别的图片了

**Comment by wang-bin** [comment]
要用内存上都数据处理的话onframe回调里对frame数据处理，硬解用frame.to()拷贝显存数据和转换格式等，处理好再赋值给frame，这么做会很慢。

**Comment by wang-bin** [comment]
没最小化你是怎么处理的？最小化也同样方法啊。没明白你是碰到了什么问题。你得把标题改改，issue内容写清楚具体问题

**Comment by wang-bin** [comment]
要用内存上都数据处理的话onframe回调里对frame数据处理，硬解用frame.to()拷贝显存数据和转换格式等，处理好再赋值给frame，这么做会很慢。grabimage也是慢的

**Comment by RAVER0306** [comment]
好吧，非常感谢您的帮助
