### ISSUE TITLE
App crashes onFrame during seek

### ISSUE THREAD

**Issue by thyagarajarahul1** [wang-bin/mdk-sdk#190]
The application crashes when trying to read frame values using onFrame. Also, how would one go about performing face detection using OpenCV and returning the new frame with face-detected markings?

**Comment by wang-bin** [comment]
Show me your onFrame() code and log

**Comment by wang-bin** [comment]
```cpp
player.onFrame<VideoFrame>([](VideoFrame& frame, int track) {
    frame = opencv_result_frame(frame);
    return 0;
});
