### ISSUE TITLE
OpenCV Support

### ISSUE THREAD

**Issue by thyagarajarahul1** [wang-bin/mdk-sdk#191]
How do I convert VideoFrame to something that OpenCV can work with (Mat)? There seems to be a lag in the video playback while using OpenCV inside onFrame, I am first converting the frame to QImage and then using that QImage to run OpenCV. Would you have any idea as to why? And should I use a thread to stop blocking the main ui thread?

I tried to do this -> cv::Mat cvFrame(frame.height(), frame.width(), CV_8UC4, frame.bufferData(), frame.bytesPerLine());

**Comment by wang-bin** [comment]
I'm not familiar with opencv. converting to qimage will be very slow. the most effecient way is rendering to an offscreen texture, then comsumed by opencv. I'm not sure if opencv supports creating a Mat from a textur. If you are using d3d11, [cv::directx::convertFromD3D11Texture2D](https://docs.opencv.org/4.x/de/dc1/group__core__directx.html#gaaea63f9b492b4a84e1e9ef6d4eba377c) may work

**Comment by wang-bin** [comment]
If you are using qt6 qml, [here is an example](https://github.com/AdrianEddy/qml-video-rs/blob/master/src/cpp/MDKPlayer.cpp#L321) 

without rhi, you have to write more code to create texture and context
