### ISSUE TITLE
The video is not displayed when using QUdpSocket

### ISSUE THREAD

**Issue by He11c0der** [wang-bin/mdk-sdk#196]
Hi
I have a problem
Previously, I did not use qudpsocket in my application and the method "bind" ( m_videoSocket->bind(QHostAddress::Any,port)) indicating the port to which the video stream is coming. Now that I initialized it, the video is not displayed in the QML element.
Maybe the problem is that I declared the following in the constructor of the server class:
m_player = new QMediaPlayer(this);
    m_videoBuffer.open(QIODevice::ReadWrite);
  m_videoStream.setDevice(&m_videoBuffer);

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-sdk/wiki/Troubleshooting#custom-io

**Comment by wang-bin** [comment]
> 
> Do I just have to do "Change mdk include path to mdk-sdk/include/abi and rebuild the project. ", after downloading mdk-sdk-abi  and the video will be displayed and I can use QUdpSocket?

yes. otherwise QIODevice support is disabled

**Comment by wang-bin** [comment]
show me your build error

**Comment by wang-bin** [comment]
what's the build command? maybe include dir is wrong in the command

**Comment by wang-bin** [comment]
it's ` INCLUDEPATH += $$MDK_SDK/include/abi` not` INCLUDEPATH += $$MDK_SDK/include/abi/mdk`

**Comment by wang-bin** [comment]
build your QIODevice support code as a static(or shared) library with abi headers. Other code still use public headers
