### ISSUE TITLE
WAV not playing

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#197]
this .wav file doesn't play

[CIMG2392.zip](https://github.com/wang-bin/mdk-sdk/files/15142319/CIMG2392.zip)

[logs.txt](https://github.com/wang-bin/mdk-sdk/files/15142317/logs.txt)

**Comment by wang-bin** [comment]
the codec `adpcm_ima_wav` is not included in the ffmpeg(lite version) from mdk package. you can try ffmpeg default version from https://sourceforge.net/projects/avbuild/files/windows-desktop/
