### ISSUE TITLE
Add support for Qt RHI

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/mdk-sdk#2]
Qt正在逐步移除对OpenGL的直接调用，改用RHI这个抽象层。去年发布的Qt 5.14已经添加了RHI的实验性支持，Qt6会全面迁移到RHI。我看了examples里MDK与Qt的对接，目前是直接调用OpenGL的API。未来MDK有支持Qt RHI的计划吗？

**Comment by wangwenx190** [comment]
或者说把示例代码迁移到RHI

**Comment by wang-bin** [comment]
qt 的rhi还没仔细看，大概可以通过QRhiNativeHandles来访问图形api相关的对象，然后生成mdk的相应的`RenderAPI`对象设置给player就行。目前`RenderAPI`支持opengl和d3d。metal预计下个月就能支持。vulkan最后(vulkan有很多恶心的设计)。`RenderAPI`的例子可以参考https://github.com/wang-bin/obs-mdk/blob/master/mdkvideo.cpp#L97 、https://github.com/wang-bin/mdk-examples/blob/master/GLFW/glfwplay.cpp#L258  、https://github.com/wang-bin/mdk-examples/blob/master/WindowsStore/XamlCx/OpenGLESPage.xaml.cpp#L30 以及wiki https://github.com/wang-bin/mdk-sdk/wiki/Render-API。
mdk有了`RenderAPI`理论上就能支持任意的应用环境。

**Comment by wang-bin** [comment]
等qrhi接口公开后我会加例子

**Comment by wangwenx190** [comment]
明白了，谢谢。

**Comment by wangwenx190** [comment]
目前QML的例子用的是FBO，这样就完全和OpenGL绑定了，明显与RHI的初衷不符，希望能增加一个基于RHI的QML例子。

**Comment by wang-bin** [comment]
看到qt的例子了，我会尽快写个

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-examples/tree/master/Qt/qmlrhi

**Comment by wangwenx190** [comment]
现在就等MDK支持Vulkan了

**Comment by wangwenx190** [comment]
问一下哈，我看0.9.0引入了`GLRenderAPI`，RHI例子用的是Qt的FBO，为什么不用`GLRenderAPI`做呢？是因为用FBO最简单吗？

**Comment by wang-bin** [comment]
不管什么情况GL 都是绘制在一个fbo上的，只不过由于gl的特点用户不需要把相关信息传给mdk，也在考虑后面把fbo传过来，这样用户代码更简洁，例子的render函数里不需要判断是否gl了。其他的接口比如d3d 是必须传些信息才能绘制。glrenderapi 目前只是用来配置内部创建的上下文的参数，可以测下glfwplay的-gl参数。用户提供的gl上下文一般情况下不需要配置
