### ISSUE TITLE
mdk支持安卓上打开本地摄像头吗？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#200]
试了下代码好像不行，player->setMedia("avdevice://dshow:/dev/video0")，权限也都给了，包括动态申请camera的权限。

**Comment by wang-bin** [comment]
你用错了，安卓没有dshow

**Comment by feiyangqingyun** [comment]
我这里填错了，实际填的是v4l2

**Comment by wang-bin** [comment]
v4l2也不支持，有专门的

**Comment by feiyangqingyun** [comment]
那mdk有没有办法打开

**Comment by wang-bin** [comment]
avdevice有个android_camera，不过我没编进去
