### ISSUE TITLE
qt+macos上如何引入文件？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#201]
提供了libffmpeg.7.dylib、libmdk-r3d.dylib、libmdk-braw.dylib、libass.dylib、mdk几个文件，唯独没有提供libmdk.dylib文件。那应该怎么引入呢？
![QQ截图20240513132711](https://github.com/wang-bin/mdk-sdk/assets/3894710/1fbaef77-a761-4491-9184-b93e4db2e3e1)

**Comment by wang-bin** [comment]
`-framework mdk`, 已经有了。dylib是依赖，libmdk-*.dylib是插件

**Comment by feiyangqingyun** [comment]
那这个mdk是动态还是静态库？为啥不是统一的libmdk.dylib这种格式呢

**Comment by wang-bin** [comment]
动态库。苹果上建议用framework。只有macos支持dylib，其他系统比如ios都不支持。
