### ISSUE TITLE
Unable to get pixel aspect ratio of a video

### ISSUE THREAD

**Issue by oomek** [wang-bin/mdk-sdk#202]
**Describe the bug**
I can get width and height of the video
```
auto video_info = player.mediaInfo().video[0];
player.setVideoSurfaceSize(video_info.codec.width, video_info.codec.height);
```
But I don't seem to find a way of getting the pixel aspect ratio of a video stream when it's not 1:1
I'd need that to scale the SFML sprite accordingly.

Is there any documentation of a structure returned by the `mediaInfo()` function?

P.S.
I need to use `player.setAspectRatio(IgnoreAspectRatio)` to ~~eliminate black bars~~ make a frame around the video using another sprite.

**Comment by oomek** [comment]
Btw the SFML example seems to use obsolete functions.

**Comment by wang-bin** [comment]
`VideoCodecParameters.par`

> Btw the SFML example seems to be using obsolete function calls.

updated

**Comment by oomek** [comment]
Brilliant. Thanks.
