### ISSUE TITLE
您好，我如何获取，视频帧实际渲染的宽高是多少？

### ISSUE THREAD

**Issue by RAVER0306** [wang-bin/mdk-sdk#206]

**Comment by RAVER0306** [comment]
或者说，我能在onFrame修改帧的像素内容重新丢进去渲染吗

**Comment by wang-bin** [comment]
mediainfo里有宽高，宽高发送改变有`{track, "video", "size", {width, height}}`事件

onFrame回调的参数是用户可修改的视频帧。不过对于硬件解码我没提供接口访问gpu资源，你得用软解或VideoFrame.to()转为可访问的资源。

**Comment by RAVER0306** [comment]
原视频尺寸1920*1080  QQuickItem 大小是 1100*700，我想获取你实际绘制内容的宽高是多少，不知道你是如何控制缩放的

**Comment by RAVER0306** [comment]
![image](https://github.com/wang-bin/mdk-sdk/assets/39723661/b913793a-f7a0-41b6-a62b-e914d385d1cf)
我目前是这样计算缩放偏移的，发现偏差有点大

**Comment by RAVER0306** [comment]
> 默认是按视频宽高比 * MediaInfo.video[].codec.par 缩放到 setVideoSurfaceSize 设置的大小的。您也可以使用其他缩放模式 setAspectRatio

好嘞，我试试

**Comment by RAVER0306** [comment]
是不是因为显示对其导致的误差,我看网上说h.264是16像素对其

**Comment by wang-bin** [comment]
没关系

**Comment by wang-bin** [comment]
我关了，这个不是issue，应该开discuss

**Comment by RAVER0306** [comment]
![image](https://github.com/wang-bin/mdk-sdk/assets/39723661/a9b825e8-4d46-440a-ade0-ef576bd7858c)
![image](https://github.com/wang-bin/mdk-sdk/assets/39723661/cf35dc8a-88d4-487f-ae35-d1124a75a27c)


还请留步，我在onFrame里面to save了，第二张图片是to save的，第一张是绘制显示的，可以明显看到高度不一致了

![image](https://github.com/wang-bin/mdk-sdk/assets/39723661/fdfeb4ef-7245-4ce6-9f7b-16a29bd5e623)

你会进行裁剪吗

**Comment by wang-bin** [comment]
save只用宽高没用par，所以可能不一样。par信息我可能每写进图片里。
渲染不裁剪，除非你设crop相关的aspectratio

你可以在讨论里开个话题。开issue和讨论注意模板，比如提供日志，否则会浪费很多时间
