### ISSUE TITLE
mdk中如何设置打开超时？

### ISSUE THREAD

**Issue by feiyangqingyun** [wang-bin/mdk-sdk#209]
如果打开一个不存在的视频流地址比如rtsp://192.168.0.11，所有回调信息中都不会有任何反应，不知道有没有哪里设置个超时时间，然后onStateChanged/onEvent哪个事件中给个提示。这样方便后续处理。谢谢

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#void-settimeoutint64_t-ms-stdfunctionboolint64_t-ms-cb--nullptr

**Comment by feiyangqingyun** [comment]
试过了，确实可以，谢谢。
player->setTimeout(1000, [this](int64_t ms) {
        qDebug() << "xxx" << ms;
        return true;
    });

**Comment by feiyangqingyun** [comment]
发现个现象，rtsp rtmp这种超时都会有执行，但是ws这种就不会有，除了对前缀格式过滤，超时这边也能有反应吗？谢谢
