### ISSUE TITLE
某些视频D3D11解码几帧后停止

### ISSUE THREAD

**Issue by qht1003077897** [wang-bin/mdk-sdk#22]
mdk version：0.10.3   
QT 5.12.0
windows x64

**Comment by qht1003077897** [comment]
https://user-images.githubusercontent.com/16768811/107141408-74f7ae80-6963-11eb-9d07-cc9c18d31cb4.mp4

这个mp4用d3d11解码会出现问题，导致视频只播放了几帧

**Comment by wang-bin** [comment]
can't reproduce by glfwplay. what about using glfwplay in your environment? and log will be helpful
