### ISSUE TITLE
ubuntu20下QT应用崩溃

### ISSUE THREAD

**Issue by boyj26** [wang-bin/mdk-sdk#221]
在ubuntu20系统下，Qt6.7环境中使用官方示例中的 QMDKWidget 播放RTSP程序会崩溃，添加log定位是在 QMDKWidget::paintGL中player_->renderVideo(/*this*/) 后发生崩溃的，请问这大概是什么问题呢？

**Comment by wang-bin** [comment]
请按照issue模版贴上日志。崩溃的话用gdb调试，用bt full输出调用堆栈，也贴出来，否则无法提供任何帮助

**Comment by boyj26** [comment]
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
capi::version: 0.8.2
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
X11 display: 0x555555a7a4d0
resizeGL>>>>>dpr: 1.000000, logical dpi: (96.000000,96.000000), phy dpi: (96.047267,96.075650)
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory


![QQ截图20240621090723](https://github.com/wang-bin/mdk-sdk/assets/13598455/7593b483-b233-4ade-b934-9dff1ebace69)

**Comment by wang-bin** [comment]
日志要发完整，用setLogHandler输出到文件，否则从qtcreator复制可能不完整。

调试没看到代码文件名和行号，libmdk.so.*.dsym和libmdk.so.0在同一个目录吗？

**Comment by boyj26** [comment]
日志就这么多 输出到文件更少
libmdk.so.*.dsym和libmdk.so.0是在同一个目录中的
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/347a5f54-c06d-45fe-b8fe-cd4a3f5c4316)
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/827a63c1-9533-48f9-9438-856da8fc84a0)
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/a8878ac2-3ac5-4dbc-a709-ff09b790cca6)


使用的是 https://github.com/wang-bin/mdk-examples/tree/master/Qt/QMDKWidget 完整实例
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/9d17f531-b4b3-4548-a951-a9558424056b)

崩溃也是QMDKWidget::paintGL中的player_->renderVideo(/*this*/)开始的
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/458b59ec-80fb-4486-ba44-7ce005e3230c)

**Comment by boyj26** [comment]
11:03:24: Debugging /home/hit/ws_qt/git/explosion-proof-car/build/Desktop_Qt_6_7_2-Debug/ExplosionProofCar ...
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
capi::version: 0.8.2
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
0.28.0 (git 4504be1) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux x86_64; Clang18.1.6 (++20240518023229+1118c2e05e67-1~exp1~20240518143321.130)GCC4.2.1; libc++180100; 15:46:29 Jun  1 2024
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
0x55555601d000>1200 00:00:00.0/00:00:01 cache 0v 0.0s/199KB 4331KB/s |-1200|>4ms update infms
[Desktop_Qt_6_7_2-Debug2024-06-21-11-02-21-log.txt](https://github.com/user-attachments/files/15922213/Desktop_Qt_6_7_2-Debug2024-06-21-11-02-21-log.txt)

**Comment by wang-bin** [comment]
我关心的是 `UGL::opengl::Context::current(void*)`是哪一行，你双击看看。所有mdk的调用都没行号，很奇怪，我这边试了下有行号

**Comment by wang-bin** [comment]
setLogHandler你是怎么写的？

**Comment by wang-bin** [comment]
另外，你下载最新的nightly包测试

**Comment by boyj26** [comment]
使用最新的nightly包还是一样的崩溃

双击UGL::opengl::Context::current(void*)也没有具体的行数，是我下载的sdk不包含源码吧
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/c4f8aac7-6f93-447a-8387-334805343418)


我在QT里面使用的 qInstallMessageHandler(outputMessage);
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/fc835b40-b908-4a06-9a77-ce3a81e0d306)

**Comment by wang-bin** [comment]
不需要源码就能看到行号的。不知道是不是gdb版本问题，你看看libmdk.so.*.dsym是否加载了。

mdk的setLogHandler呢？

**Comment by boyj26** [comment]
我用gdb命令看了下好像的确没有加载
使用mdk的setLogHandler的log如下
[log.txt](https://github.com/user-attachments/files/15924449/log.txt)

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-examples/blob/d6035e1450039962577ada748a9be37620c6e6c9/Qt/QMDKWidget.cpp#L175-L179 你把这几行注释掉
```
    ra.getProcAddress = +[](const char* name, void* opaque) {
        Q_UNUSED(opaque); // ((QOpenGLContext*)opaque)->getProcAddress(name));
        return (void*)QOpenGLContext::currentContext()->getProcAddress(name);
    };
    ra.opaque = context();
```
linux下的gl getprocaddress会返回无效值，由于没找到如何判断无效的相关文档，我这边没处理，然后会挂，之前我也碰到过。这代码是后来加的，用来验证一些功能，不加也没问题

**Comment by wang-bin** [comment]
gdb不显示行号问题我晚点再查查看

**Comment by wang-bin** [comment]
可以显示行号啊，我用gdb调试glfwplay，随便播放一个视频再ctrl + c，info threads找到线程名有adec, vdec, demux, reader的切过去，然后bt就能看到行号。`ps -ef |grep gdb`查到gdb进程号，`pmap -p $gdb_pid |grep dsym`可以看到符号文件加载了

**Comment by wang-bin** [comment]
我记得我也是在2004下复现的，新一点的系统不会，可能是mesa那边有改进。你在intializeGL()里加下面几行代码看看打印什么值
```c++
#include <EGL/egl.h>

....

void QMDKWidget::initializeGL()
{
    const auto f = (PFNEGLGETCURRENTDISPLAYPROC)QOpenGLContext::currentContext()->getProcAddress("eglGetCurrentDisplay");
    const auto disp = f();
    qDebug("display: %p", disp);
}
```

**Comment by boyj26** [comment]
注释ra.getProcAddress后不闪退可以用了。

qDebug("display: %p", disp); 输出的是 0xfffffffffffffe98

ps -ef |grep gdb和pmap -p $gdb_pid |grep dsym看到符号文件加载了，但是也没有行号的
![image](https://github.com/wang-bin/mdk-sdk/assets/13598455/61daa570-10e1-40bd-91da-0870d25fb0ba)

**Comment by wang-bin** [comment]
你装个lldb或者升级到gdb 10就能显示行号，看上去是llvm的问题 https://discourse.llvm.org/t/gdb-10-1-cant-read-clangs-dwarf-v5/6035/15

最新包不注释应该也没问题了
