### ISSUE TITLE
在i7-7700、显卡P2000的设备上，解码5760 3240 h265编码的视频，出现卡顿、音视频不同步问题

### ISSUE THREAD

**Issue by flowerlove** [wang-bin/mdk-sdk#224]
**Describe the bug**
在i7-7700、显卡P2000的设备上，解码5760 3240 h265编码的视频，出现卡顿、音视频不同步问题。当我第一次打开视频时，显卡的硬解码核心占用100%，画面卡住不动，但是音频仍在播放，过一分钟左右GPU硬解码核心占用掉下来，但是此时画面与音频仍不同步，且播放卡顿。
渲染方式：
d3d11_render_api_ = new MDK_NS::D3D11RenderAPI();
d3d11_render_api_->rtv = texture_render_;
start_update_texture_thead();

mdk_player_->setRenderAPI(d3d11_render_api_, VideoPlayer::GetInstance());
mdk_player_->onStateChanged(on_state_);
mdk_player_->onEvent(on_event_);
mdk_player_->onMediaStatusChanged(on_media_status_changed_);
mdk_player_->setRenderCallback(on_rendercallback_);
mdk_player_->setVideoSurfaceSize(width_, height_, VideoPlayer::GetInstance());
解码器设置顺序：
mdk_player_->setDecoders(MDK_NS::MediaType::Video, { "MFT:d3d=11", "D3D11", "CUDA", "hap", "FFmpeg", "dav1d" });

**Environment:**
 - OS: Win10 21h2
 - GPU: P2000 4G

[log.txt](https://github.com/user-attachments/files/16060993/log.txt)

**Comment by wang-bin** [comment]
prepare起始时间39秒但是只能seek到0秒，由于是精确seek，视频会从0开始全速解码直到39s而不渲染，所以解码核心100%

**Comment by flowerlove** [comment]
> prepare起始时间39秒但是只能seek到0秒(这个有点奇怪)，由于默认是精确seek，视频会从0开始全速解码直到39s而不渲染，所以解码核心100%

我刚看了一下，如果我上一次退出时在39秒退出，那么下次启动前会进行prepare(39000)，是因为这个原因导致的吗？

**Comment by flowerlove** [comment]
我理解是应该SEEK到39秒向后查找关键帧，本视频多处均存在关键帧，并不是只有开头才有。素材连接：https://cowtransfer.com/s/417b41c0549443 点击链接查看 [ 大堂 无边_1.mp4 ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 vhc5vj 查看；

**Comment by flowerlove** [comment]
prepare有办法改为非精确SEEK么？

**Comment by wang-bin** [comment]
prepare 最后一个参数改成 SeekFlag::Default就行。这个视频只有第一帧是关键帧，只能这个效果了

**Comment by flowerlove** [comment]
> prepare 最后一个参数改成 SeekFlag::Default就行。这个视频只有第一帧是关键帧，只能这个效果了

我使用./ffmpeg.exe -i ./test1.mp4  -vf "select= eq(pict_type\,I)" -vsync vfr output_%05d.jpg 导出关键帧，并不是只有第一秒有呀

**Comment by wang-bin** [comment]
`ffprobe -select_streams 0 -show_frames -of csv `只有第一帧是关键帧。seek的时候关键帧信息是封装格式里给的, mp4给的信息只有第一帧关键帧。hevc码流其实有很多关键帧，不过这个信息没法被seek使用。vlc、mpv、quicktime都很慢。

**Comment by wang-bin** [comment]
要快速seek的话最简单的就是不管关键帧，不过会花屏，不花屏还得自己解析码流，做也可以做

**Comment by flowerlove** [comment]
> `ffprobe -select_streams 0 -show_frames -of csv `只有第一帧是关键帧。seek的时候关键帧信息是封装格式里给的, mp4给的信息只有第一帧关键帧。hevc码流其实有很多关键帧，不过这个信息没法被seek使用。vlc、mpv、quicktime都很慢。

是的，我测试了mpv，也是这个效果。不过还有一点区别：mdk最新版本SEEK的时候，会有声音在播放，mpv SEEK的时候声音不会播放。

**Comment by flowerlove** [comment]
比较好奇的是，像potplayer、开源的mpc-hc，都是可以正常SEEK的，但是MPV、VLC确实不行
