### ISSUE TITLE
Freezing Issue When Quickly Switching Videos

### ISSUE THREAD

**Issue by ZhouYing-bit** [wang-bin/mdk-sdk#225]
**Describe the bug**
When I switch video playback quickly, if the switching interval is around 100ms, it will permanently freeze and become unresponsive. However, if the switching interval is set to 1 second, there is no issue.

If there is a playlist feature on the UI, users can reproduce this issue by quickly clicking the next button.

![image](https://github.com/wang-bin/mdk-sdk/assets/13702789/68fdf859-d07e-4a1b-8e59-88da4d501084)

**To Reproduce**
```
    QTimer t;
    t.setInterval(100);
    t.callOnTimeout([&] {
        // switch play
        if (url == "E:\\测试视频\\VR\\SIVR-291-3+4-Ai Hongo_180_3DH.mp4") {
            url = "E:\\测试视频\\VR\\SIVR-273-3-Yura Kano_180_3DH.mp4";
        } else {
            url = "E:\\测试视频\\VR\\SIVR-291-3+4-Ai Hongo_180_3DH.mp4";
        }
        w.setMedia(url);
        w.play();

        // stop timer
        static int count = 0;
        count++;
        if (count >= 10) {
            t.stop();
        }
    });
    t.start();
```

**Expected behavior**
I believe that regardless of the frequency at which the interface is called externally, the program should not become unresponsive.

**Environment:**
 - OS: windows 11 23H2
 - GPU: RTX 3050TI

**Log**
[mdk_lock_log.txt](https://github.com/user-attachments/files/16093759/mdk_lock_log.txt)

```

**Comment by wang-bin** [comment]
`setMedia`前加个
```cpp
  player.set(State::Stopped); 
  player.waitFor(State::Stopped);  
```
