### ISSUE TITLE
QR Code watermark showing

### ISSUE THREAD

**Issue by oomek** [wang-bin/mdk-sdk#226]
I've done a benchmark that plays 64 60fps videos simultaneously and I've discovered that your lib is showing a QR Code watermark for a brief second. Could you please explain what is the purpose of it?

![image](https://github.com/wang-bin/mdk-sdk/assets/2974860/52fc7ae2-3b02-45b8-aeab-64050a5523b7)

**Comment by oomek** [comment]
Nevermind, old version.

**Comment by wang-bin** [comment]
the sdk will expired after 40 days(since sdk build time). https://github.com/wang-bin/mdk-sdk?tab=readme-ov-file#license

**Comment by oomek** [comment]
I see the appkey generator for Qt and Windows. How do I get the key for a multiplatform opensource app? Windows, MacOS, Linux, Raspbian etc. Does the key need to be generated locally for every end user or can it be added during building?

**Comment by wang-bin** [comment]
i need to know
- windows: executable name, product and company name in rc file (or QMAKE_TARGET_PRODUCT QMAKE_TARGET_COMPANY in qt qmake).
- macos, ios, android: app bundle id, e.g. com.example.test
- linux: executable name

then i can generate a key

**Comment by oomek** [comment]
Windows:
attractplus.exe
attractplus-console.exe
Product name: Attract-Mode Plus
https://github.com/oomek/attractplus
no company name

macos, ios, android:
app bundle id: attractplus ( we're not a company and we're not distributing our app in any appstore

Linux:
attractplus

Thanks

**Comment by wang-bin** [comment]
- windows: `SetGlobalOption("MDK_KEY", "83F484C3E1B0858C603DBFF95F86471207DBF447CECB7DE75808F168A133BFA1E46E37E3E7ADCEAA53A139FEAD0F149FA23B071630AA3AC8D6093CC1409765089BF47B3C1E4F7A739FC24006A079B8ED05DBE606BABF0F863B7CDC25CE57DA81B4024290C8EC6BD939A1BC98E339FF3A8E1B3AE3709B1B48F2A616C218976508");`
- else: `SetGlobalOption("MDK_KEY", "9324828C7CDA83AF8253261FE3EFBA760E072E41A3D82D07536ACE00BE32934A7FB6FAB193EEB0CA720A68D954AD1B7E09B2D11B03DED57140CD069FFE9F35086CDB7D7383257C507DACD9E01C1045890C072520D7AC5F66301EBE6CCB41EC5CE6DC7F930786D6B5145F3FF46291B8B7D3BA0EEBE88D519A52EA20A4DAD43508");`

If you `SetLogHandler()` before `SetGlobalOption("MDK_KEY"`, you can see your app name in log

**Comment by oomek** [comment]
Hi. I'm having troubles with the keys provided.

The key starting with `83F` doesn't work for either `attractplus.exe` or `attractplus-console.exe`
The key starting with `932` works for `attractplus.exe` doesn't work for `attractplus-console.exe`

Haven't check with Linux, or macOS yet.

**Comment by oomek** [comment]
```

**Comment by oomek** [comment]
```
D:\Documents\GitKraken\mdktest>attractplus.exe 1 1 videos/60s.mp4
0.29.1 (git 6a7cd03) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Windows0x0600/10.0.22635 x86_64; vcruntime14.41.34120/14.40.33816 msvcp140.dll; MSVC1941; 10:16:38 Aug 30 2024
global option: UserAddress = 00000000004017E7
global option: MDK_KEY = 9324828C7CDA83AF8253261FE3EFBA760E072E41A3D82D07536ACE00BE32934A7FB6FAB193EEB0CA720A68D954AD1B7E09B2D11B03DED57140CD069FFE9F35086CDB7D7383257C507DACD9E01C1045890C072520D7AC5F66301EBE6CCB41EC5CE6DC7F930786D6B5145F3FF46291B8B7D3BA0EEBE88D519A52EA20A4DAD43508
3mdk verify key signature ok
3mdk license key restrictions: OpenSource,
key time: -1
check version
user module: D:\Documents\GitKraken\mdktest\attractplus.exe
user module: D:\Documents\GitKraken\mdktest\attractplus.exe
3mdk license key for app: attractplus
```

**Comment by oomek** [comment]
```
D:\Documents\GitKraken\mdktest>attractplus-console.exe 1 1 videos/60s.mp4
0.29.1 (git 6a7cd03) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Windows0x0600/10.0.22635 x86_64; vcruntime14.41.34120/14.40.33816 msvcp140.dll; MSVC1941; 10:16:38 Aug 30 2024
global option: UserAddress = 00000000004017E7
global option: MDK_KEY = 9324828C7CDA83AF8253261FE3EFBA760E072E41A3D82D07536ACE00BE32934A7FB6FAB193EEB0CA720A68D954AD1B7E09B2D11B03DED57140CD069FFE9F35086CDB7D7383257C507DACD9E01C1045890C072520D7AC5F66301EBE6CCB41EC5CE6DC7F930786D6B5145F3FF46291B8B7D3BA0EEBE88D519A52EA20A4DAD43508
3mdk verify key signature ok
3mdk license key restrictions: OpenSource,
key time: -1
check version
user module: D:\Documents\GitKraken\mdktest\attractplus-console.exe
user module: D:\Documents\GitKraken\mdktest\attractplus-console.exe
3mdk license key for app: attractplus
1mdk license key does not support current app: attractplus-console|attractplus-console
1Bad mdk license!
```

**Comment by oomek** [comment]
Oh, I thought mdk is only checking for the filename. I think I have to bind the rc file with the manifest to my test app.

**Comment by wang-bin** [comment]
yes, for windows apps, you have to set company name and product name in rc. filename only is also supported. console.exe requires another key if check filename

**Comment by oomek** [comment]
![image](https://github.com/user-attachments/assets/f6af8659-9e63-402b-9309-b259eb043ab1)

**Comment by oomek** [comment]
> yes, for windows apps, you have to set company name and product name in rc. filename only is also supported. console.exe requires another key if check filename, i will generate for you later

On Windows we have 2 executables:
`attractplus.exe`
`attractplus-console.exe`
The later used for debugging by the frontend developers.

**Comment by wang-bin** [comment]
attractplus-console: 24964B0A7A7F7BBBB11619567A2D78EEBFE5B5547B1AA536A8C171DF134B4AC624FE15100C2B89D0DC07865B4245F7A168FA56ABF1FD3C79BB5AF69EC6831B02DB69B4F5858084444EE9E6A985D28711BDE5A6350F6ED757CBB501B3663867A54B90667F604E4F410456A2D308249584589E07D317E9B3615E7CCAF669891B02

attract-mode plus/attractmode.org: 01D7EB2A78C07ABA95CB8EA7CC15F9399891B80AD908D5A7DAFB013C295C2FDF1B8B61E96CB933F57A32C53E12F05A118730269E963C37B125B539D3EF19D80DFE2814D5873F85456A34715833EA06C69A91996BAD7CA7C6B98F2C5146384AFF6BE7149A43D847810853A64A7F9F3E74A95F54F9E8EBEDE79B0840EA833B406A

**Comment by oomek** [comment]
Thank you. The second key works for both win32 binaries.
