### ISSUE TITLE
qt android mdk播放mp3，切换音乐时大概率出现杂音

### ISSUE THREAD

**Issue by ken626014896** [wang-bin/mdk-sdk#227]
版本号
0.26.0 (git 0610342) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>

切换前我把声音设为0或者静音也不行，切换那一瞬间会兹的一声

**Comment by wang-bin** [comment]
最新包呢？只有mp3会出现？

**Comment by ken626014896** [comment]
测试了新版的没有
