### ISSUE TITLE
How to get a list of current active tracks

### ISSUE THREAD

**Issue by sbenmeddour** [wang-bin/mdk-sdk#230]
**Is your feature request related to a problem? Please describe.**
Even after reading documentation, I did not find how to get the current "active tracks"

**Describe the solution you'd like**
Is there any function / properties to get the active tracks (subtitles, audio, video) ? I no could you please explain the behavior of the player about the default track selection ? Will it be based on the first on the list / or from the device's Locale

Thank you !

**Comment by wang-bin** [comment]
No. Usually only setters, no getters, you have to store the values yourself. The default track is the first video/audio/subtitle track.
