### ISSUE TITLE
Set Bitrate

### ISSUE THREAD

**Issue by reddevil1310** [wang-bin/mdk-sdk#231]
Dear Mr.Wang,
I use mdk-sdk in qml application to stream rtsp links from ip camera. Is there a way to get/set bitrate for these streams? I tried switchBitrate but it returned failed.
Thank you!

**Comment by wang-bin** [comment]
get from player.mediaInfo().bit_rate after stream is loaded.  `switchBitrate` is just playing a new url. If you want to use rtsp command to change bit rate, it's not supported.
