### ISSUE TITLE
视频中间显示了一个二维码

### ISSUE THREAD

**Issue by RAVER0306** [wang-bin/mdk-sdk#232]
内容如下：
MDK SDK is outdated. Get a new free sdk from https://sourceforge.net/projects/mdk-sdk/files/nightly, or purchase a license. paypal: https://www.paypal.me/ibingow/500 more: https://www.qtav.org/donate.html

我如何去掉呢，我只是作为内部测试工具使用，每晚需要跑测试内容，二维码会影响测试结果

**Comment by wang-bin** [comment]
用最新的nightly包替换下
