### ISSUE TITLE
setMedia("avdevice://gdigrab:desktop")

### ISSUE THREAD

**Issue by zwh9527** [wang-bin/mdk-sdk#234]
您好，我设置setMedia("avdevice://gdigrab:desktop")显示桌面，然后想通过record方法推流，但是提示错误
[FFmpeg:flv] Video codec bmp not compatible with flv
Error avrt::avformat_write_header(fmtctx_, &dict) @420 D:\a\mdk-sdk\mdk-sdk\mdk\ffmpeg\plugin\FFmpegPacketIO.cpp: (0xffffffd8) Function not implemented

使用的sdk版本是0.29.0

**Comment by feiyangqingyun** [comment]
264 265才能推流

**Comment by zwh9527** [comment]
明白了
