### ISSUE TITLE
关于RTMP延迟问题

### ISSUE THREAD

**Issue by zero16832** [wang-bin/mdk-sdk#235]
[main.cpp.txt](https://github.com/user-attachments/files/16519057/main.cpp.txt)

![delay](https://github.com/user-attachments/assets/33e180b1-6f81-4901-8ade-c2eabb49617b)

上面代码是我根据你的案例编写的一个例子，在进行RTMP拉流的时候发现跟FFPLAY的延迟有1秒多的延迟(右侧是ffplay播放rtmp视频流，无参ffplay rtmp://xx.xx.xx.xx)，还能从哪里可以优化这个延迟呢？

**Comment by wang-bin** [comment]
`setBufferRange(0, 1000)` 减小缓冲大小。其他见 https://github.com/wang-bin/mdk-sdk/wiki/Typical-Usages#low-latency-live-stream
