### ISSUE TITLE
Customize subtitles apprearance

### ISSUE THREAD

**Issue by sbenmeddour** [wang-bin/mdk-sdk#241]
- ### **Is your feature request related to a problem? Please describe.**

> Is it possible to export an option to customize subtitles ? 
> I would like to apply a custom font size, and font/background color

- ### **Describe the solution you'd like**

> Exporting it through option/property or an API is fine

- ### **Describe alternatives you've considered**

> Tried to use a custom libass, failed

**Comment by wang-bin** [comment]
Done in the latest build. See https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#subtitle-properties

**Comment by sbenmeddour** [comment]
Thanks a lot, great job 👍
