### ISSUE TITLE
Multi audio channels support 

### ISSUE THREAD

**Issue by Vizalkar** [wang-bin/mdk-sdk#243]
Hi
We are implementing multi audio channels support in our software and as far as it seems, in MDK, videos that have more than 2 channels for the audio are mixed back into stereo. The external sound card that we use only plays through 2 of its outputs while it has 6 available and the source video contains 6 audio channels.

We are looking for a solution to solve that problem

Regards

**Comment by Vizalkar** [comment]
Is this by any mean already possible via FFmpeg options or anything for instance ?

On our schedule we need this feature for November so we are evaluating the alternative solutions as you may not have the time to implement it soon enough.
We are considering playing audio with a [miniaudio](https://github.com/mackron/miniaudio) player that we would sync to the video.
Is there any mechanism that already exist that would help us ensure av sync if we were to choose that solution ? 

Regards

**Comment by wang-bin** [comment]
which platform?

**Comment by Vizalkar** [comment]
Linux

**Comment by wang-bin** [comment]
I use alsa to play audio. supporting multiple channels is a little complicated in alsa. I will try pulseaudio

**Comment by wang-bin** [comment]
try the latest sdk and `setAudioBackends({"PulseAudio"})`

**Comment by Vizalkar** [comment]
Great thank you a lot ! Will try that tomorrow when I have the soundcard !

**Comment by wang-bin** [comment]
pulseaudio is the default in the latest sdk

**Comment by oomek** [comment]
Is there any particular reason why `setAudioBackends()` is undocumented?

**Comment by wang-bin** [comment]
> Is there any particular reason why `setAudioBackends()` is undocumented? My Arch Linux actually required the ALSA backend for the audio to work.

Forgot to add it. https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#void-setaudiobackendsconst-stdvectorstdstring-names
