### ISSUE TITLE
ffmpeg 7 support

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [wang-bin/mdk-sdk#246]
I remember mdk went to version 6 here https://github.com/wang-bin/mdk-sdk/commit/aaa10f1d05716d871847d0fb7a8ccc62392b6ad1 because of a problem related to avformat_find_stream_info and i think it got fixed in https://github.com/FFmpeg/FFmpeg/commit/a31106d84976bd28e56de35ee8085eebfc6c5e4d but i am not sure, just posting this incase it got really fixed and the migration can be done to keep ffmpeg version up to date.

**Comment by wang-bin** [comment]
ffmpeg7 is already used. the patch is https://github.com/wang-bin/avbuild/blob/master/patches%2Fmaster%2F0029-Revert-avutil-timestamp-change-precision-of-av_ts_ma.patch . we enabled debug log and found  printing a time string is very slow(a few seconds). we guess it's a miss compilation, but not sure

**Comment by abdelaziz-mahdy** [comment]
Oh okay then, I didn't know it was used, then this issue can be ignored then
