### ISSUE TITLE
video playing problem

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#248]
On linux one of my user can't play this video file. I have no problem on debian 12. (mdk 0.29)
Here is the logs + video file
[DSCF0077.zip](https://github.com/user-attachments/files/17110911/DSCF0077.zip)
[log_internalvideo.txt](https://github.com/user-attachments/files/17110912/log_internalvideo.txt)

**Comment by wang-bin** [comment]
use EGL + OpenGL ES2/3 can fix vaapi rendering issues. [The latest build](https://github.com/wang-bin/mdk-sdk/actions/runs/11012987206) is also a fix for this issue.
