### ISSUE TITLE
msys2 compatibility

### ISSUE THREAD

**Issue by oomek** [wang-bin/mdk-sdk#256]
Is there any chance to get a msys64 ucrt64 compatible libmdk, libffmpeg, and libc++?
All I can see in the releases are *.lib files for windows. msys2 expects *.a lib files

**Comment by wang-bin** [comment]
iirc mingw toolchain can use a dll's .lib directly. i tested with mingw gcc and clang before.

**Comment by wang-bin** [comment]
i tested mingw gcc again today and confirmed the same sdk works for all toolchains.
