### ISSUE TITLE
想询问一下部分接口传递的指针的生命周期问题

### ISSUE THREAD

**Issue by axojhf** [wang-bin/mdk-sdk#258]
**Is your feature request related to a problem? Please describe.**
setRenderAPI传递的指针是整个播放器实例存在周期内都会使用还是调用完这个接口后就不使用了

**Describe the solution you'd like**
如果大佬有精力和意愿，可否在一些涉及到指针传递（传入和返回，回调）的场合标注一下内部使用这个指针的生命周期

**Describe alternatives you've considered**

**Additional context**

**Comment by axojhf** [comment]
比如setRenderAPI

**Comment by wang-bin** [comment]
参数在这条语句结束时生命周期就可以结束了

**Comment by axojhf** [comment]
好的，暂时没有疑问了
