### ISSUE TITLE
Dead lock when playing

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#259]
with 0.30.1, i have a dead lock when trying to play this file

https://github.com/user-attachments/assets/fd8ee035-3fbb-424f-b07b-6d1af1694e33

**Comment by wang-bin** [comment]
Which platform? I need your log

**Comment by pierrexn** [comment]
Sorry, Windows and here is the logs...
[logs.txt](https://github.com/user-attachments/files/18052585/logs.txt)

**Comment by wang-bin** [comment]
try https://github.com/wang-bin/mdk-sdk/actions/runs/12229752213

please also check if #127 and #177 is not affected because i have no windows environment now

**Comment by pierrexn** [comment]
same lock, and i have a crash when playing #127 & #177

**Comment by wang-bin** [comment]
I guess the crash is in ffmpeg. download again and try again. show me the new log of this issue.

**Comment by wang-bin** [comment]
I can reproduce the issue in a VM with latest mft hevc extension, should be fixed in this build https://github.com/wang-bin/mdk-sdk/actions/runs/12258197922

**Comment by pierrexn** [comment]
It's fixed!

**Comment by pierrexn** [comment]
when do you think to release the fixed version?

**Comment by wang-bin** [comment]
not sure, maybe next month, i'm busy recently
