### ISSUE TITLE
Support for WEBVTT subtitles

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#262]
**Is your feature request related to a problem? Please describe.**
I got some .mkv files I want to play with embedded WEBVTT subtitles. 

In mediainfo they are properly detected:
```
Text #1
ID                                       : 4
Format                                   : S_TEXT/WEBVTT
Codec ID                                 : S_TEXT/WEBVTT
```

FFProbe returns
```
Unsupported codec with id 0 for input stream 4
```

which I guess is an issue here as I see in logs:
```
01:38:59.508: [FFmpeg:matroska,webm] Could not find codec parameters for stream 4 (Subtitle: none): unknown codec
...
01:39:02.042: ERROR! failed to setup subtitle decoder
```

Found this old ffmpeg ticket https://trac.ffmpeg.org/ticket/5641 that still seems to be the case here. Any way to handle it?

**Describe the solution you'd like**
Automatically handle decoding of S_TEXT/WEBVTT.

**Describe alternatives you've considered**
mpv handles these properly.

**Comment by wang-bin** [comment]
webvtt is supported. show me the full log.

**Comment by 23doors** [comment]
Well, to me it seems like webm webvtt is supported but mkv flavor is not.
Attaching logs.

[log.txt](https://github.com/user-attachments/files/18162737/log.txt)

**Comment by wang-bin** [comment]
i need a test file. maybr i can add a patch for ffmpeg

**Comment by 23doors** [comment]
Created an mkv from a random .vtt + bee.mp4. You can also create something similar with vtt subs that are in example of fvp. But anyway, it should be possible for you to reproduce it. 
[bee.zip](https://github.com/user-attachments/files/18163315/bee.zip)

**Comment by wang-bin** [comment]
I tried to add S_TEXT/WEBVTT in ffmpeg but it's not enough.

**Comment by 23doors** [comment]
According to https://stackoverflow.com/questions/61000319/ffmpeg-doesnt-detect-the-subtitle-format-webvtt-and-refuses-to-copy-it if you force decoder, it works. So I guess ffmpeg is simply not detecting it properly?

**Comment by wang-bin** [comment]
> According to https://stackoverflow.com/questions/61000319/ffmpeg-doesnt-detect-the-subtitle-format-webvtt-and-refuses-to-copy-it if you force decoder, it works. So I guess ffmpeg is simply not detecting it properly?

it does not work. no vtt packet read. we have to rewrite `matroska_parse_webvtt()`

**Comment by wang-bin** [comment]
try [this ffmpeg build when finished](https://github.com/wang-bin/avbuild/actions/runs/12376126169)

**Comment by 23doors** [comment]
Thanks! That seems to work. Only issue I noticed (which is probably not fully related to this one) is when I switch to HDR colorspace AFTER subtitles are presented at least once - then they look like this:
<img width="203" alt="image" src="https://github.com/user-attachments/assets/d2342e05-e0bb-4e81-9bc1-78756bd9a8db" />

Using white color above, no fancy colors. Getting bright red on HDR screen. And I can't seem to reset it (tried subtitles->0->1, changing color etc).

So:
1. open video
2. turn on hdr before any subs are visible
3. subs work fine

But:
1. open video
2. subs are starting to show
3. turn on hdr
4. subs are messed up like above

**Comment by wang-bin** [comment]
is video color and brightness correct? iirc flutter doest not support hdr, then if you set an hdr colorspace video color will be wrong. what about `./mdk
-sdk/bin/glfwplay -metal mkvfile`?

**Comment by 23doors** [comment]
I tested using simple swift application and swift-mdk - based on SPV. Color and brightness of image are correct, just subs are wrong IF and only IF hdr is turned on after subs start appearing.

Regarding `glfwplay -metal` - is there a way to manually turn hdr on/off? Cause if not, I won't be able to reproduce it there

**Comment by wang-bin** [comment]
press p to switch colorspace

**Comment by wang-bin** [comment]
> Yup, same issue there. Once subs appear they seem to be "bound" to that color space.
> 
> To reproduce:
> 
> 1. opened file (tested with HDR10 and DV files), switched colorspace to bt709
> 2. waited for some subs to appear
> 3. switched to bt2100
> 4. subs are messed up, image is fine
> 5. switch back to bt709 - subs are fine again
> 
> <img alt="image" width="186" src="https://private-user-images.githubusercontent.com/1051101/396711374-d73d75ca-8748-4225-90f4-b2aeed707995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDIxMDAsIm5iZiI6MTczNDUwMTgwMCwicGF0aCI6Ii8xMDUxMTAxLzM5NjcxMTM3NC1kNzNkNzVjYS04NzQ4LTQyMjUtOTBmNC1iMmFlZWQ3MDc5OTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMDYwMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZkMTdlYjFkZDFlMzA1NjAyMDQxMTBiZTVlNjdjMGQ5YTg2MzA4Zjg3MmU1MmQwNjEzN2Y3MWNmMzFiODNmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.U_vrcSVsZj4rcpfRv-9aE1Sl9YwbLGuXVuvb5FUskAw">

It's a new bug

**Comment by wang-bin** [comment]
patched ffmpeg is bundled in the latest sdk

**Comment by 23doors** [comment]
Thanks again! created a new bug https://github.com/wang-bin/mdk-sdk/issues/263
