### ISSUE TITLE
Subtitles seem to be bound to colorspace once displayed

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#263]
**Describe the bug**
Switching colorspace AFTER subtitles are displayed at least once causes all subtitles to be shown in completely wrong colors.

**To Reproduce**
To reproduce:

1. open file (tested with HDR10 and DV files), switch colorspace to bt709
2. wait for some subs to appear
3. switched to bt2100
4. subs are messed up and won't work in this colorspace anymore, image is fine

![image](https://github.com/user-attachments/assets/f3cee91b-f3bd-4196-9764-d1603a80227a)

**Expected behavior**
There should be a way to reset subtitles or they should map automatically between colorspaces.

**Environment:**
 - OS: macOS
 - GPU: M2 Pro

**Comment by wang-bin** [comment]
should be fixed in https://github.com/wang-bin/mdk-sdk/actions/runs/12396920897

can you test d3d11, d3d12 and vk renderer on windows? `glfwplay.exe -d3d11/-d3d12/-vk ...`

**Comment by 23doors** [comment]
Thanks!
Tested on mac -metal - works fine
Dont have a hdr display to test windows with but checked with switching color profiles anyway.
-d3d11/12 - works fine
-vk - subs work fine, app crashes after 5th press of P though (regardless if subs are visible or not).

Not sure how to check logs on windows though as it detaches when I start in cmd.exe

**Comment by wang-bin** [comment]
glfwplay.exe -logfile d3d11.log -d3d111 ..

or use mintty(used by msys2 and windoes git) to run commands

**Comment by 23doors** [comment]
Here is the logfile, file I tested with was DV HDR, maybe that's a factor
[vk.zip](https://github.com/user-attachments/files/18187026/vk.zip)

**Comment by wang-bin** [comment]
it's another bug in vk renderer
