### ISSUE TITLE
Set start position of media

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#264]
**Is your feature request related to a problem? Please describe.**
Seems I can set start position of next media, but when I just want 1 media without a next one - how should I do this?
load->seek of course works but results in unnecessary buffering at 0 position (between load and seek).

**Describe the solution you'd like**
Some API to set start position of playback before media is loaded.

**Comment by wang-bin** [comment]
prepare(position)

**Comment by 23doors** [comment]
Thanks, missed that!
