### ISSUE TITLE
More subtitle styling options (blur, shadow offset)

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#266]
**Describe the solution you'd like**
If possible, please add more subtitle styling, specifically:
sub outline blur
https://mpv.io/manual/master/#options-sub-blur

and ideally also shadow offset
https://mpv.io/manual/master/#options-sub-shadow-offset

It would also be nice to have sub-scale
https://mpv.io/manual/master/#options-sub-scale

I know you can use font-size but sub-scale works with .ass/.ssa subtitles as well.

**Comment by wang-bin** [comment]
- blur: setProperty("subtitle.blur", to_string(float value))
-  shadow offset:  setProperty("subtitle.shadow", to_string(float value))

sub-scale is not supported yet

**Comment by 23doors** [comment]
Thanks! Will test it

**Comment by 23doors** [comment]
One note though.
```
shadow offset: setProperty("subtitle.shadow", to_string(float value))
```

Isn't it shadow size and not offset?
```
"subtitle.shadow": shadow size, float value, default is "0". if < 0, will show background box if "box" value >=0
```

**Comment by 23doors** [comment]
subtitle.blur seem to have no effect, was it added recently?

**Comment by wang-bin** [comment]
"subtitle.scale" is added in the latest build https://github.com/wang-bin/mdk-sdk/actions/runs/12417887519

> ```
> shadow offset: setProperty("subtitle.shadow", to_string(float value))
> ```
> 
> Isn't it shadow size and not offset?

offset

> subtitle.blur seem to have no effect

Oops, no effect for me too

**Comment by wang-bin** [comment]
there is a bug in libass: https://github.com/libass/libass/pull/827

**Comment by 23doors** [comment]
I didnt test 0.17.3 myself but at least with 0.17.1 libass sub-blur worked properly in mpv, didnt try mdk with it yet. I guess dep.7z and in flutter it uses 0.17.3?

**Comment by wang-bin** [comment]
my implementation is different from mpv's. mpv also has the same issue when using other options

**Comment by 23doors** [comment]
As https://github.com/libass/libass/pull/827 was merged, would libass master lib work then with mdk? So subtitle.blur would work then?

**Comment by wang-bin** [comment]
try this https://github.com/wang-bin/mdk-sdk/actions/runs/12431146795

**Comment by 23doors** [comment]
Works great! one thing I notice though - blur is applied to both shadow and outline. But I guess this is libass behavior?

**Comment by wang-bin** [comment]
> Works great! one thing I notice though - blur is applied to both shadow and outline. But I guess this is libass behavior?

yes, same in mpv

**Comment by 23doors** [comment]
just wanted to confirm, closing then!
