### ISSUE TITLE
Stretch video frame

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#267]
Seems like there is no way to alter video frame so that subtitles are rendered below the video (while video keeps aspect ratio). E.g. video has aspect ratio 2.4, I want to display it on 1.77 aspect ratio display in such way that video is centered vertically and subs are visible on bottom of the screen. Very useful for fullscreen view, especially for widescreen videos where subs end up being very high on the screen.

Tried `setVideoSurfaceSize` with different aspect ratio - subs are still clipped by original aspect ratio. Tried `setAspectRatio` and it seems to have no effect here as well.

**Comment by wang-bin** [comment]
yes, currently subtitles are rendered in video frame region

**Comment by wang-bin** [comment]
use [the latest build](https://github.com/wang-bin/mdk-sdk/actions/runs/12462064854), and `setProperty("subtitle.size", "vo")`, then subtitles are rendered in video renderer size set by `setVideoSurfaceSize()`, for example in video widget size
