### ISSUE TITLE
Buggy seek when paused

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#270]
**Describe the bug**
Sending seek with flags fromNow(4) | inCache(1024) results in bufferrange being forgotten and results in re-buffering whole video.

**To Reproduce**
1. load video, set buffer range to say min=1000, max=30000, drop=false.
2. pause (important, doesnt seem to occur if playing)
3. wait for it to buffer
5. seek 10s with fromNow(4) | inCache(1024)
6. all good. seek again with same flags, should still be in cache
7. results in whole cache buffer to be dropped and it re-starts bufering until end of video (disregards previously set buffer range max). Can't fix it with re-setting buffer range as well.

**Expected behavior**

seek when paused should work the same as seek during playing.

**Environment:**
 - OS: macOS

**Comment by wang-bin** [comment]
`setBufferRange()` is for a internal packet queue, seeking out of `buffered()` range(i.e. InCache failed) will clear the queue. the name may be confusing. what you need is property "demux.buffer.ranges"

**Comment by 23doors** [comment]
Thing is, I am not seeking out of buffered() range. 

1. set buffer range to max=180s
2. open and pause. I see buffered() reaching 180s
3. while still paused - seek +10s (fromnow + incache)
4. works fine, I am at position 10s now, still within cached buffer.
5. seek +10s again (still paused)
6. now I see buffered() being 0 and rising until it reaches whole remaining video length

Also, in this case reader.buffering event is fired but never reaches 100% and I am in +buffering state until I hit play again.
But even when I hit play, whole video is now buffered().

**Comment by 23doors** [comment]
Downloaded newest build and now it seems I cant reproduce it anymore. Closing!

**Comment by 23doors** [comment]
Happening after all. Not all the time but happens especially often when you seek out of buffer a few times with fromNow(4) | inCache(1024) and negative value (seek backwards). It will then start buffering whole video and ignore buffer range max value.

**Comment by 23doors** [comment]
[log.txt](https://github.com/user-attachments/files/18263319/log.txt)

Here is the logfile. And I never get +buffered state until I unpause a few minutes later:
```
21:18:34.459: 455996467 player5063436352 onMediaStatus: MediaStatus(+loaded+prepared+buffering+end) => MediaStatus(+loaded+prepared+buffered+end)
21:18:34.459: ++++++++++++BUFFERING END++++++++++++
21:18:34.459: 455996467 player5063436352 onEvent: reader.buffering -  - 100
```

.buffer() now returns whole remaining video length.

**Comment by 23doors** [comment]
After seek I also often get a spam of:
```
Bad packet!!!
0x313d8a9b0 audio stream#1 EOF/EOS decoded. end: 1
0x313d8a9b0 audio stream#1 check loop range for EOS. dec_state.seeking: 0. end: 1, nb_decoded:223
EOS audio frame of track 0
```

not sure if that's related

**Comment by 23doors** [comment]
Happens with other seek flags (including from0 accurate seek) as well - but only when video is paused.
And when I see buffered() raising and I unpause - it will stop rising. So buffers seem to be sometimes improperly processed here but only when paused.

**Comment by 23doors** [comment]
One more weird behavior that could help find the reason for it.
This only occurs when paused: sometimes small seek (e.g. 5 s backwards) will succeed and report time X. But player.position will keep returning old time. Maybe whole thing is related to subtitle streams as well.

```
00:58:34.700: default FrameReader 0x1455b18c0 callbacks 0, seeking 0 flag 0, seekComplete#5 @608983
00:58:34.745: 0x1455b18c0 #5/5 subtitle seek_done: 1, seek_wait_frame_: -1/2
00:58:34.745: 0x1455b18c0 subtitle stream#4 sending 1 invalid AOT frame @612.237000s. seeking: 0
00:58:34.745: 0x147ad0c00 1st subtitle frame @612.237000
00:58:34.745: 0x147ad0c00 seek end subtitle frame @612.237000 seek_pos_: -1
00:58:34.747: default FrameReader0x1455b18c0 #5 seekComplete 612237
00:58:34.747: default 0x1455b18c0 FrameReader::update MediaStatus 0X114=>0X114
00:58:34.747: default FrameReader 0x1455b18c0 callbacks 0, seeking: 0, seekComplete#5 not found @612237
```

**Comment by 23doors** [comment]
@wang-bin part of it seem to be fixed. But I'm still getting sometimes a bug from my comment above.

```
13:43:27.489: seek_drop_non_video_: 395023 ms, seek_wait_frame_: 0...
13:43:27.489: 0x32119b160 video stream#0 AOT frame is sent
13:43:27.489: 0x32119b160 video stream#0 is seeking #11... got flush pkt. flush decoder and  drop frames until seek target 395.0230s...
13:43:27.489: 0x32119b160 subtitle stream#4 AOT frame is sent
13:43:27.489: 0x32119b160 subtitle stream#4 is seeking #11... got flush pkt. flush decoder and  drop frames until seek target 395.0230s...
13:43:27.489: invalid subtitle frame @-1.000000
13:43:27.490: invalid video frame @-1.000000
13:43:27.520: 0x32119b160 #11/11 subtitle seek_done: 1, seek_wait_frame_: 0/2
13:43:27.520: 0x32119b160 subtitle stream#4 sending 1 invalid AOT frame @396.188000s. seeking: 0
13:43:27.520: 0x127916c00 1st subtitle frame @396.188000
13:43:27.520: 0x127916c00 seek end subtitle frame @396.188000 seek_pos_: 395027
0x127916c00>395027 00:06:35.0/00:26:25 cache 0v 1.6s/922KB 51634KB/s |-5012|>4ms update 19989.3ms 0.1fps draw 0/2 +0ms
13:43:27.526: 0x32119b160 #11/11 video seek_done: 1, seek_wait_frame_: 0/0
13:43:27.526: 0x32119b160 video stream#0 sending 1 invalid AOT frame @395.020000s. seeking: 0
13:43:27.526: VideoRenderer clear buffered frames
13:43:27.526: 0-track seek end video frame @395.020000 seek_pos_: 395027
13:43:27.526: seeking media's position is 395027=====
13:43:27.528: default FrameReader0x32119b160 #11 seekComplete 395020
13:43:27.528: default 0x32119b160 FrameReader::update MediaStatus 0X124=>0X124
```

Here I am seeking to 395027 (5s backwards with FromStart|InCache), seek returns that seek to 395020 completed. But player.position is actually returning old 400027 position all the time. Retrying same seek a few times will yield same results. When I unpause I get 5 seconds of stutter, then it resumes normally.

Seems like it affects only some portions of video, e.g. I can seek through most of it normally, but some parts seem "stuck".

**Comment by wang-bin** [comment]
> Here I am seeking to 395027 (5s backwards with FromStart|InCache), seek returns that seek to 395020 completed. But player.position is actually returning old 400027 position all the time. Retrying same seek a few times will yield same results. When I unpause I get 5 seconds of stutter, then it resumes normally.

no audio decoded after seek. can you share this video?

**Comment by 23doors** [comment]
To be honest it occurs pretty much in every video.

For example:
https://archive.org/download/BigBuckBunnyFULLHD60FPS/Big%20Buck%20Bunny%20-%20FULL%20HD%2060FPS.mp4

Paused, seeked a few times. And started to seek backwards 5s (using FromStart|InCache here).
Added logs to see what seek and what player.position returns.

And after a few seeks got:
```
Seek to 0:04:46.497000 done. Returns: 286483, player position: 286483
Seek to 0:04:57.050000 done. Returns: 297033, player position: 302036
... retrying ...
Seek to 0:04:57.036000 done. Returns: 297033, player position: 302036
... retrying ...
Seek to 0:04:57.036000 done. Returns: 297033, player position: 302036
```

So being at position 302036 I seek to 297036, seek returns and says it succeded at 297033. But player.position stays at 302036.

mdk logs when this happens:
```
18:16:11.043: seeking media's position is 297036=====
18:16:11.043: 0x13e869a10 #5/5 video seek_done: 1, seek_wait_frame_: 0/0
18:16:11.043: 0x13e869a10 video stream#0 sending 1 invalid AOT frame @297.033333s. seeking: 0
18:16:11.043: VideoRenderer clear buffered frames
18:16:11.043: 0-track seek end video frame @297.033333 seek_pos_: 297036
18:16:11.043: seeking media's position is 297036=====
18:16:11.043: default FrameReader0x13e869a10 #5 seekComplete 297033
18:16:11.043: default 0x13e869a10 FrameReader::update MediaStatus 0X124=>0X124
18:16:11.049: default FrameReader 0x13e869a10 callbacks 0, seeking 0 flag 0, seekComplete#5 @297033
```

player.position never changes though.

Now when I resume - player.position suddenly goes to somewhere around 297033 and I get a 1-5s of stutter. Then it resumes normal playback.

**Comment by 23doors** [comment]
Another weird issue with seek. Not sure if related.

This occurs pretty rarely and I got no way of reproducing it. Used same test video I used 100 times already and it occured 2-3 times on random.
[log.txt](https://github.com/user-attachments/files/18266945/log.txt)

Wasn't paused when this happened, just normally playing. I seek to same time I always seek during tests. 
And I end up being flooded with
```
18:25:02.105: 0x147f79400 audio stream#1 EOF/EOS decoded. end: 1
18:25:02.105: 0x147f79400 audio stream#1 check loop range for EOS. dec_state.seeking: 0. end: 1, nb_decoded:820
18:25:02.105: EOS audio frame of track 0
18:25:02.105: Bad packet!!!
```

Video keeps playing but I get buffering state all the time. What's worrying - even when I stop player, it doesn't go away but I keep getting these in logs.

**Comment by 23doors** [comment]
@wang-bin should I reopen a new bug for it or maybe could you reopen this one?

**Comment by wang-bin** [comment]
yes, version 0.25.0 works

**Comment by wang-bin** [comment]
try https://github.com/wang-bin/mdk-sdk/actions/runs/12536363753

**Comment by 23doors** [comment]
So far so good! Will test a bit more and report back if needed, but looks like you nailed it.

**Comment by 23doors** [comment]
Only issue so far is that now `demux.buffer.ranges` seems to mishandle buffer time merges? Didn't test it before that much so not 100% sure it's a regression.

demux.buffer.ranges=8, buffer range min=1s, max=180s.

After few seeks I end up with

buffer time ranges returning:
```
(start: 0:23:27.740000, end: 0:26:34.144000), 
(start: 0:24:31.011000, end: 0:24:54.368000), 
(start: 0:24:34.348000, end: 0:27:39.232000), 
(start: 0:00:00.000000, end: 0:22:32.256000), 
(start: 0:08:51.197000, end: 0:11:52.896000),
```

So weirdly I end up with 1 big 22s buffer and they dont seem to get merged?

Buffered time range seem to expand indefinitely if I dont seek.

Looks like it's pretty recent addition and I can't find any docs for it, but where are those buffers stored? On disk? If so, where? And when are they purged? Would be useful to document it so that app dev knows what to clear on crash.

**Comment by wang-bin** [comment]
there are some known bugs about ranges. i have to rewrite it. 

> Looks like it's pretty recent addition and I can't find any docs for it, but where are those buffers stored? On disk? If so, where? And when are they purged? Would be useful to document it so that app dev knows what to clear on crash.

in memory. a least recent range will be dropped to ensure ranges count <= the value set by user.
