### ISSUE TITLE
Add a way to re-render current frame after resize when paused

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#271]
**Is your feature request related to a problem? Please describe.**
Unable to redraw changed frame size after changing frame size with setVideoSurfaceSize AND state is Paused.

**Describe the solution you'd like**
Provide either an API to forcibly redraw frame with new size or automatically handle it when setVideoSurfaceSize is called.

**Comment by 23doors** [comment]
Could also be useful to see live changes of subtitle settings when paused.

**Comment by wang-bin** [comment]
How to reproduce? video will redraw after setVideoSurfaceSize.

> Could also be useful to see live changes of subtitle settings when paused.

this can be improved

**Comment by wang-bin** [comment]
try https://github.com/wang-bin/mdk-sdk/actions/runs/12485038573

**Comment by 23doors** [comment]
> How to reproduce? video will redraw after setVideoSurfaceSize.

You're right, my bad. Turns out my issue was that metal view currentDrawable wasn't resized at that time and I was only drawing in setRenderCallback. 

Tried latest build, subs seem to be redrawn properly when surface is resized.

But it would also be useful to redraw current frame when any `subtitle.*` property changes. E.g. 
1. subs are showing, pause
2. change `subtitle.scale`
3. would be nice to have current frame re-rendered with new subtitle.scale. I guess it would be useful for other `subtitle.*` properties as well for easier sub styling.

**Comment by wang-bin** [comment]
try the latest build

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-sdk/actions/runs/12492131422 this build will redraw subtitle if you set "sutitle.*", no additional code required

**Comment by 23doors** [comment]
Seems to work great, thanks! Closing
