### ISSUE TITLE
Subtitle styling for default track 0 is only applied after switching tracks

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#272]
**To Reproduce**
1. load a mkv which has srt subtitles embedded. It will be shown as by default active subtitle tracks are `[0]`
2. setup some subtitle styling, `subtitle.font`, `subtitle.shadow`, `subtitle.border` and such
3. styling is not applied **until** `setActiveTracks` is called with some different track e.g. `[]` and then switched back to `[0]`

**Expected behavior**
Styling should work for default track without the need to switch and switch back.

**Environment:**
 - OS: macOS m1

**Workaround**
After create player, one can:
`setActiveTracks` with `[]` for subtitles. Now you can open media, set subtitles styling and enable `[0]` track again.

But I guess it shouldn't be needed?

**Comment by wang-bin** [comment]
playing or paused?

**Comment by 23doors** [comment]
Doesnt seem to matter in this case

**Comment by wang-bin** [comment]
I can't reproduce your issue. I use modified glfwplay to test. Try to set env var `ASS_REGIONS_DEBUG=1` and show me your log.

**Comment by 23doors** [comment]
I tried latest build and I can't reproduce it anymore. I guess https://github.com/wang-bin/mdk-sdk/issues/271 fixed it for me, thanks!
