### ISSUE TITLE
Frame-accurate seek in both directions

### ISSUE THREAD

**Issue by AdrianEddy** [wang-bin/mdk-sdk#28]
For timeline preview, it is useful to have an accurate seek to any frame, in both forward and backward direction. Currently MDK seems to support only forward frame seek, but looks like it's just playing the media until the desired frame is reached.

The way it works in other players is to seek to the nearest keyframe (last keyframe before the desired target), then seek forward frame by frame (but I don't see a reason to render frames while seeking, it should happen internally).

**Comment by wang-bin** [comment]
Do you mean step to the next/previous 1 frame? It's still developing. But for timeline preview, accurate seeking to a given time is enough, via `seek(msec, SeekFlag::FromStart)` see example https://github.com/wang-bin/mdk-examples/blob/master/Qt/qmdkplay.cpp#L23

**Comment by AdrianEddy** [comment]
> Do you mean step to the next/previous 1 frame? 

Yes exactly, next 1 frame works fine, but previous doesn't and it will be useful too. Also seek to arbitrary exact frame will be useful, so for example I can call

`seek(1234, SeekFlag::FromStart | SeekFlag::Frame)`
and then for example 
`seek(976, SeekFlag::FromStart | SeekFlag::Frame)`

**Comment by wang-bin** [comment]
> > Do you mean step to the next/previous 1 frame?
> 
> Yes exactly, next 1 frame works fine, but previous doesn't and it will be useful too. Also seek to arbitrary exact frame will be useful, so for example I can call
> 
> `seek(1234, SeekFlag::FromStart | SeekFlag::Frame)`
> and then for example
> `seek(976, SeekFlag::FromStart | SeekFlag::Frame)`

If frame rate is known, seek forward a large number of frames and seek to by time are equivalent. If frame rate is unknown, it's impossible to fast seek by frame, you must decode frames 1 by 1(it's supported now) and which will be slow. So seeking to arbitrary exact frame is not useful.

**Comment by AdrianEddy** [comment]
> If frame rate is known, seek forward a large number of frames and seek to by time are equivalent.

You're right, this seems to work correctly if I calculate the timestamp from frame and frame rate and seek to timestamp.

I'll close this issue, but still it would be nice for the user of the SDK if that happens internally when passing `SeekFlag::Frame`.
Maybe something like this could be implemented in the SDK for `SeekFlag::FromStart | SeekFlag::Frame` case, if frame rate is known
```cpp
auto delta = targetFrame - currentFrame;
if (delta > 0 && delta < 5) {
    seek(delta, SeekFlag::FromNow | SeekFlag::Frame);
} else {
    double timestampMs = (targetFrame / codec.frame_rate) * 1000.0;
    seek(timestampMs, SeekFlag::FromStart);
}
```

**Comment by wang-bin** [comment]
Try the latest build. Backward seeking works. the first parameter `pos` can be -1, -2, -3 etc. frame rate must be known.
