### ISSUE TITLE
请问在qt android和pc上播放不了rtsp是为啥的

### ISSUE THREAD

**Issue by ken626014896** [wang-bin/mdk-sdk#29]
MDK 0.11.1 (git d71c060) - Multimedia Development Kit. Copyright (c) 2016-2021 WangBin(QtAV author) <wbsecg1 at gmail.com>Build for: Windows0x0600 x86_64; Clang12.0.1 MSVC1911; MSVCRT14.28.29333.0/msvcp140.dll; 02:13:03 May 17 2021

MediaStatus状态一直是loading,本地视频和http的正常播放

**Comment by wang-bin** [comment]
log发下。url后面加`?mdkopt=avformat&fflags=+nobuffer&analyzeduration=10000&probesize=1000`可以加快rtsp起播速度
