### ISSUE TITLE
No Signals in mdk::Player

### ISSUE THREAD

**Issue by PeterAkakpo** [wang-bin/mdk-sdk#3]
There are not signals to connect to in the Player class. there are onMediaStatusChanged and onStateChanged but they are not displayed as signals. connecting to them give error suggesting that 
Q_OBJECT is not in the Player class. ("qobject.h:249: error: C2338: No Q_OBJECT in the class with the signal"

**Comment by wang-bin** [comment]
you have to emit signals yourself in the callback. see https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/master/mediaplayercontrol.cpp#L44  https://github.com/wang-bin/qtmultimedia-plugins-mdk/blob/master/mediaplayercontrol.cpp#L47

**Comment by PeterAkakpo** [comment]
i have tried the following from the above link, but its still not working

_player->onStateChanged([this](State value){
        Q_EMIT stateChanged(value);
    });
    _player->onMediaStatusChanged([this](MediaStatus value){
        Q_EMIT mediaStatusChanged(value);
        return true;
    });

**Comment by wang-bin** [comment]
how do you connect signals?

**Comment by PeterAkakpo** [comment]
i tried this first but it didn't work
**connect(player,&MediaPlayer::mediaStatusChanged,this,&MainWindow::mediaStatusChanged);**

then i tried this, it also didn't work   **connect(player,SIGNAL(mediaStatusChanged()),this,SLOT(mediaStatusChanged()),Qt::DirectConnection);**

**Comment by wang-bin** [comment]
> connect(player,&MediaPlayer::mediaStatusChanged,this,&MainWindow::mediaStatusChanged);

It's a queued connection, signal parameter type `MediaStatus` must be known to qt metatype system.

```cpp
    Q_DECLARE_METATYPE(mdk::MediaStatus) // declare in global scope

   qRegisterMetaType<MediaStatus>(); // in a function
````

>connect(player,SIGNAL(mediaStatusChanged()),this,SLOT(mediaStatusChanged()),Qt::DirectConnection);

forgot signal parameter? qRegisterMetaType too.


other options can be
```cpp
    connect(this, &QMDKWindow::mediaStatusChanged, []{});
```
