### ISSUE TITLE
qio: Url or protocol is not supported by MediaIO (Qt)

### ISSUE THREAD

**Issue by ChrisThis** [wang-bin/mdk-sdk#31]
Hallo, 
i try to use Qt QIODevice., but protocol is not supported:

```
     iodev = dynamic_cast<QIODevice*>(&lfh);
     _player.setMedia(QString("qio:%1").arg(qintptr(iodev)).toUtf8().constData());
```
log:

```
qio: Url or protocol is not supported by MediaIO FFmpeg
Try to use default MediaIO
```

when i try to compile the Qt plugin, compiler said: "mdk/MediaIO.h" not found.
I will try to handle the byte stream for the mdk. In QtAV i can to this with QIODevice, but i need also a solution for the mdk.

Thanks in advance.

**Comment by wang-bin** [comment]
it's a private header for now. if can send you via email if you want.
