### ISSUE TITLE
播放了下m3u8的地址 发现与web端的播放器相比 播两下就会卡顿一下

### ISSUE THREAD

**Issue by lsclh** [wang-bin/mdk-sdk#32]
这个是由于缓冲原因还是什么原因 还是缺少了哪些参数设置 文档里没找到 新手问问题可能有点蠢 请见谅....

**Comment by wang-bin** [comment]
缓冲问题，setBufferRange第前两个参数改下，第一个是缓冲到指定数据量开始播放，第二个是最多缓冲多少，可以设成INT64_MAX就是播放时会尽可能缓冲多点
