### ISSUE TITLE
Is there a chance there will be a Ubuntu PPA containing the MDK library?

### ISSUE THREAD

**Issue by paul-h** [wang-bin/mdk-sdk#35]
I've used QtAV in an open source project and used the PPA to install the required libraries and even donated to keep it going but unfortunately it looks like development has been abandoned :(

I believe the MDK is it's replacement but I don't see any mention of a PPA for it.  Since the MDK is not open source I'm guessing you can't create a PPA for it? Are there any open source projects using the MDK? How do/would they use it in an open source project and still allow there project to be packaged for use in Ubuntu?

**Comment by wang-bin** [comment]
ppa does not support pre-built binary packages. But you can try to add a script to download the sdk. https://github.com/wangwenx190/QtMediaPlayer this is an open source project, but no ppa
