### ISSUE TITLE
REQUEST: Static linkage?

### ISSUE THREAD

**Issue by dr3mro** [wang-bin/mdk-sdk#36]
Thank you for your effort 
Q?
How to static linkage with Qt on windows ?
Thanks

**Comment by wang-bin** [comment]
the sdk provides dynamic library only. you can still use it in your static linked apps. same as linking against dynamic system libraries.

**Comment by dr3mro** [comment]
Thank you for your response
I am already doing that but could you please consider providing static
linked libs or at least provide a guide on how to
Thank you

**Comment by wang-bin** [comment]
no. it requires the same toolchain and stl to link your app. i only build 1 binary sdk for each platform. a dynamic library can be used by all toolchains, but static can't.

**Comment by dr3mro** [comment]
Ok, thanks for the clarification. But can I build it my self?  How to build
it please?

**Comment by wang-bin** [comment]
you can't. no source code

**Comment by wang-bin** [comment]
you can't. no source code

**Comment by dr3mro** [comment]
Ok, thanks for the reply.
