### ISSUE TITLE
Cannot play a 32bpp MOV file

### ISSUE THREAD

**Issue by julitobatata** [wang-bin/mdk-sdk#37]
I can successfully play a 32bit MOV file (alpha channel) using QtAV. But using MDK-SDK I have problems, the system simply shuts down. Can you try to find out the problem? It is very important for my project to be able to play videos with alpha channel. I am working in Windows 10 64bits and using Visual Studio 2019 IDE.
[teste.zip](https://github.com/wang-bin/mdk-sdk/files/6919105/teste.zip)

**Comment by julitobatata** [comment]
In the "simple" example I put first the url only, crash is the result. Specifying decoder (-c:v FFmepeg or others) the sound works, but image don´t be showed. With only RGB video files I don´t find any issues.

**Comment by wang-bin** [comment]
Because the ffmpeg-*.dll in mdk-sdk is a lite version, many codecs are disabled, for example "qtrle" in your test video. You can use a prebuilt ffmpeg with this codec enabled, for example download the package whose name does not ends with "-lite", and replace ffmpeg-*.dll.

**Comment by julitobatata** [comment]
Thank you very much Wang, I figure you are talking about "avbuild" package in your repository, I will try to compile using your tool following your recomendation.
Then I will try to use your library to render into my QOpenGLFramebufferObject running in a secondary thread. Still I don't imagine how can I implement this.

**Comment by wang-bin** [comment]
It's simple. Look at this example https://github.com/wang-bin/mdk-examples/blob/master/Qt/qml/mdkplayer.cpp

What you need to do is calling `setRenderCallback` to emit a signal and queued connect to your fbo thread, `renderVideo()` in the slot. And don't forget `setVideoSurfaceSize()` with fbo size in fbo thread.
