### ISSUE TITLE
快速切换视频文件播放时会有一定几率崩溃

### ISSUE THREAD

**Issue by ZhouYing-bit** [wang-bin/mdk-sdk#39]
### MDK版本

MDK 0.12.0 (git 013f88e) - Multimedia Development Kit. Copyright (c) 2016-2021 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Windows0x0600 x86_64; MSVC1929; MSVCRT14.29.30038.1/msvcp140.dll; 01:28:25 Jun 28 2021

### 运行环境：
win10+qt 5.15.2 + msvc2019

### **这是崩溃时的dump信息**
![image](https://user-images.githubusercontent.com/13702789/130386468-730c4620-2455-44d8-b61a-90938a6003f0.png)

我在UI主线程通过按钮不断的调用以下片段代码，用于切换不同的视频文件播放，以此来实现上一部、下一部功能
![image](https://user-images.githubusercontent.com/13702789/130386693-1df77831-6ba4-4e8a-bb87-163f8bed2b41.png)

在回调函数中通过发送信号方式获取播放器的播放状态，当播放状态 state == 1 时，调用player_->position()方法获取视频总时长，此时出现崩溃问题；
![image](https://user-images.githubusercontent.com/13702789/130386839-8f4f5291-bdb8-4e4b-918d-c13f900e56c6.png)

**Comment by wang-bin** [comment]
信号槽要direct connect
