### ISSUE TITLE
Zero-Copy rendering on SFML RenderTexture

### ISSUE THREAD

**Issue by oomek** [wang-bin/mdk-sdk#4]
Can we achieve in the current state of the library a zero-copy decoding on a SFML RenderTexture. If so, would you be able to provide an example?

**Comment by wang-bin** [comment]
The same as sw decoder rendering. I will write an example tomorrow.

**Comment by wang-bin** [comment]
https://github.com/wang-bin/mdk-examples/blob/master/SFML/sfmltexture.cpp#L61

Use `-c:v` option to enable hardware decoders. Supported decoders can be found in https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#setdecodernamesconst-stdvectorstdstring-names

**Comment by oomek** [comment]
There is some issue with rendering using renderVideo() call of 30fps videos on 60Hz refresh rate. I've noticed quite severe stuttering. This can be overcome by calling renderVideo() every second frame.
