### ISSUE TITLE
MDK 0.13.0 does't work on macOS 10.x

### ISSUE THREAD

**Issue by AdrianEddy** [wang-bin/mdk-sdk#46]
Was there a reason to bump the minimum supported macOS version to 11+? 
MDK sdk v0.13.0 crashes on macOS 10.x with the following message:
```Dyld Error Message:
  Symbol not found: _VTRegisterSupplementalVideoDecoderIfAvailable
  Referenced from: /Frameworks/mdk.framework/Versions/A/mdk (which was built for Mac OS X 11.6)
```

MDK sdk v0.12.0 works

**Comment by wang-bin** [comment]
No. It should be a weak symbol. I don't know what happens to the compiler

**Comment by wang-bin** [comment]
the latest x86_64 sdk is ok. other packages will be available tomorrow

**Comment by AdrianEddy** [comment]
Thank you! Greatly appreciated 👍
