### ISSUE TITLE
Question about GPL compatibility

### ISSUE THREAD

**Issue by JeromeMartinez** [wang-bin/mdk-sdk#5]
I would like to use mdk-sdk in a project which could be released with a GPL license (it currently has a more permissive license).

I read:

> Free for GPL softwares

Great!
But for that, I need that mdk-sdk source code is provided with GPL license, as the GPL license explicitly stipulates that the whole software must have its source code provided on request and with a license compatible with the GPL (it is actually purpose of GPL: forbidding the usage of GPL code with code having a license incompatible with GPL).

If my code is GPL, mdk-sdk must be compatible with it in order to be able to distribute my software. I checked the packages on Sourceforge, I saw the license “Free for GPL softwares” but without any source code, so mdk-sdk is free for GPL softwares but incompatible with GPL softwares, at least with the public packages I found.

Just to be clear before I ask for a key to the developer: will the source code with a GPL compatible license be delivered with the key? If not, how is it expected that mdk-sdk is compatible with the constraint requested for having the right to use mdk-sdk for free?

**Comment by wang-bin** [comment]
No source code. My words were not accurate: the binary sdk can be free, but under the restriction of some license. It's GPL incompatible and your binary will not be redistributable under GPL, but end users can build your software with this sdk themselves. Maybe you can use dlopen and do not include the library binary in your distribution.
Some examples: obs-studio and ffmpeg both have decklink module, obs even provides decklink plugin in it's installer.

**Comment by JeromeMartinez** [comment]
Thank you for the explanation, I understand better now.
I note that an optional input plugin is not exactly same as a part of an UI, but I get the idea about the technical implementation.
