### ISSUE TITLE
Low performance on playing Video stream

### ISSUE THREAD

**Issue by Dizgah** [wang-bin/mdk-sdk#50]
Hi and thank you for developing this awesome tool.

I've tried to check the performance of this library on playing network video stream and the spec are based on below:

1. mdk-sdk Version 0.14.0
2. video streamer: IP webcam over android on local wifi network
3. simplePlayer example based on Qt widget 5.12.11
4. Visual Studio 2019 (VS2017 C++ compiler) 
5. trying all video decoder provided and supported in OS ( Win 10 64 bit)

Although mdk is really easy to use and out of headache tool but unfortunately from performance point of view it was not efficient enough at least comparing to the VLC player.
VLC was playing videos about 2 seconds faster than simplePlayer with fewer Lags and smoother play.
Then is there any performance option I had ignored or I can do to increase performance?

**Comment by wang-bin** [comment]
what kind of stream? rtsp?

**Comment by wang-bin** [comment]
you can try to add options at the end of url, the result can be better than vlc. see https://github.com/wang-bin/mdk-sdk/wiki/Troubleshooting#mosaic-and-high-latency-in-rtsp
