### ISSUE TITLE
Qt5 crash in MediaInfo.h -> mdk::from_c

### ISSUE THREAD

**Issue by cristiandragusanu** [wang-bin/mdk-sdk#51]
Hello,

I'm experiencing a crash when loading some particular video files (all produced by the same device). I'm using Qt5 with MinGW 8.1.0 64bit on Windows 10 64bit, and MDK 0.14.0. It doesn't matter if it's a release or debug build.

The crash always happens when loading the file (including when calling ```prepare()```), as a Segmentation Fault at the same line, in MediaInfo.h, in the function from_c:

![image](https://user-images.githubusercontent.com/49856105/156438311-95718f16-f61d-49f7-8eec-d0a8f4612d73.png)

The app works with no problems with many other videos, in different formats, containers, sizes and so on.
It seems to crash with a particular format, but I can't pinpoint the exact cause.

The faulty files are MP4 files, HVC1 codec, 30fps, ~22mbps, AAC sound. Let's call them type A.
Other files, including other MP4 files, other HVC1 files and so on, work fine. Let's call them type B.

If I play a Type A file first, then I can play any other file (Type A or B) without problems.
If I play a Type B file first, then playing other Type B files works fine. But playing Type A files leads to the above crash.

Sometimes, in very rare cases, it doesn't crash, but seems to enter an infinite loop or deadlock somewhere in the same code.

I tried using ```setDecoders(MediaType::Video, { ... })``` to set different decoders, there's no difference at all. Tried disabling different tracks (Audio, Video, Subtitle), no changes. 

I don't have any more ideas. Please let me know how I can help to fix this issue. If needed, I can provide a video sample, but I'd prefer to provide it on a private channel, not to post it publicly.

Thanks!

**Comment by wang-bin** [comment]
a sample video will be helpful. you can share it via google drive, one drive etc.

**Comment by cristiandragusanu** [comment]
I've narrowed it down a bit.

It's not related to loading/playback itself, that seems to work fine on its own. It's about when MediaInfo really becomes available. According to documentation, when ```mediaStatus``` contains ```MediaStatus::Loaded```, then ```mediaInfo``` should be available. But apparently for this set of files, sometimes it's not available at that point.

I've attached an archive with 2 videos (A = problematic file, B = ok file) and a sample code based on your qmdkqmlplay example.

In your example I've added a callback for ```mediaStatusChanged```, and when ```MediaStatus::Loaded``` is detected it emits a ```mediaLoaded``` signal which should update the ```duration``` of the current video in the QML UI.
The app starts with the B (ok) file, and there's a button to start file A (problematic). The button also shows the duration as text.

For some reason, in this simple example, sometimes it works fine. But most of the times, it fails at the same point in MediaInfo.h. Usually if you click the button as soon as you can (to change to the 2nd video very soon), it should crash. It looks like some timing/sync issue somewhere.

Please let me know as soon as you download the archive, so I can remove it. Thanks!

https://drive.google.com/file/d/1LGvzLTpPJYY-GY5EMci3sGTxk2q8zdhY/view?usp=sharing

Please let me know if I can help with something else about this.

**Comment by wang-bin** [comment]
Try the lastest build

**Comment by cristiandragusanu** [comment]
It seems to have fixed it. Thank you! :)
