### ISSUE TITLE
qml解码多路视频发现内存一直上涨问题

### ISSUE THREAD

**Issue by ken626014896** [wang-bin/mdk-sdk#54]
sdk版本是三月份的
使用的是例程里面qml例子，解码45路rtspl流 分辨率都是500*360
![微信图片_20220401111837](https://user-images.githubusercontent.com/38373469/161189033-d8da119f-4b7d-489b-9380-12f4ac751a66.png)

![微信图片_20220401111945](https://user-images.githubusercontent.com/38373469/161189069-c7513522-f517-464a-8a27-6dc2400d0ed1.png)
从1512涨到了1923
请问我这边是不是哪里忘记设置了

**Comment by wang-bin** [comment]
有没有继续涨？没有的话就是正常

**Comment by ken626014896** [comment]
继续涨

**Comment by wang-bin** [comment]
给个测试代码

**Comment by ken626014896** [comment]
链接：https://pan.baidu.com/s/1k34fwsOwBdR2TziGCMrR7A  提取码：3qox
流是rtsp流，我这边暂时无法导到外网

**Comment by ken626014896** [comment]
请问有什么解决办法了吗0.0

**Comment by wang-bin** [comment]
本地视频是正常的，rtsp我测了下vlc也是一直涨，不确定是什么原因。setFrameRate这行可以去掉, DXVA不推荐用

**Comment by wang-bin** [comment]
先关了这个，放到 https://github.com/wang-bin/mdk-sdk/issues/54 跟踪
