### ISSUE TITLE
”PlaylistAsOne” scenario - black screen when seeking while paused

### ISSUE THREAD

**Issue by alexcristd** [wang-bin/mdk-sdk#55]
Hello,

I'm trying to implement a scenario similar to the PlaylistAsOne example, using Qt5 with MinGW 8.1.0 64bit on Windows 10 64bit, and MDK 0.14.2.

I didn't try compile the example itself (due to completely different dependencies than what I need), but the already built application from the SDK works perfectly, both when seeking while playing and while pause. FYI: the example cpp seems to have some missing code between lines 173-175. Can you please check that?

My issue: I need to seek through multiple files as a continuous item. If I seek while playing, everything is perfect. If I pause the playback and start seeking, everything works fine as long as I seek in the same file. When I click somewhere where the file should change, the seek happens, but **the video screen remains black**. If I press "play", it starts playing from the correct position, so **the actual seek went fine, it just doesn't render the frame while pause**. I can't figure out what I'm missing...

Given the example code:
``` c++
    player->setNextMedia(nullptr);
    player->set(State::Stopped);
    player->waitFor(State::Stopped);
    player->setMedia(it->url.data());
    player->prepare(offset);
    player->set(State::Paused);
```
_Question: Why is the last ```set(State::Pause)``` needed, since the API states that ```prepare``` "preloads a media and then becomes State::Paused"?_

In my code, all steps are applied, but in different parts of the code, so I can't show a simple snippet. But they are there, triple checked, in that order. **Seeking while pause doesn't render the frame.** As mentioned, seeking while playing works perfectly, and playback resumes correctly after seeking while pause.

I tried placing the ```set(State::Pause)``` in different places, like in a callback for ```prepare```. Didn't help.
I tried calling ```renderVideo()```, either directly after ```prepare```, either in a callback. Nothing.
I tried setting ```setPreloadImmediately(true)``` and ```setProperty("continue_at_end", "1")``` in the constructor of the MDKPlayer. Same thing.
I tried setting ```SetGlobalOption("videoout.clear_on_stop", 0);``` in ```main()``` or in the constructor of the player, or immediately before ```set(PlaybackState::Stopped)```. No good.

Is it something else I'm missing about this?

I appreciate any help. Thanks!

**Comment by alexcristd** [comment]
Is there a separate log file saved somewhere? Or do I need to explicitly set a log handler?

I used:
```c++
    MDK_NS::SetGlobalOption("logLevel", "All");
    MDK_NS::SetGlobalOption("ffmpeg.loglevel", "trace");
```
in ```main()```, but all I got related to MDK in the QT console was (stripped other app-specific logging):
```
//// starting playback
MDK 0.14.2 (git c757f57) - Multimedia Development Kit. Copyright (c) 2016-2022 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Windows0x0600 x86_64; Clang14.0.1 MSVC1920; MSVCRT14.28.29333.0/msvcp140.dll; 14:32:31 May 15 2022
get Context 000000001E4EC820/0000000000030000 has no local data for key 0000000000000001, create 1(0000000014BB9500)
get Context 000000001E4EC820/0000000000030000 has no local data for key 0000000000000000, create 1(0000000014BB8A80)

/// pausing playback, then seeking to a different file
> 00:02:07.5/00:05:00 diff: |-0.074| > 0.005s, vo delay 0.000, @1.000, drop: 0, buffered: 3670ms/8209KB
```
The last line above is always shown last in the console, updates in realtime when playing, and updates correctly when seeking while paused, showing that the seek is indeed done correctly, only the rendering is missing.

Can I enable more detailed logging?

**Comment by wang-bin** [comment]
with `setLogHandler` you can write log in a file

**Comment by alexcristd** [comment]
Here's the log: https://drive.google.com/file/d/1UjvhveHXUtlW8SysNNkW3prTvI5IcwAH/view?usp=sharing

At line 36.113 I pause the playback, then I seek to a different file. Thanks!

**Comment by wang-bin** [comment]
it's hard to find out the bug from log. can you provide a minimal example?

**Comment by alexcristd** [comment]
Working on the minimal example I finally found the issue in my own code. :( It indeed works fine (or will work, after I'll clean up the mess I've made searching for this issue...).

Thanks a lot for your time and I'm very sorry to have wasted it. :(
