### ISSUE TITLE
How to change rtsp latency?

### ISSUE THREAD

**Issue by toan-tq** [wang-bin/mdk-sdk#56]
Hello,

Does 
The lib QtAV has BufferMode mode so I can change latency of realtime rtsp stream.
Does mdk-sdk library have similar option?

**Comment by wang-bin** [comment]
no BufferMode. `Player.setBufferRange()` can do the same work, but it's already set to proper values for rtsp. you can apply ffmpeg avformat options, see https://github.com/wang-bin/mdk-sdk/wiki/Troubleshooting#mosaic-and-high-latency-in-rtsp
