### ISSUE TITLE
SetGlobalOption("logLevel", "Off") has incorrect effect

### ISSUE THREAD

**Issue by alexcristd** [wang-bin/mdk-sdk#57]
Using Qt5 with MinGW 8.1.0 64bit on Windows 10 64bit, and MDK 0.14.2.

**Issue:** Calling ```SetGlobalOption("logLevel", "Off")``` still produces logging output of type ERROR and INFO.

**Notes:**
```SetGlobalOption("logLevel", LogLevel.Off)``` and ```SetGlobalOption("logLevel", 0)``` behave correctly, no output is generated.
Also other string calls, such as ```SetGlobalOption("logLevel", "Error")``` seem to work correctly. Only the "Off" string call seems wrong.

Can you please double check what's wrong? I integrated the logging options in an integrated logging system of my application, and it's easier to configure strings, but this issue kinda overloads my logs when I don't need it. :)

Thanks!

**Comment by wang-bin** [comment]
Yes, i forgot to handle "Off" case
