### ISSUE TITLE
Frame-accurate seek, inconsistent behavior

### ISSUE THREAD

**Issue by alexcristd** [wang-bin/mdk-sdk#60]
Hello,

Using Qt5 with MinGW 8.1.0 64bit on Windows 10 64bit, and MDK 0.14.2

I'm having some issues with frame accurate seeking, both ways.

**Seeking forward**
Using: ```internal_player->seek(1, SeekFlag::Frame | SeekFlag::FromNow);```
The seek seems ok, the image is updated, but the result of ```internal_player->position()``` is **NOT** changed. Therefore, any UI elements that need to show accurate position can't be updated during frame seeking.

**Backward seeking**
I know there's a bug with direct frame backward seeking. Is there any progress on that? For my application, frame seeking is extremely important.

I tried the workaround described in [another issue](https://github.com/wang-bin/mdk-sdk/issues/28), computing based on framerate, but it's not working. I've tried these 2 approaches:
```
    auto framerate = internal_player->mediaInfo().video[0].codec.frame_rate;
    auto frameDuration = 1000.0 / framerate;
    auto position = internal_player->position() - frameDuration;

    internal_player->seek(position, SeekFlag::FromStart);
```
```
    auto framerate = internal_player->mediaInfo().video[0].codec.frame_rate;
    auto frameDuration = 1000.0 / framerate;

    internal_player->seek(-frameDuration, SeekFlag::FromNow);
```

Both of them work for a couple clicks, then they just get stuck at some particular point (maybe a keyframe?). Any help with this, please? I've tried everything I could think of...

One more note: because the forward seek doesn't update the player's internal position, if I click on forward seek a bunch of times, and then once on backward seek, it jumps all the way back to the original position when playback was initially paused.

**Comment by wang-bin** [comment]
i will fix it add try to add backward frame seeking this weekend.

**Comment by wang-bin** [comment]
Try the latest build. Both bugs are fixed. Backward seeking is not optimized for now and it's slow. the first parameter `pos` can be -1, -2, -3 etc. frame rate must be known.

**Comment by alexcristd** [comment]
Thank you! :)

Preliminary testing shows that everything is ok for MP4/MOV files. There is no significant/noticeable slowness on backward seeking if MDK logging is fully disabled. If logging is enabled, there is indeed a very slight delay, but nothing to worry about.

However, for TS files (local/offline files, not online streams) it doesn't seem to work. MDK reports the framerate correctly (30), but backward seeking behaves as with the workaround: it may work for 1-2 clicks (although the positioning seems incorrect), then it gets stuck. If you need a sample file, I'll try to provide one.

**Comment by alexcristd** [comment]
Not sure how useful this is, but other (closed source) players, like PotPlayer, handle this correctly. Forward seeking is instant, but backward seeking has a slight delay, so it also seems to be based on decoding.

**Comment by wang-bin** [comment]
ts backward seek is improved in the latest build
