### ISSUE TITLE
Wrong playback speed for some videos (fast forward)

### ISSUE THREAD

**Issue by alexcristd** [wang-bin/mdk-sdk#61]
Hello,

Using Qt5 with MinGW 8.1.0 64bit on Windows 10 64bit, and MDK 0.14.2 nightly (as of yesterday).

Not sure for how long this has been an issue (I'm pretty sure it worked fine a while back, but I'm not 100%).

[speedy.zip](https://github.com/wang-bin/mdk-sdk/files/8942523/speedy.zip)

I have 3 sample videos (**nok1, nok h264, nok265** in the attached ZIP), gathered from some random sample site that I don't remember right now. 2 of them are h264, one is h265. These are **problematic**.

I have 1 sample video (**ok.mp4** in the attached ZIP, but any other video that I tested behaves the same). These are **ok**.

*Scenarios:*
1) If I play any of the **problematic** file first, it plays perfectly

2) If I play one **ok** file first, then a **problematic** file, the **problematic** file is played on very fast forward.

3) If I play any **problematic**(2) file right after another **problematic**(1) file, then (2) plays correctly, even if (1) was on fast forward - assuming that (1) was played after an **ok** file.

So:
playing **problematic** => ok
playing **problematic** + **problematic** => ok
playing **ok** + **problematic** => fast forward
playing **ok** + **problematic** (fast) + **problematic** => ok

Can you please investigate what's wrong?

Thanks!

**Comment by wang-bin** [comment]
which example?

**Comment by wang-bin** [comment]
i mean the example code. i can't reproduce the bug in glfwplay

**Comment by wang-bin** [comment]
fixed in the latest build.

**Comment by alexcristd** [comment]
Thanks!
