### ISSUE TITLE
Thumbnail extraction

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#62]
Hello, 

I would like to extract a thumbnail, so i have checked your native/thumbnail.cpp example. 
I dont use VideoFrame::save, i only want a QImage

* how to get the orientation? image is not correctly oriented for vertical video

**Comment by wang-bin** [comment]
frame.to(PixelFormat::RGBA) then use VideoFrame.bufferData() and bytesPerLine().

orientation is mediaInfo().video[0].rotation.

**Comment by pierrexn** [comment]
Thank you
