### ISSUE TITLE
在win7 上运行

### ISSUE THREAD

**Issue by chengxiaosheng** [wang-bin/mdk-sdk#66]
您好：
   我在win7上运行 mdk-sdk 时， 当设置媒体路径并播放的时候，mdk.dll 会抛出 0xc0000005 异常，导致程序崩溃。
请问我应该如何操作?

**Comment by wang-bin** [comment]
运行的是哪个例子？glfwplay能运行吗？

**Comment by chengxiaosheng** [comment]
@wang-bin 我在WIN7上断点调试 输出如下：
![image](https://user-images.githubusercontent.com/9647185/183705600-f7346b40-f576-4239-a5b0-c38d932ba925.png)
这里是否与 声音驱动有关呢 ？

**Comment by wang-bin** [comment]
对，dsound崩溃了，最新包已修复。另外建议安装xaudio2 驱动，默认会使用xaudio2，bug也在最新包里修复
