### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#67]
Hello, i have a problem on linux ubuntu 20, when i try to load a video file, on my Qt App i have this error (i use QMDKWidget)

"
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
"

the x11play works

an idea? 

(no problem with previous QtAV)

**Comment by wang-bin** [comment]
something wrong in your qt code or environment. make sure you can run a simple QOpenGLWidget app.
