### ISSUE TITLE
Question prebuildet SDK with braw?

### ISSUE THREAD

**Issue by dotxyzcf** [wang-bin/mdk-sdk#69]
Hello,

i dont understand anything in the documentation. It says i need to add a global Option, but WHERE??? Is there a prebuild SDK + braw Plugin?

**Comment by wang-bin** [comment]
> i dont understand anything in the documentation. It says i need to add a global Option, but WHERE???

`SetGlobalOption("plugins", "mdk-braw"); // before any Player is created, for example, in main()`

> Is there a prebuild SDK + braw Plugin?

Already in the sdk, mdk-braw.dll/so/dylib. You also need braw api libraries from blackmagic site or download from https://sourceforge.net/projects/mdk-sdk/files/deps/braw/, extract the dll/so/framework to the same location of mdk library(macos location may be different, if fails, find `braw bundle url:` in the log).

This is the decoder's full document: https://github.com/wang-bin/mdk-sdk/wiki/Decoders#braw

**Comment by wang-bin** [comment]
You can try [glfwplay example](https://github.com/wang-bin/mdk-examples/blob/master/GLFW/glfwplay.cpp#L286):
`./glfwplay -plugins mdk-braw 123.braw`

on windows, you can also run `install.bat` in the sdk, and then right click a braw file and open with mdk player

**Comment by dotxyzcf** [comment]
ok. im working on linux machines...

**Comment by dotxyzcf** [comment]
dbkg-based systems most, like ubuntu or debian.

**Comment by dotxyzcf** [comment]
![grafik](https://user-images.githubusercontent.com/92203938/188276385-be859cc7-577a-4e1c-b8ae-5ca8d35e8955.png)
so i have this now. you sayed, that i need to copy the black magic api things into the md-sdk folder? and then?

For beginners it would be nice:

if there is a 100% prebuilded BINARY for windows, linux, mac... Than users just need to download the latest release binary and execute them over a terminal or something like that.

**Comment by wang-bin** [comment]
```
cp -af BlackmagicRawAPI2.6-linux64/*.so mdk-sdk/lib/amd64/
cd mdk-sdk/bin/amd64
./glfwplay -plugins mdk-braw clip.braw
./glfwplay -plugins mdk-braw -c:v BRAW:gpu=auto:copy=1:scale=1920x1080 clip.braw # faster
```

> For beginners it would be nice:
> 
> if there is a 100% prebuilded BINARY for windows, linux, mac... Than users just need to download the latest release binary and execute them over a terminal or something like that.

Yes, but it's a plugin, and braw api libraries size is too large

**Comment by dotxyzcf** [comment]
and how to convert with the arguments?

**Comment by wang-bin** [comment]
convert to what?

**Comment by dotxyzcf** [comment]
.mov for proxy editing

**Comment by wang-bin** [comment]
no convert api yet, but you can use Player.onFrame() to get rgb frames and encode by yourself. you can also try gyroflow, the plugin is used in that app, and can convert to other formats

**Comment by wang-bin** [comment]
no convert api yet, but you can use Player.onFrame() to get rgb frames and encode by yourself. you can also try gyroflow, the plugin is used in that app, and can convert to other formats

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
