### ISSUE TITLE
rk3568板子 CMAKE_SYSTEM_PROCESSOR 匹配失败

### ISSUE THREAD

**Issue by programClown** [wang-bin/mdk-sdk#71]
您好，我这里在rk3568板子上测试的时候，FindMDK.cmake执行到
`
elseif(CMAKE_SYSTEM_NAME STREQUAL Linux)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "ar*64")
    set(_IMPORT_ARCH arm64)
`
匹配不成功，改成
`
if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
`
没有问题。

**Comment by wang-bin** [comment]
应改为 "ar.*64"

**Comment by programClown** [comment]
OK，这样好了
