### ISSUE TITLE
全志平台缺少 libglapi.so.0 和 libXext.so.6

### ISSUE THREAD

**Issue by wrs000001** [wang-bin/mdk-sdk#73]
你好，我将你交叉编译好的
ffmpeg-master-sunxi-clang-lite.tar
mdk-sdk-sunxi.tar
sysroot.tar
放到全志平台上，运行 DecodeFps 时提示缺少  libglapi.so.0，运行 ffmpeg 时提示缺少 libXext.so.6
请问这样如何解决

**Comment by wang-bin** [comment]
我用的是很多年前的sysroot编译的，现在也估计没人用了不再编译。你可以提供一份你的sysroot我来交叉编译。
