### ISSUE TITLE
怎么直接使用QWidget去渲染，而不是用QOpenGLWidget？

### ISSUE THREAD

**Issue by liquanguo** [wang-bin/mdk-sdk#74]
我这边使用的框架为QGraphicsView，如果把QOpenGLWidget直接使用scene::addWidget()的情况下，视频无法刷新（调用this->viewPort().update()是可以，但是很消耗CPU并且视频显示不流畅）
所以，我想问问，如何集成到QGraphicsView中呢？或者直接使用QWidget去渲染？
谢谢！

**Comment by wang-bin** [comment]
回头我写个例子。可能会新加接口

**Comment by liquanguo** [comment]
> 回头我写个例子，可能会新加接口。QWidget不支持，必须要有opengl。

好的，谢谢。

**Comment by wang-bin** [comment]
现有接口实现的例子，需要启用opengl  https://github.com/wang-bin/mdk-examples/tree/master/Qt/graphicsview
