### ISSUE TITLE
MFT和d3d11拉取网络流，无法使用硬解

### ISSUE THREAD

**Issue by jun-zhang** [wang-bin/mdk-sdk#75]
MFT和d3d11拉取网络流，无法使用硬解
日志文件：
[log.txt](https://github.com/wang-bin/mdk-sdk/files/10017497/log.txt)

**Comment by wang-bin** [comment]
log显示有画面出来了，你那边现象是什么？用D3D11解码器呢？能否用ffmpeg命保存一份视频文件让我看看
```
ffmpeg -an -i url -c copy test.h264
```

**Comment by jun-zhang** [comment]
视频显示出来的，应该采用的是软解，gpu上没有显示decoder占用。cpu占用4%左右，应该是用的软解。
[test.zip](https://github.com/wang-bin/mdk-sdk/files/10020375/test.zip)

**Comment by wang-bin** [comment]
是在硬解，视频画面变化不大解码消耗小。对比软解cpu使用率还是有区别的

**Comment by jun-zhang** [comment]
这个是使用demo播放的
![image](https://user-images.githubusercontent.com/6859306/202331099-4d62cff2-e443-4959-abf5-fd21ce2f8efa.png)
这个是使用vlc播放的相同的
![image](https://user-images.githubusercontent.com/6859306/202331189-1c2256d0-1c69-4a3a-92a0-b871c824eafe.png)
差别很明显

**Comment by wang-bin** [comment]
MFT确实只用了软解。ffmpeg的D3D11也解码失败。用QSV倒是能解码。原因暂时还不清楚

**Comment by wang-bin** [comment]
可能是baseline不会使用硬解，MFT貌似没法控制。使用 "D3D11:ignore_profile=1"作为解码器可以强制硬解 baseline

**Comment by jun-zhang** [comment]
ignore_profile=1 确实可用
