### ISSUE TITLE
mdk-sdk有源码吗，怎么下载的？

### ISSUE THREAD

**Issue by liquanguo** [wang-bin/mdk-sdk#76]
mdk-sdk有源码吗，怎么下载的？
我通过执行 mkmdk.sh 都是错误，下不了啊

                                             bash: fork: retry: Resource temporarily unavailable
538060269 [main] bash 1534 dofork: child -1 - forked process 20788 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
                                             bash: fork: retry: Resource temporarily unavailable
546145059 [main] bash 1534 dofork: child -1 - forked process 24444 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
                                             bash: fork: Resource temporarily unavailable
546157734 [main] bash 1534 dofork: child -1 - forked process 19672 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
                                             bash: fork: retry: Resource temporarily unavailable
547174998 [main] bash 1534 dofork: child -1 - forked process 19852 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
                                             bash: fork: retry: Resource temporarily unavailable
549192325 [main] bash 1534 dofork: child -1 - forked process 17164 died unexpectedly, retry 0, exit code 0xC0000135, errno 11
                                             bash: fork: retry: Resource temporarily unavailable
553221576 [main] bash 1534 dofork: child -1 - forked process 22372 died unexpect

**Comment by wang-bin** [comment]
不提供源码，只有部分模块开源供学习

**Comment by liquanguo** [comment]
> 不提供源码，只有部分模块开源供学习

好的，大哥，有空帮忙加个接口集成到QGraphicsView中，谢谢了

**Comment by wang-bin** [comment]
> > 不提供源码，只有部分模块开源供学习
> 
> 好的，大哥，有空帮忙加个接口集成到QGraphicsView中，谢谢了

https://github.com/wang-bin/mdk-examples/tree/master/Qt/graphicsview
