### ISSUE TITLE
mdk是否支持输入并渲染单帧图像数据？

### ISSUE THREAD

**Issue by RekiDunois** [wang-bin/mdk-sdk#78]
以前用QtAV的做法是将视频流的每一帧都包装成 QtAV::VideoFrame，然后使用QtAV::VideoOutput中的receive方法来渲染每一帧到widget中，达到播放视频流的目的。

请问mdk有没有相关接口能支持类似的功能？

**Comment by wang-bin** [comment]
可以加个接口

**Comment by wang-bin** [comment]
用最新的包使用Player.enqueue()接口 https://github.com/wang-bin/mdk-sdk/wiki/Player-APIs#void-enqueueconst-videoframe-frame-void-vo_opaque--nullptr
