### ISSUE TITLE
请问作者是否有编译好的带硬件解码的FFMPEG for andriod?

### ISSUE THREAD

**Issue by ShenYuan-sean** [wang-bin/mdk-sdk#80]
我对比了FFMPEG和MDK在PC端的RTSP延迟情况，发现MDK的延迟略大。我想采用ffmpeg在安卓设备上面再对比一下，但是我没有ffmpeg的Android的库（带硬件解码,arm-v8a  64bit）。不知道您是否可以提供一下？
非常感谢！

**Comment by wang-bin** [comment]
有，https://github.com/wang-bin/avbuild

编译好的每周自动更新一次最新的，在 https://sourceforge.net/projects/avbuild/files/android/

**Comment by wang-bin** [comment]
延迟是对比ffplay？

**Comment by ShenYuan-sean** [comment]
我自己用ffmpeg的库写的，就是很常规的流程，ffplayer我这两天也一起测试对比一下相对MDK的延迟。非常感谢您提供的ffmpeg！我测试延迟的方法就是通过一个RTSP的摄像机拍摄手机的秒表，然后截图对比不同软件的延迟。
