### ISSUE TITLE
How to set a video filter?

### ISSUE THREAD

**Issue by lsangemi** [wang-bin/mdk-sdk#81]
Hi, how to set a video filter properly for the player? I guess I should use the player's setProperty(k,v) function, so how to set a "setpts=0" filter? I tried with 

m_player->setProperty("video.avfilter", "setpts=0");

but had no luck. Thank you again!

**Comment by wang-bin** [comment]
setpts filter is disabled in my prebuilt ffmpeg, you can download one with default configuration, for example https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-master-windows-desktop-vs2022-default.7z/download

**Comment by lsangemi** [comment]
Ok, I'm basically referring to Player.h of mdk-sdk, so I'm using the shared object only (libffmpeg.so.5). If I got you, I think that replacing that library with the one included in the "default" package, I should get by. Could you confirm I'm passing the key,value pair correctly to the setProperty function ("video.avfilter", "setpts=0")?

Thank you

**Comment by wang-bin** [comment]
correct. If you want' set pts to 0, you can call `VideoFrame.setTimestamp()` in `onFrame()` callback.

**Comment by lsangemi** [comment]
Ok, it's done. Thank you!
