### ISSUE TITLE
使用mdk-sdk播放视频时，播放视频的最后一帧出现一个二维码，这个怎么关闭？

### ISSUE THREAD

**Issue by liquanguo** [wang-bin/mdk-sdk#85]
使用mdk-sdk播放视频时，播放视频的最后一帧出现一个二维码，这个怎么关闭？
二维码截图：
![md-sdk](https://user-images.githubusercontent.com/19346612/218035279-5cdd8af5-99c8-442c-b6c7-b0debc72f291.png)
使用微信扫描后，二维码显示的信息如下：

MDK SDK is outdated. Get a new free sdk from
https://sourceforge.net/projects/mdk-sdk/files/nightly or purchase a license. paypal:
https://www.paypal.me/ibingow/500 more: https://www.qtav.org/donate.html

请问，这个二维码怎么关闭的

**Comment by wang-bin** [comment]
保持sdk是最新的，否则40天后会出现二维码。也可以邮件或qtav群里问我要授权码

**Comment by liquanguo** [comment]
授权码收费的吗？另外授权码需要多久一次，怎么使用的？




李慕容
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-bin/mdk-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月11日(星期六) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-bin/mdk-sdk] 使用mdk-sdk播放视频时，播放视频的最后一帧出现一个二维码，这个怎么关闭？ (Issue #85)





 
&nbsp;保持sdk是最新的，否则40天后会出现二维码。也可以邮件或qtav群里问我要授权码

**Comment by wang-bin** [comment]
目前国内用户免费，永久授权。

**Comment by liquanguo** [comment]
好的，那麻烦发一个授权码到我的邮箱（706414069@qq.com），谢谢了，授权码怎么用的也说一下，非常感谢

**Comment by wang-bin** [comment]
需要知道你的程序运行的系统（win、linux、mac、ios、android），还有程序相关的其他信息。请发我邮件联系

**Comment by liquanguo** [comment]
目前我这边主要在Windows11、10、7，Linux、macOS上使用，程序的话Windows32位64位都有，还需要其他信息吗


***@***.***;





李慕容
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-bin/mdk-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月11日(星期六) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-bin/mdk-sdk] 使用mdk-sdk播放视频时，播放视频的最后一帧出现一个二维码，这个怎么关闭？ (Issue #85)





 
需要知道你的程序运行的系统（win、linux、mac、ios、android），还有程序相关的其他信息。请发我邮件联系

**Comment by wang-bin** [comment]
程序名，windows还有rc文件里的公司名、产品名，mac需要包名

**Comment by feiyangqingyun** [comment]
王总，我今天也出现了二维码，麻烦给我来一份，信息如下。
                                VALUE "CompanyName", "xxx\0"
                                VALUE "FileDescription", "video_xxx\0"
                                VALUE "FileVersion", "2024,9,20,0\0"
                                VALUE "LegalCopyright", "Copyright (C) 2025\0"
                                VALUE "OriginalFilename", "video_xxx.exe\0"
                                VALUE "ProductName", "video_xxx\0"
                                VALUE "ProductVersion", "2024,9,20,0\0"
谢谢，只要win和linux就行
