### ISSUE TITLE
App Store submission rejected

### ISSUE THREAD

**Issue by julienchevet** [wang-bin/mdk-sdk#86]
When I try to submit my application to the App Store, it is rejected with the following errors:

> Asset validation failed
> Invalid bundle structure. The “MyApp.app/Frameworks/mdk.framework/libffmpeg.5.dylib” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle

> Asset validation failed
> Invalid Bundle. The bundle MyApp.app/Frameworks/mdk.framework does not support the minimum OS Version specified in the Info.plist.

> Asset validation failed
> Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle MyApp.app/Frameworks/mdk.framework is required.

> Asset validation failed
> Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'Kalismart.app/Frameworks/mdk.framework' is ''.

Do you know why and how to fix them?

- Qt 6.4.2
- MDK-SDK iOS installed with cocoapods
- Xcode 14.1

**Comment by wang-bin** [comment]
> Invalid bundle structure. The “MyApp.app/Frameworks/mdk.framework/libffmpeg.5.dylib” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle

I have to change libffmpeg.5.dylib to a framework

Other errors are about info.plist

**Comment by wang-bin** [comment]
the latest sdk fixes these errors. i usually don't increase pod version, so may have to run
```
pod deintegrate
pod cache clean mdk
pod update
```
to ensure the latest sdk is downloaded

**Comment by julienchevet** [comment]
It works, no more App Store issues, thanks
