### ISSUE TITLE
视频缓存在使用seek之后会被清理掉

### ISSUE THREAD

**Issue by TYUTthelastone** [wang-bin/mdk-sdk#87]
我播放https格式的视频时，简单的暂停播放缓存不会消失，但是seek之后视频缓存就会被清空，请问有什么办法可以像其它播放器一样看到缓存进度并且支持seek吗

**Comment by wang-bin** [comment]
url前面增加cache: ,比如 `cache:http://.....`，这个是用ffmpeg自带的缓存功能，我这边没有进度信息

**Comment by TYUTthelastone** [comment]
ok,成功解决了

**Comment by wang-bin** [comment]
最新包`player.setProperty("demux.buffer.ranges", "8"/*or other number*/)`可以对http(s)流进行缓存，8表示最多可以缓存8段数据，根据LRU规则丢弃。seek到未缓存的位置会开始一段新缓存，当前缓存段增长过程中与下一段重叠了会合并。seek到已缓存的位置不会重新下载。查看所有缓存用`player.bufferedTimeRanges()`，ui上可以根据这个返回值自绘个进度条显示已缓存的时间段（mpv的进度条有这功能）
