### ISSUE TITLE
Metal: yuv420p CVPixelBuffer garbage color

### ISSUE THREAD

**Issue by wang-bin** [wang-bin/mdk-sdk#9]
How to produce:

`glfwplay -metal -c:v VT:format=yuv420p test.mp4`

or

`glfwplay -metal -c:v FFmpeg:pool=CVPixelBuffer test.mp4`

![image](https://user-images.githubusercontent.com/785206/84912319-e5f40880-b0eb-11ea-842b-2c8dd525256c.png)

**Comment by debugly** [comment]
@wang-bin 

Hello bin, how to fix the bug?

**Comment by wang-bin** [comment]
everything is fine on m1. it's a system bug

**Comment by debugly** [comment]
Yes, it is. Intel works fine except Integrated graphics.
