### ISSUE TITLE
字幕的语言类型在哪里获取？

### ISSUE THREAD

**Issue by TYUTthelastone** [wang-bin/mdk-sdk#92]
SubtitleStreamInfo里面只有解码器的信息，解码器里面的额外信息也是空的，找不到字幕信息放在哪里

**Comment by wang-bin** [comment]
用最新的包，SubtitleStreamInfo.metadata["language"]

**Comment by TYUTthelastone** [comment]
我用的0.20的包，里面的SubtitleStreamInfo的定义依然是：
struct SubtitleStreamInfo {
    int index;
    int64_t start_time;
    int64_t duration;

    SubtitleCodecParameters codec;
};

**Comment by wang-bin** [comment]
刚加的，最新包从 https://sourceforge.net/projects/mdk-sdk/files/nightly/ 下载 或 https://github.com/wang-bin/mdk-sdk/actions/runs/4458770145

**Comment by TYUTthelastone** [comment]
ok,现在可以用了
