### ISSUE TITLE
频繁的SEEK操作后，RenderAPI 上报的进度值不再更新

### ISSUE THREAD

**Issue by flowerlove** [wang-bin/mdk-sdk#94]
mdk版本 0.20.0；
进度条变化时发送SEEK命令，比如从1秒拖拽到30秒，会发30次SEEK命令：mdk_player_->seek(newTime, MDK_NS::SeekFlag::Default);
之后打印mdk_player_->position()值，发现不再变化，一直停留在某个值的位置。

**Comment by flowerlove** [comment]
Windows版本

**Comment by flowerlove** [comment]
此时画面和声音都正常，仅仅是返回的position值不再变化，再次SEEK就可以恢复。

**Comment by wang-bin** [comment]
可能是seek有bug

**Comment by wang-bin** [comment]
容易复现吗？我用glfwplay -log all 测试没复现。有没有测试用例？

**Comment by flowerlove** [comment]
> 



> 容易复现吗？我用glfwplay -log all 测试没复现。有没有测试用例？

容易复现，我在进度条valueChanged槽函数里做SEEK操作，几下就出来了，比如从0拖拽到1分钟，期间就会SEEK60次，不过后来我增加了SEEK的callback函数，在里面增加SEEK的判断条件，只有上一次SEEK完成才会执行下次SEEK，目前就没有再出现这个问题了。

**Comment by wang-bin** [comment]
内部也使用了seek未完成丢弃新seek的机制

**Comment by wang-bin** [comment]
试下最新的
