### ISSUE TITLE
不断的销毁和创建播放器，发现内存不断上涨

### ISSUE THREAD

**Issue by ken626014896** [wang-bin/mdk-sdk#96]
最新的sdk，win10平台
测试的是例子里面的qml工程,析构是正常的
一个1mb左右的视频，每次会有80mb的涨幅
经测试，QMetaObject::invokeMethod(this, "update") 注释这句话，就没内存上涨了，好像是渲染的问题?
```
{
    //    SetGlobalOption("logLevel",0);
    setLogHandler([](LogLevel v, const char* msg){
        if (v < LogLevel::Info)
            qWarning()<<"MDK-JNI"<< msg;
        else
            qDebug()<<"MDK-JNI"<< msg;
    });

    SetGlobalOption("logLevel","all");
    SetGlobalOption("profiler.gpu", 1);

    setMirrorVertically(true);
#ifdef Q_OS_WIN
    internal_player->setDecoders(MediaType::Video, {"D3D11","MFT:d3d=11:copy=0", "CUDA", "FFmpeg"});
#endif

}

QmlMDKPlayer::~QmlMDKPlayer()
{
    qDebug()<<__FUNCTION__;
    internal_player->setMedia("");
    internal_player->set(PlaybackState::Stopped);
    delete internal_player;
}
```

[2023-05-18.txt](https://github.com/wang-bin/mdk-sdk/files/11506285/2023-05-18.txt)
销毁播放器会打印QmlMDKPlayer::~QmlMDKPlayer  旧的sdk好像是去年的版本没这个问题

**Comment by ken626014896** [comment]
android好像也有相同情况

**Comment by wang-bin** [comment]
哪个例子哪个qt版本？

**Comment by ken626014896** [comment]
例子是mdk-examples/Qt/qml 这个
qt版本是5.15.2  另外我用qt5.12.4也有同样情况

main.qml 我改成这个了，模拟不断的销毁和创建播放器的过程
```
Repeater{
        id:rep
        model:1
        MDKPlayer {
            id: mediaplayer
            z:3
            width: root.width
            height: root.height
            source: "f:/video/a.mp4"

        }
    }

    Rectangle{
        width: parent.width
        height: 60
        anchors.bottom: parent.bottom
        color: "green"
        z:6
        Text {
            text: qsTr("重新加载")
            anchors.centerIn: parent
            font.bold: true
            color: "white"
        }
        MouseArea{
            anchors.fill: parent
            onClicked: {
                rep.model=0
                rep.model=1
            }
        }
    }
```

https://github.com/wang-bin/mdk-sdk/assets/38373469/3c25fd66-cc9f-4c5f-b03a-3fdc75f8542f
不用internal_player->setDecoders 指定某个解码器的话，内存涨幅会低很多

**Comment by wang-bin** [comment]
qt5默认用的是desktop opengl，d3d解码渲染资源释放不干净是已知问题，不确定是谁的问题，你可以换成OpenGLES渲染，或用qt6 d3d11渲染。

**Comment by ken626014896** [comment]
QCoreApplication::setAttribute(Qt::AA_UseOpenGLES); 设置之后，电脑内存释放正常了，但是安卓好像还是一样

**Comment by ken626014896** [comment]
大佬安卓上面换成OpenGLES渲染还是会有内存泄漏的情况，请问目前修复的怎么样了，还是说是qt本身渲染的问题

**Comment by wang-bin** [comment]
周末再修。你看看是不是解码器有关

**Comment by wang-bin** [comment]
qt android我这边编译不了没法测

**Comment by ken626014896** [comment]
最新sdk 安卓测试，一切换播放器就崩溃了，win的不使用OpenGLES 渲染的话还是依旧上涨，但是不奔溃

    internal_player->setDecoders(MediaType::Video,{"AMediaCodec:java=0:copy=0:surface=1:async=1:image=1"});
//internal_player->setDecoders(MediaType::Video,{"AMediaCodec:java=0:copy=0:surface=1:async=1:image=0"}); 
//internal_player->setDecoders(MediaType::Video,{"MediaCodec:threads=1"});
// internal_player->setDecoders(MediaType::Video,{"FFmpeg"});
这几种解码设置都试了下，都是会奔溃

[mdk.log](https://github.com/wang-bin/mdk-sdk/files/11587357/mdk.log)
麻烦作者了

**Comment by wang-bin** [comment]
之前的sdk有奔溃吗？奔溃日志不能过滤当前app，要所有的，现在这个日志后面还会有一串堆栈信息用来定位行号的。win的默认gl渲染问题没修，不确定是不是我这边的问题

**Comment by ken626014896** [comment]
上个版本的sdk没这个问题，不是很懂(奔溃日志不能过滤当前app)这句话，我这边没有做过滤，log里面就是qt所有的打印信息

新的log在最后面我加上了debug时的信息你看看是不是这些，我看sdk好像死掉在析构函数里面
![image](https://github.com/wang-bin/mdk-sdk/assets/38373469/405dbc2d-dedb-4ae7-9eda-fa5c3dfa6cfb)

**Comment by ken626014896** [comment]
[mdk.log](https://github.com/wang-bin/mdk-sdk/files/11588745/mdk.log)

**Comment by wang-bin** [comment]
删gl资源时没上下文就挂了，你试试profiler.gpu不设。泄漏问题估计也和上下文有关，之前用image=0的情况我有处理，image=1我今天加一下

**Comment by wang-bin** [comment]
试下今天的版本会不会奔溃 https://github.com/wang-bin/mdk-sdk/actions/runs/5109593831

android泄漏问题还不清楚，我这边用address sanitizer没跑起来，其他系统上asan没看出问题，还是需要你对比下几个解码器是否都有泄漏

**Comment by ken626014896** [comment]
新的不会奔溃了，试了下internal_player->setDecoders(MediaType::Video,{"MediaCodec:threads=1"}) 这个是内存上涨是最快的，其他两个比较慢，这是我的测试工程，麻烦看看播放器初始化有没有问题
[testMDK.zip](https://github.com/wang-bin/mdk-sdk/files/11590052/testMDK.zip)

**Comment by wang-bin** [comment]
你可以把log发一下我看看有没有释放资源的相关日志

**Comment by ken626014896** [comment]
[mdk.log](https://github.com/wang-bin/mdk-sdk/files/11590422/mdk.log)
用的是internal_player->setDecoders(MediaType::Video,{"AMediaCodec:java=0:copy=0:surface=1:async=1:image=1"});
重复不断的销毁和创建了大概8次左右，播放器析构打印~QmlMDKPlayer

**Comment by wang-bin** [comment]
image相关资源没释放。你再给个 image=0的log

**Comment by ken626014896** [comment]
设置image=0,也是涨的
[mdk2.log](https://github.com/wang-bin/mdk-sdk/files/11591264/mdk2.log)

**Comment by ken626014896** [comment]
image=0也是涨了
[mdk2.log](https://github.com/wang-bin/mdk-sdk/files/11591279/mdk2.log)

**Comment by wang-bin** [comment]
你的例子没法显示画面，qmlrhi的例子我按你的改了下，在mac上资源释放和日志都正常。安卓没法测试，qt的安卓编译太垃圾，自从ant不能用只能用gradle之后从来没编译打包成功过，android studio啥的都正常。要不你改下qmlrhi的例子贴下日志? 只改qml，c++的话输出下日志，其他不要改

```diff
diff --git a/Qt/qmlrhi/main.qml b/Qt/qmlrhi/main.qml
index 23e4827..e8fc74e 100644
--- a/Qt/qmlrhi/main.qml
+++ b/Qt/qmlrhi/main.qml
@@ -8,12 +8,35 @@ Item {
     property string url
 
     //! [2]
+    Repeater{
+            id:rep
+            model:1
     VideoTextureItem {
         id: renderer
         anchors.fill: parent
         anchors.margins: 10
         source: url
     }
+    }
+    Rectangle{
+            width: parent.width
+            height: 60
+            anchors.bottom: parent.bottom
+            color: "green"
+            Text {
+                text: qsTr("重新加载")
+                anchors.centerIn: parent
+                font.bold: true
+                color: "white"
+            }
+            MouseArea{
+                anchors.fill: parent
+                onClicked: {
+                    rep.model=0
+                    rep.model=1
+                }
+            }
+        }
 
     Rectangle {
         id: labelFrame
```

**Comment by ken626014896** [comment]
使用qmlrhi测试,qt版本为5.15.2
发现内存会上涨一段时间,然后又回到正常
这个是这个时间的log
[mdk2.log](https://github.com/wang-bin/mdk-sdk/files/11594900/mdk2.log)

然后发现使用回调函数时,debug时很大概率出现崩溃,定时器就不会
```
   m_player->setRenderCallback([=](void *){
            QMetaObject::invokeMethod(this, "update");
    });
```
这个是debug信息,好像是播放器销毁了,继续调用了QMetaObject::invokeMethod(this, "update");
[mdk3.log](https://github.com/wang-bin/mdk-sdk/files/11594922/mdk3.log)

**Comment by wang-bin** [comment]
> 使用qmlrhi测试,qt版本为5.15.2 发现内存会上涨一段时间,然后又回到正常 这个是这个时间的log [mdk2.log](https://github.com/wang-bin/mdk-sdk/files/11594900/mdk2.log)
> 

这个日志很奇怪，有一部分资源释放换了种方法，忘记以前为啥换的了，换回来应该没问题，不过这两天要发新版本，可能要发版后再改回来。你用最新的包，然后用AMediaCodec解码，我昨天多加了些日志。

> 然后发现使用回调函数时,debug时很大概率出现崩溃,定时器就不会
> 
> ```
>    m_player->setRenderCallback([=](void *){
>             QMetaObject::invokeMethod(this, "update");
>     });
> ```
> 
> 这个是debug信息,好像是播放器销毁了,继续调用了QMetaObject::invokeMethod(this, "update"); [mdk3.log](https://github.com/wang-bin/mdk-sdk/files/11594922/mdk3.log)

析构里加个`m_player->setRenderCallback(nullptr)`试试

**Comment by wang-bin** [comment]
参考这个 https://github.com/AdrianEddy/qml-video-rs/blob/6805f191482c763d0b3f27e3266a0d940098d4a0/src/cpp/MDKPlayer.cpp#L69

**Comment by ken626014896** [comment]
那个例子好像是qt6的，我这边暂时没这个环境，用的是https://github.com/wang-bin/mdk-examples/tree/master/Qt/qmlrhi这个例子    
解码设置: m_player->setDecoders(MediaType::Video,{"AMediaCodec:java=0:copy=0:surface=1:async=0"});

目前测试内存是先上涨到90%左右，才突然恢复到正常的60%这样
[mdk.log](https://github.com/wang-bin/mdk-sdk/files/11597621/mdk.log)

**Comment by wang-bin** [comment]
image=0还有软解的日志也发一下

**Comment by ken626014896** [comment]
image=0   m_player->setDecoders(MediaType::Video,{"AMediaCodec:java=0:copy=0:surface=1:async=0:image=0"});

[mdk2.log](https://github.com/wang-bin/mdk-sdk/files/11598322/mdk2.log)

软解 m_player->setDecoders(MediaType::Video,{"FFmpeg"});
[mdk3.log](https://github.com/wang-bin/mdk-sdk/files/11598326/mdk3.log)

**Comment by wang-bin** [comment]
很奇怪，一直在delete同一个地址，这地址不知哪来的，删了也没异常

**Comment by wang-bin** [comment]
可能是上个版本引入的bug。试下最新的包，windows也可以测下 https://github.com/wang-bin/mdk-sdk/actions/runs/5122811987

**Comment by ken626014896** [comment]
测试了1个小时左右发现Android和pc内存目前已经稳定下来了，目前还没发现明显上涨，十分感谢作者!!

**Comment by wang-bin** [comment]
也非常感谢你报的bug和测试

**Comment by wang-bin** [comment]
对了，windows下用opengl不用opengles也不泄漏了是吗

**Comment by ken626014896** [comment]
是的，测试时我没开启opengles ，让它默认
![image](https://github.com/wang-bin/mdk-sdk/assets/38373469/96841912-55f8-4361-bc5b-60546a2512d9)
